### ISSUE TITLE
[please fix] forestry leaves cause crash

### ISSUE THREAD

**Issue by kreezxil** [kreezxil/World-of-Dragons#100]
https://github.com/ForestryMC/ForestryMC/issues/2385

This is closed at Forestry for some reason if tho it is still current.

**Comment by kreezxil** [comment]
Ok, it is definitely open here: https://github.com/ForestryMC/ForestryMC/issues/2336

Seems regular players are closing their own tickets instead of leaving them open for the developer to see that the issue is real. Seems I need to reach out to the Dev. Here's hoping I have success there.

**Comment by kreezxil** [comment]
Discovered that the Release build 322 does not have this issue, the pack will roll down to this version, i'm going to leave this open, because I would like to update as soon as they fix it and I don't want them to get the idea we fixed the issue because we did not. At least I don't have to write a CrT script to block silk touching.

**Comment by kreezxil** [comment]
I am now thoroughly involved in beta testing this issue. yay.

**Comment by Quotebookguy** [comment]
Any success, @kreezxil? Or any workarounds for those of us who suddenly can't load our save files without the game immediately crashing?

Thanks for tracking this down!

**Comment by kreezxil** [comment]
if you update to the latest pack release, you will be using version build
322 of forestry which does not have this problem. There is no solution yet.
Even the dev is at a loss for words but acknowledges it.

**Comment by kreezxil** [comment]
Further that solves the issue with your character file, my solution, which
is not the preferred solution but is a great interim solution.

**Comment by Quotebookguy** [comment]
I'll have to see if FTB Revelations (the mod pack I have that contains Forestry) similarly reverted to the previous version. Thanks!

**Comment by kreezxil** [comment]
FTB packs typically do not using bleeding edge mods like I do.

**Comment by kreezxil** [comment]
A massive rollback, and I need to test this out. To see which of the future versions I can actually use.

**Comment by kreezxil** [comment]
The data is no longer conclusive and somehow it's fixed itself? I'm so lost, I'll be updating this mod again for the pack. maybe the onslaught of bug reports that **should** ensue will help get it fixed, then again, maybe it won't.

A possible theory is that at the time forge build 2815 was buggy in a bad way. I don't have proof of this one thought, but I'm thinking that the forge team quietly replaced it with a version that wasn't as bad, or rather fixed.
