### ISSUE TITLE
[please fix] Can't craft Navigation Upgrade

### ISSUE THREAD

**Issue by suken27** [kreezxil/World-of-Dragons#103]
**Describe the bug**
The recipe of the item Navigation Upgrade of OpenComputers is not craftable because it includes the item "Uncraftable Potion" that, as its name implies, cannot be crafted. The recipe is not the same that apears in the mod wiki: https://ocdoc.cil.li/item:navigation_upgrade

**To Reproduce**
Just need to see the recipe in JEI. The items name is Navigation Upgrade.

**Screenshots**
![image](https://user-images.githubusercontent.com/48246954/54890286-eed63a00-4ea8-11e9-8204-947d5f11cf21.png)

**Versions:**
I found that in the USA server, at the time I'm posting this issue.

**Comment by kreezxil** [comment]
Seems one of the magic mods redefined the basic potion and its fixed in this situation.
