### ISSUE TITLE
[please fix] Water is Freezing in none cold biomes

### ISSUE THREAD

**Issue by irondragon12** [kreezxil/World-of-Dragons#104]
Im not 100% sure that this is a bug but my world's water blocks are all turning to ice in none cold biomes. This is the latest version of the pack. This all started when i spawned a Toroquest mage in to see it, but after killing it this started to happen.
![2019-03-26_15 52 44](https://user-images.githubusercontent.com/30564310/55038796-42e33a80-4fdf-11e9-84f5-2b5a9678b962.png)

EDIT: ok so it says plains but now it is snowing when i use to rain. Im super confused, please help me.

**Comment by irondragon12** [comment]
Ok now it is snowing almost everywhere i go.

**Comment by irondragon12** [comment]
and now my worlds floor has zeros on each blocks.

**Comment by irondragon12** [comment]
ok im done im just starting a new world but if there is a way to fix all this then please let me know.

**Comment by kreezxil** [comment]
First, the snow and ice and from Serene Seasons, didn't you notice the
foliage was changing too?

Serene Seasons also changes crop yields, so you can't just grow wheat
during the winter and expect it to produce as much.

Second, the numbers are Torch Optimizer. The more red and larger the number
the greater the chance a hostile mob will spawn on it. Hit F7 to turn off
numbers, avoid accidentally hitting the square brackets keys as that turns
on the cycle which changes where the asterisk appears in the number range.
The asterisk is where you should optimally place a torch. The asterisk can
be changed in case you are using a lesser light source or a greater one.

If you don't like either in your personal copy you can take out both mods.
I suggest you don't tho.
