### ISSUE TITLE
[please fix] Auto jumping with auto jump off.

### ISSUE THREAD

**Issue by irondragon12** [kreezxil/World-of-Dragons#105]
ok so i keep auto jumping up blocks with auto jump off and it is really starting to piss me off. Please help me find a fix for it. This is the latest version of the pack.

**Comment by kreezxil** [comment]
You're pissing me off with your language.

The auto jumping is happening because you are running and the name of the
mod is called Better Auto Jump. If you'd just walk from place to place it
wouldn't auto jump.
