### ISSUE TITLE
[please add] Just Mob Heads

### ISSUE THREAD

**Issue by kingslayer296** [kreezxil/World-of-Dragons#107]
Mod Name: Just Mob Heads
Mod Link: https://minecraft.curseforge.com/projects/just-mob-heads

I would like more heads to collect, and not just vanilla mobs but also mobs from other mods in the pack, however there doesn't seem to be any mods like that.
There is also a Just Player Heads mod made by the same author.

**Comment by kreezxil** [comment]
Thanks for your suggestion. I'll consider it for the next update.

**Comment by kreezxil** [comment]
this was added in build 171
