### ISSUE TITLE
Dragons too much hp & Myrmex Hives too rare

### ISSUE THREAD

**Issue by irondragon12** [kreezxil/World-of-Dragons#111]
in my opinion dragons have WAY too much hp and take forever to kill the normal ones not the stage 4-5 ones. I found a huge desert and could not find a myrmex hive, then i looked at the config.
![myrmex](https://user-images.githubusercontent.com/30564310/55266456-43c3d880-523a-11e9-9846-345754a4e806.PNG)
that is too insane and the dragons max hp at default is 500 but you set it to 5000 max hp. TOO MUCH.

**Comment by kreezxil** [comment]
as far as dragons go, they don't have too much HP, for your own server and copy of the modpack you may change the values in that config. In fact delete the config and let it generate naturally. For single player or a small group of friends the normal setting will be good for about 1 week. Then by that time you will have donned the most advanced armor the game has to offer as well as weapons and various augments and the dragons will no longer be a challenge.

As for the Myrmex issue, thanks for pointing that out. That should not have been. I'll correct it.

**Comment by irondragon12** [comment]
thx and what is the most op armor?

**Comment by kreezxil** [comment]
Most OP armor? probably the one you came make from techguns that is
basically cyberarmor that you can charge up and enhance with motors and
stuff. Or you can use Constructs Armory and do something extremely OP with
it. Please join my Discord, there are lots of discussions about what OP
armors and weapons there are in the pack.
