### ISSUE TITLE
Dynamic Trees Removal

### ISSUE THREAD

**Issue by irondragon12** [kreezxil/World-of-Dragons#112]
dynamic trees' trees drop very little amounts of wood, so could you please remove it?

**Comment by kreezxil** [comment]
No, I will not remove dynamic trees. As per the other issues where I suggest that you may remove it for your copy of the pack, go ahead.

Dynamic trees produce more wood than standard trees if you allow the trees to grow a long time. They work like real world trees. Baby trees that were saplings a few days before produce very little to no wood, but much older trees, such as those you allow to grow for 30 game days can produce upwards of 15 blocks of wood. The also look like it, engrossed, fattened and burgeoning.
