### ISSUE TITLE
[please add]  Custom npcs

### ISSUE THREAD

**Issue by ParsaMT** [kreezxil/World-of-Dragons#117]
# Mod Nominated for Adding*
Mod Name:custom npcs
Mod Link: https://minecraft.curseforge.com/projects/custom-npcs?gameCategorySlug=mc-mods&projectID=221826

# Reason for Nomination

Reason: we could add weekly quests by actual npc quest givers and make them interactable

**Comment by Draconian4466** [comment]
I could make some npcs too

**Comment by kreezxil** [comment]
added
