### ISSUE TITLE
[please add] Random PSIdeas

### ISSUE THREAD

**Issue by Amsel1** [kreezxil/World-of-Dragons#118]
# Mod Nominated for Adding*
Mod Name: Random PSIdeas
Mod Link: https://minecraft.curseforge.com/projects/random-psideas

# Reason for Nomination
 
Reason: the mod add more thing to psi so you can make better spells like support spells and theres better armor then the normal psi armor it adds more options for your psi like over clocked more senors a gun hoe fishing rod and shears cad a psi sheald it adds meny more Operator and Tricks so you can make vary cool spells also psi swords so you can make spells that use attacks to activate and cases for your cads

**Comment by kreezxil** [comment]
added
