### ISSUE TITLE
[please fix] dragon horn

### ISSUE THREAD

**Issue by Aurora940** [kreezxil/World-of-Dragons#119]
**Describe the bug**
The dragon horn from fire and ice there is a bug with it when you put a dragon in it it goes in but once you try and take it out it doesn't come out its like its deleted from the game

My suggestion is get rid of the horn since we have the morbs and they work

**Comment by kreezxil** [comment]
Hopefully rolling back fixes this, This has been a long standing bug.

**Comment by kreezxil** [comment]
stale
