### ISSUE TITLE
[please add] clay soliders

### ISSUE THREAD

**Issue by ParsaMT** [kreezxil/World-of-Dragons#120]
# Mod Nominated for Adding*
Mod Name: clay soliders
Mod Link: https://minecraft.curseforge.com/projects/clay-soldiers-mod

# Reason for Nomination

Reason: so now that pvp is off in both servers i was thinking about a kinda of competition between players and this mod provides what i want although we should probably make it a admin only thing since it can lag the server if someone makes too many of them ( players tend to do that alot ) so yeah it will be like a pokemon battle but with armies...of clay

**Comment by kreezxil** [comment]
how would the admin control it?

**Comment by ParsaMT** [comment]
by admin only i mean only we can get them via creative so in competitions we put them in vending machines and give the two players a certain amount of money. based on that they can buy different mounts,soliders ...etc and build they'r own army and battle against each other

**Comment by kreezxil** [comment]
Interesting.

**Comment by kreezxil** [comment]
not added. we have custom npcs now. we need to configure those first.
