### ISSUE TITLE
[please fix] astral tome given upon login

### ISSUE THREAD

**Issue by jpruitt2297** [kreezxil/World-of-Dragons#121]
Every time I login to the US WoD server I am given a new astral tome. I have even uninstalled and reinstalled, still doing it though. Been doing this since 14.41.170 version of the pack I believe.

As for recreating it, it would just happen upon login to the server.

 - Minecraft: 1.12.2
 - Forge: 14.23.5.28.24
 - Mod Pack: World of Dragons

**Comment by kreezxil** [comment]
https://github.com/HellFirePvP/AstralSorcery/issues/1052 is known and the indev is fixed, I've asked if he can push it to curseforge.

**Comment by kreezxil** [comment]
I've fixed it with the pack by disabling giving this book upon logon, I'll leave this open because technically it's not fixed until Astral Sorcery has been pushed out publicly.

**Comment by kreezxil** [comment]
Fixed in build 175 of World of Dragons.
