### ISSUE TITLE
[please add] player trading mod

### ISSUE THREAD

**Issue by ParsaMT** [kreezxil/World-of-Dragons#122]
# Mod Nominated for Adding*
Mod Name: Trade
Mod Link:  https://minecraft.curseforge.com/projects/trade

# Reason for Nomination

Reason: heard US is making a trade center so i decided to find this for them they are not that many players in eu and the players that are on all know eachother, seems like a handy mod

**Comment by kreezxil** [comment]
Not added. We got too much to handle now with custom npcs to configure.
