### ISSUE TITLE
[please fix] missing reward in quests

### ISSUE THREAD

**Issue by ParsaMT** [kreezxil/World-of-Dragons#124]
**Describe the bug**
 when players complete the quest Upgrade which requires a upgrade template in the no iron chest section they'll get a "missing item" which is a item from a mod that got removed

**To Reproduce**
1. Go to quest
2. Click on No iron chest WTF
3. Scroll down 
4. complete the Upgrade quest
5. see error
**Screenshots**

![Screenshot_1](https://user-images.githubusercontent.com/46574373/55586766-0336f400-573f-11e9-9d2b-0ad2344e26ae.png)

**Comment by kreezxil** [comment]
Fixed
