### ISSUE TITLE
[Config File] Botania

### ISSUE THREAD

**Issue by Drakyl** [kreezxil/World-of-Dragons#125]
# New Config

To hopefully help with server stability a little

Botania
https://pastebin.com/GQdZ0mDL

**Comment by kreezxil** [comment]
make sure you also give the name of the file I'm replacing. thanks.

**Comment by Drakyl** [comment]
I did. It's the Botania config. Also called botania. Listed both in the subject and Body of this request. Not sure what more your looking for.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kreezxil** [comment]
However, I do have it installed on the server.

**Comment by Drakyl** [comment]
Ok your confusing me. This was not a mod request, but a config change recommendation. If your saying you made the config change then good. Hopefully will help a bit with lag. If not then please review and add as you feel necessary

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kreezxil** [comment]
i'm saying at the top of the section where you start the config you put
filename: thisISaCONFIGwithTHISname.cfg, because some mods have more than
one config and some mods have config names that don't match the mod name.
I'll adjust the template to handle this ambiguous situation.
