### ISSUE TITLE
morbs centrifugal issue, zombie soldiers

### ISSUE THREAD

**Issue by ziba1** [kreezxil/World-of-Dragons#126]
Hi, having an issue with the centrifugal separator and reusable morbs with zombie soldiers inside, vanilla mobs in morbs work fine, but the morbs containing zombie soldiers will not go into the centrifugal separator

Modpack version - 14.41.173

I might be inclined to think this could affect all the mobs from the techguns ? mod, maybe even other mods too but I havent tried

**Comment by kreezxil** [comment]
which mod is the centrifugal separator you are referring to from? Does that
mod say the machine will work with any morbed mob?

**Comment by ziba1** [comment]
cant see anything that says it does or doesnt, but a quick test today in creative with random modded mobs in morbs and it doesnt accept any that ive tried

**Comment by kreezxil** [comment]
Are morbs Tech Reborn or Thermal Expansion, it would help if you could
identify the mod for me, could be something as simple as a config change.

**Comment by ziba1** [comment]
ahh, sorry, yes, would be useful haha, the morbs are from thermal expansion, and yes, seems no modded mob inside a morb will go into the centrifugal separator, so no dinosaurs either,, guessing none of the animania mobs etc.

So - centrifugal separator, and morbs are from thermal expansion, no modded mob that you catch in a morb will go into the centrifugal separator.

Cheers dude o/

**Comment by kreezxil** [comment]
Is the centrifugal separate you are using from Thermal Dynamics are Tech
Reborn, they both have this machine.

**Comment by ziba1** [comment]
the centrifugal separator is from thermal dynamics, the morbs are also from thermal dynamics

**Comment by kreezxil** [comment]
Mod author says that supporting code has not be designed for those mobs.
