### ISSUE TITLE
[please add] Landlust - Furniture

### ISSUE THREAD

**Issue by Drakyl** [kreezxil/World-of-Dragons#129]
# Mod Nominated for Adding*
Mod Name: Landlust - Furniture
Mod Link: https://www.curseforge.com/minecraft/mc-mods/landlust-furniture

# Reason for Nomination

Reason:
Adds more decorative/cosmetic blocks.

**Comment by kreezxil** [comment]
this had a bad bug the last time I removed it. Also see note about rustic.

**Comment by kreezxil** [comment]
added
