### ISSUE TITLE
[please fix] Every creature dying

### ISSUE THREAD

**Issue by MrGords** [kreezxil/World-of-Dragons#13]
**Describe the bug**

**To Reproduce**
Unsure

**Screenshots**

**Versions:**

 - Minecraft: 1.12.2
 - Forge:
 - Mod: WoD 13.8.130

**Comment by Draconian4466** [comment]
Uhh this isn't very helpful what do you mean?

**Comment by kreezxil** [comment]
@MrGords if you can't follow instructions, provide logs, screenshots, or any way to duplicate this, then I can't help. If you can figure out the problem feel free to open a new issue.
