### ISSUE TITLE
[please add] Rustic

### ISSUE THREAD

**Issue by Drakyl** [kreezxil/World-of-Dragons#130]
# Mod Nominated for Adding*
Mod Name: Rustic
Mod Link: https://www.curseforge.com/minecraft/mc-mods/rustic

# Reason for Nomination
Reason:
> Adds more decorative blocks

**Comment by kreezxil** [comment]
I removed a lot of decoration mods in the past because of pack size, because there was a time when the pack went from uber popular to uber not popular and the deciding factor was too many decoration mods. I'll have to see what the memory foot print is before I add this.

**Comment by kreezxil** [comment]
added
