### ISSUE TITLE
[please add] Rustic Thaumaturgy

### ISSUE THREAD

**Issue by Drakyl** [kreezxil/World-of-Dragons#131]
# Mod Nominated for Adding*
Mod Name: Rustic Thaumaturgy
Mod Link: https://www.curseforge.com/minecraft/mc-mods/rustic-thaumaturgy

# Reason for Nomination
>Reason:
If Rustic is added this allows Thaumcraft mats to be used to make more cosmetic items.

**Comment by kreezxil** [comment]
added
