### ISSUE TITLE
[please add] Tiny Mob Farm

### ISSUE THREAD

**Issue by Drakyl** [kreezxil/World-of-Dragons#133]
# Mod Nominated for Adding*
Mod Name: Tiny Mob Farm
Mod Link: https://www.curseforge.com/minecraft/mc-mods/tiny-mob-farm

# Reason for Nomination
Reason:
Eliminates the need for mob/animal farms and hopefully helps with server stability while giving players a way to automate mob drops. crafting difficulty may need to be adjusted upwards so as to not make it too easy.

**Comment by kreezxil** [comment]
hmmm, I won't need to add woot then.

**Comment by kreezxil** [comment]
added
