### ISSUE TITLE
[please fix] - arcance bore causing crash

### ISSUE THREAD

**Issue by Proxian** [kreezxil/World-of-Dragons#136]
I put down the arcane bore put a redstone torch next to it and it crashed my lan server

Current version of WOD( 173)

[crash-2019-04-07_02.53.48-server.txt](https://github.com/kreezxil/World-of-Dragons/files/3051712/crash-2019-04-07_02.53.48-server.txt)

**Comment by kreezxil** [comment]
Ok, i'm posting this on the Thaumcraft issue tracker.
https://pastebin.com/QgyHcBt5

**Comment by kreezxil** [comment]
https://github.com/Azanor/thaumcraft-beta/issues/1669
