### ISSUE TITLE
[Add] Abysal craft

### ISSUE THREAD

**Issue by Draconian4466** [kreezxil/World-of-Dragons#14]
This mod is pretty fun and i would like to see it added to the pack

**Comment by kreezxil** [comment]
we need better reasons than that

**Comment by Draconian4466** [comment]
Ok. It adds a whole new type of magic new biomes and new dimensions alot of new mobs new tools and ores

**Comment by kreezxil** [comment]
Tell me more. Do you remember how to do a book report?

**Comment by Draconian4466** [comment]
Kind of?

**Comment by Draconian4466** [comment]
This mod adds 42 new mobs so players never get tired of fighting 6 overworld biomes evil animals 4 new dimensions for players to explore and live if they want. 15 new ores. New type of tree in case they want a different type of wood for their house 17 new food items for the master chef players. 4 New machines to add a bit more tech. 4 new enchantments so players can get an extra boost against things new magic system with rituals and a new form of energy used in the magic system.

**Comment by kreezxil** [comment]
ok, added.
