### ISSUE TITLE
[please fix] world corruption

### ISSUE THREAD

**Issue by Enniota** [kreezxil/World-of-Dragons#142]
i dont know how but i was playing whit my friend on the latset version and  that apend 

https://pastebin.com/pG2xXYzc

i think somthing bad append in the world

**Comment by Enniota** [comment]
i have roll back my world actually

**Comment by Enniota** [comment]
too manyentities and the convoyerblelt of immersive was my problem i had a convoyer was not on the good direction and i think the stack of item made by the escavator was too uge  *so remouve too manyentities saved my day

**Comment by Enniota** [comment]
okay disable it let me whit another issue mekanica block on the world have disaper its okay for me i had 2 block of the mods but other can lose it aswell

**Comment by kreezxil** [comment]
mekanica won't work in claims, you have to unclaim the chunk the digitalminer is working in, if that is not the issue please describe in greater detail, provide pictures.

**Comment by Enniota** [comment]
I had the world with 2 blocks mekanica after removing the mods too many entities they disappeared

**Comment by Enniota** [comment]
that was on the old version that should be okay now

**Comment by kreezxil** [comment]
I do not entirely understand what you wrote in English. If you feel your
issue is resolved please close it.

The following French created with https://translate.google.com

Je ne comprends pas tout à fait ce que vous avez écrit en anglais. Si vous
pensez que votre problème est résolu, fermez-le.
