### ISSUE TITLE
[please fix] time out 

### ISSUE THREAD

**Issue by Enniota** [kreezxil/World-of-Dragons#147]
**storage like chest or refined storage lock the player make it won't able too interact with anything unless i disconect and reconect if the server didin t time out of that   **

first i was thinking just random apparition but that append with an interaction with a storage

**To Reproduce**
1. Go to a world 
2. make a system like that https://user-images.githubusercontent.com/31098775/56084566-0ca61780-5e35-11e9-8181-0cb8f97fe2ae.png and 
https://user-images.githubusercontent.com/31098775/56084569-1891d980-5e35-11e9-8ce0-6212ba6f2b29.png
 or just use a chest like a diamond i m sure that work with it 
3. we are always 2 at the same time on the server when the bug append 

click on one of the terminal and sometime you got the bug append 

**Versions:**
- Minecraft: 1.12.2
 - Forge:14.23.5.2825
 - Mod Pack <14.44.176>:
 - Mod Name: ...
 - Mod Version: ...

**Comment by kreezxil** [comment]
Are you saying that you can't use the system? That's a really odd bug,
we're using the refined storage systems on the USA and EU servers and are
not having an issue. Did you install something extra like optifine?
Optifine can cause the issue.

**Comment by Enniota** [comment]
no and that append only sometime like 1/5

**Comment by kreezxil** [comment]
I need consistent data to fix this. If it only happens once in a blue moon
then it's a one off and something else is happening.

**Comment by Enniota** [comment]
i mgona to try to record my game console when that append in game

**Comment by Enniota** [comment]
https://pastebin.com/gEkHbQsz i m not sure now what the problem look that what i got when i get the bug

**Comment by kreezxil** [comment]
that's a bad log, just send latest.log and debug.log

**Comment by Enniota** [comment]
[latest.log](https://github.com/kreezxil/World-of-Dragons/files/3077698/latest.log)
and i don t find debug.log

**Comment by kreezxil** [comment]
remove torchoptimizer from the pack and see if that solves your problem

**Comment by Enniota** [comment]
okay

**Comment by Enniota** [comment]
I said it to my friend too where gona to try

**Comment by kreezxil** [comment]
let me know if that works

**Comment by kreezxil** [comment]
so did that work or not?

**Comment by Enniota** [comment]
yes it look like it work

**Comment by Enniota** [comment]
thanks ^^

**Comment by kreezxil** [comment]
I'm going to patch what I saw with Torch Optimizer (my mod) to see if I can fix that error. If I can we'll test it and see if the situation stays resolved.

**Comment by Enniota** [comment]
okay is it on the new version ?

**Comment by kreezxil** [comment]
No, fixing this is a nightmare.

**Comment by Enniota** [comment]
x)

**Comment by kreezxil** [comment]
Ok, I did some ssp testing and I see that on a certain interval there is a 10 second pause, but it's with the entire pack not just a single mod. So that means there is a mod doing it.
