### ISSUE TITLE
[please add] NOTES

### ISSUE THREAD

**Issue by OmegaInferno49** [kreezxil/World-of-Dragons#15]
- ~~Rubberbanding issue, despite moving to "supposedly" better computer, midwest server~~
- Figure out memory draw?; Stress from certain mods on server (Jprofiler to find it, but is confusing and required specialized knowledge)
- Upgraded drops from I&F dragons / better loot from horde; gems such as diamonds and emeralds (instead of iron armor, bars, and iron weapons), lucky blocks, maybe other mod specific rare items? (Scale and bones more useful?)
- I&F heart made more useful rather then a WIP item; used as creation for player's maximum hearts such as a item that does that in another mod. (Gives two+ perm hearts instead of one?) Heart made into center of recipe surrounded by compressed obsidian gives end dragon egg? "Heart surrounded by 4 diamond blocks and 4 eyes of ender could give nether star"?
- Kingdom mod where killing a dragon gives high rep boost? Harvesting livestock depletes rep though? Complaint from new players who are minding their business and suddenly get attacked by guards without knowing why; killing dragon nearby? Entity glitch?
- Diamond Glass mod getting a recipe to recover diamonds due to statement concerning the wither on gethub
- More quests in Quest Book mod? More based around certain things
- Have the Mail mod on a server rather then a client for security vulnerabilities issue?
"it wouldn't be an extra server, just ssp only use of the mod won't be possible
that way server owners would have full control over where the database is
but the clients (players) wouldn't
granted it's not perfect cyber security however I think it would work"
- Pack excibits some kind of burdensome issue no matter what it's put on, needing rework. ( _cough_ Please keep Ender IO _cough_ )
- ~~Thinking of putting everythong on to the central server and run all 3 existing servers on it. Based on discussion, make new east coast and eu servers based on the new concepts and ie new maps; meaning the next issue of world of dragons will be major version 14!~~

I still need to incorporate all the data that @Emriella gathered for me

**Comment by kreezxil** [comment]
very good notes

**Comment by Hirschney** [comment]
Thanks for entering these.  I was just going to get to them today.

**Comment by kreezxil** [comment]
edited the main note for cleanliness and to show what's been done in regards to the notes, not the issues which is its own chronolog.

**Comment by kreezxil** [comment]
Ok  I think we got this in the bag and I've got a new direction to taken the main pack.
