### ISSUE TITLE
SPam crafting

### ISSUE THREAD

**Issue by ChaoticLaughter** [kreezxil/World-of-Dragons#151]
I have noticed that when trying to make SPam from VFP that the mechanism salt does not work as it requires the ingredient salt like the other Vanilla Food Pantry foods. I understand that this is something that is supposedly fixed to my knowledge, but I just wanted to bring this up

**Comment by kreezxil** [comment]
did you try with the last update? You should be able to obtain normal VFP
salt again.

**Comment by kreezxil** [comment]
ok, I realized now that I fixed something other than what you had specifically said, it's completely fixed now. there is a way to make spam. mekanism salt will convert to vfp salt.
