### ISSUE TITLE
My computer a potato help

### ISSUE THREAD

**Issue by doggoinpc** [kreezxil/World-of-Dragons#152]
The game directs me get myself a new PC and not a potato. My potato has a RX580 with 32 Gigs of RAM with a Ryzen 5 2600x but it does not allow me to run the mod, is there something wrong with my potato?

**Comment by kreezxil** [comment]
remove the memory tester mod from the pack and you'll be able to boot the
pack.

You do this by clicking anywhere on the profile icon that doesn't say play.
On the next screen click on the sprocket in the upper right
Then click on "profile options"
then uncheck the top box that says "locked"
hit ok
now scroll down the mod list till you find "memory tester"
hit the trashcan icon at the far right
now hit play at the top

I'll remove this mod from my pack in build 178, it's clear now that it is
failing horribly.

**Comment by kreezxil** [comment]
memory tester was removed in build 178.
