### ISSUE TITLE
[please add] Cyclic

### ISSUE THREAD

**Issue by AceWolf456** [kreezxil/World-of-Dragons#153]
https://minecraft.curseforge.com/projects/cyclic

It adds a bunch of things that could help people starting out, and a bunch of quality of life items.

**Comment by kreezxil** [comment]
Most of what you want from that mod can already be achieved. You just need to research the mods in the pack better. Also join the discord and ask the other players about what ever you're looking for.

I'll leave this open for now. But I'm not adding it until we resolve the lag issues with the pack.

**Comment by AceWolf456** [comment]
Honestly, I phrased it like that to seem less selfish, the only thing I want from Cyclic is to get the Elytra in the baubles slot. And I know it's selfish because I'm like the only person who uses the Elytra for it's intended purpose.

If you don't add it I accept that, but thanks for taking the time to even consider it.

**Comment by kreezxil** [comment]
added
