### ISSUE TITLE
Crash on pressing "U" on silverfish head

### ISSUE THREAD

**Issue by Xplodin** [kreezxil/World-of-Dragons#157]
The game crashed whilst rendering item
Error: java.lang.NullPointerException: Rendering item
https://pastebin.com/rswhFiPY

**Comment by kreezxil** [comment]
https://github.com/mezz/JustEnoughItems/issues/1563
https://github.com/SquidDev-CC/CC-Tweaked/issues/185

**Comment by kreezxil** [comment]
stale
