### ISSUE TITLE
[please add] Nemesis System

### ISSUE THREAD

**Issue by kreezxil** [kreezxil/World-of-Dragons#158]
You thought techguns was bad?
https://minecraft.curseforge.com/projects/nemesis-system

**Comment by Draconian4466** [comment]
This mod looks cool

**Comment by kreezxil** [comment]
added

**Comment by kreezxil** [comment]
removed because of a crash, if it gets fixed I'll add it back. Hopefully MET doesn't have this issue. probably a mod confliction or config issue. don't know.
