### ISSUE TITLE
[please fix] duplication rs glitch

### ISSUE THREAD

**Issue by TatlTaell** [kreezxil/World-of-Dragons#159]
**Describe the bug**
A duplication glitch involving the refined storage crafting grid and shift clicking items in at no cost, allowing the item count to go up but the items to not leave your inventory. 

**To Reproduce**
I stumbled across the glitch accidentally and have no idea how to recreate it. The glitch stopped when I closed the inventory screen. 

**Screenshots**
![E3CD4FC1-14BB-405B-81EE-425F1C3E2C80](https://user-images.githubusercontent.com/50048239/56849818-a525a880-68c7-11e9-94fa-9a5ded4152e6.jpeg)

**Versions:**

 - Minecraft:
 - Forge:
 - Mod Pack 14.48.180
 - Mod Name:
 - Mod Version:

**Additional context**
Once I figure out how to replicate the glitch I will update the steps here

**Comment by kreezxil** [comment]
Did this happen during a lag spike?

**Comment by TatlTaell** [comment]
I’m pretty sure there was no lag at the time

**Comment by kreezxil** [comment]
why you no make good title?

![Screenshot_1](https://user-images.githubusercontent.com/3880072/56897648-b354ff80-6a54-11e9-8d44-42346c64ba0e.png)

**Comment by kreezxil** [comment]
doesn't appear to be reproduceable
