### ISSUE TITLE
[please add] mod name crazy mobs

### ISSUE THREAD

**Issue by blazepelt** [kreezxil/World-of-Dragons#16]
# Mod Nominated for Adding*
Mod Name:
Mod Link:

# Reason for Nomination

Reason:

**Comment by kreezxil** [comment]
don't make me search for stuff, put the mod name and the mod's page url in the mod link and then fill out the part where it says reason, do it like a book report, actually explain it. start a new one. i'm close it.

**Comment by kingslayer296** [comment]
oof ye that is really hard to read. I even tried to look it up but there isnt anything under that name on curseforge

**Comment by kreezxil** [comment]
@blazepelt please find the curseforge link to this mod. I will not use an
out of network mod.
