### ISSUE TITLE
[please fix] Cant open world without crashing

### ISSUE THREAD

**Issue by aguy0801** [kreezxil/World-of-Dragons#160]
**Describe the bug**
I can launch minecraft with the pack just fine, but the game closes and crashes whenever I enter a world

**To Reproduce**
I dont even know, it just closes every time I open a world

**Screenshots**

**Versions:**

 - Minecraft:
 - Forge:14,23.4.2825
 - Mod Pack:14.48.180

**Additional context**
This is an error I got
Unable to configure ModInfo java.lang.IncompatibleClassChangeError at net.ilexiconn.llibrary.client.lang.LanguageHandler.addRemoteLocalizations(LanguageHandler.java:91) at net.ilexiconn.llibrary.LLibrary$CoreAPIHandler.addRemoteLocalizations(LLibrary.java:111) at net.ilexiconn.llibrary.server.core.patcher.LLibraryHooks.addRemoteLocalizations(LLibraryHooks.java:31) at net.minecraft.client.resources.Locale.func_135022_a(Locale.java:32) at modinfo.ModInfo.getLocale(ModInfo.java:271) at modinfo.ModInfo.<init>(ModInfo.java:53) at journeymap.client.JourneymapClient.startMapping(JourneymapClient.java:527) at journeymap.client.task.main.MappingMonitorTask.perform(MappingMonitorTask.java:72) at journeymap.client.task.main.MainTaskController.performTasks(MainTaskController.java:84) at journeymap.client.JourneymapClient.performMainThreadTasks(JourneymapClient.java:665) at journeymap.client.forge.event.StateTickHandler.onClientTick(StateTickHandler.java:72) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2525_StateTickHandler_onClientTick_ClientTickEvent.invoke(.dynamic) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344) at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1708) at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) at net.minecraft.client.main.Main.main(SourceFile:123) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by kreezxil** [comment]
first you should be on forge build 2836 not 2825

second that's not a valid crash report, please read about what I need at https://github.com/kreezxil/World-of-Dragons/wiki/Crash-Reports

third and I can't tell from your excerpt, but you've probably don't have enough ram allocated. The pack needs 6GB to run with no FPS/TPS issues as single player.

**Comment by aguy0801** [comment]
I cant put the log in a pastebin, it exceeds the limit
Also, how do I update forge then?

**Comment by kreezxil** [comment]
you have a bad install of the pack, if you were using Twitch Launcher it
would've updated to forge 2836 for you. If you're using any other launcher
you must tell that launcher to update to forge build 2836. This is easy to
do in MultiMC.

If pastebin says it's too big then put it on your cloud drive and share it
publically and put the link here.

**Comment by kreezxil** [comment]
However, pastebin will not say your crash-report is too large, that is a
small file and the most helpful one. I really need that one.

I suggest deleting the pack from your twitch launcher and getting it fresh.

**Comment by kreezxil** [comment]
no further input received, closing.
