### ISSUE TITLE
[please fix] crash in specific places

### ISSUE THREAD

**Issue by explorko** [kreezxil/World-of-Dragons#169]
**Describe the bug**
my game crash when i come to specific place in the world. mostly in cold biomes, but it happens to me even in forest ones. that place is on ungerenated chunk 

**Versions:**
 - Minecraft: 1.12
 - Forge: 1.12
 - Mod Pack 1.0
 - Mod Name: unknown
 - Mod Version: unknown

**Logs**

Crash Report:  https://pastebin.com/eRnGS56V
Debug Log: too big to be on pastebin
Latest Log: too big to be on pastebin

**Comment by kreezxil** [comment]
I'm sorry but old versions of my modpack can not be supported. If you don't
want to upgrade you will need to update the farseek and streams mod
yourself. You can do this by clicking on the profile icon (not the play
button), and in the upper right click on the sprocket and then choose
"profile options", uncheck the locked box and hit ok. The mod list will
change to show a bunch of arrows and trashcans on the far right. Now find
farseek and streams and click the arrow next to each.

That will resolve the issue.

I know for 2 reasons you're on an old version of the pack, first you said
pack version 1.0. Be aware that World of Dragons is on build 189, you are
188 builds behind.

Secondly the crash report says you are using a really old version of forge
with the line that says

```
Forge 14.23.4.2730
```

we are on Forge 14.23.5.2836.

However upgrading to the latest will cause lots and lots of changes, so I
recommend you just do what I said in the first paragraph.
