### ISSUE TITLE
[please fix] CodeChicken Lib startup cast

### ISSUE THREAD

**Issue by AceWolf456** [kreezxil/World-of-Dragons#170]
Title says it all
https://paste.dimdev.org/doqulatiba.mccrash

**Comment by kreezxil** [comment]
it sure does, but the top of the stack trace explains it better

**Invalid value type a, @Line:1, alse"client" {**

Did you edit the <pack>/config/codechickenlib.cfg file yourself, because
this is a human config level error. There should even the letters 'alse' in
front of the word client.

The file should look like this
```
"client" {
#With this enabled, CCL will catch all exceptions thrown whilst rendering
blocks.
#If an exception is caught, the block will not be rendered.
B:"catchBlockRenderExceptions"=true

#With this enabled, CCL will catch all exceptions thrown whilst rendering
items.
#By default CCL will only enhance the crash report, but with
'attemptRecoveryOnItemRenderException' enabled
# CCL will attempt to recover after the exception.
B:"catchItemRenderExceptions"=true

#With this enabled, CCL will attempt to recover item rendering after an
exception is thrown.
#It is recommended to only enable this when a mod has a known bug and a fix
has not been released yet.
#WARNING: This might cause issues with some mods, Some mods modify the GL
state rendering items,
#  CCL does not recover the GL state, as a result a GL leak /may/ occur.
However, CCL will remember
#  and pop the GL ModelView matrix stack depth, this might incur a bit of a
performance hit.
#  Some mods might also have custom BufferBuilders, CCL has no way of
recovering the state of those.
#  this /can/ result in 'Already Building' exceptions being thrown. CCL
will however recover the vanilla BufferBuilder.
B:"attemptRecoveryOnItemRenderException"=false

#With this enabled, CCL will message the player upon an exception from
rendering blocks or items.
#Messages are Rate-Limited to one per 5 seconds in the event that the
exception continues.
B:"messagePlayerOnRenderCrashCaught"=false
}
```
I've attached it too, just copy it over what you have. Wonder how this
happened as I didn't distribute it messed up.

**Comment by AceWolf456** [comment]
I was given specific instructions of what to change. I was told, by you, to see if the last boolean is on false or not, if not, make it false. That was all I changed. I've since reinstalled the pack and that fixed it. I'm just not gonna touch things I don't know about, even with instructions.

**Comment by kreezxil** [comment]
what did you use to edit the config file. You should always use text editor
like notepad++ or notepad itself, not a wordpressor as those typically
don't know how to edit plain text without causing problems.

**Comment by AceWolf456** [comment]
I used a program called NotepadX.
