### ISSUE TITLE
[please fix] Crash - Astral sorcery attunment

### ISSUE THREAD

**Issue by vAlpha3** [kreezxil/World-of-Dragons#172]
**Describe the bug**
Regular crash trying to attune myself in astral sorcery, error says due to either TechGuns or Astral.

**To Reproduce**
1. Get up to research Attunement level in Astral mod.
2. Make attunement altar, and make the star alignment part to attune self.
3. Crash.

**Screenshots**
N/A

**Versions:**

 - Minecraft: 1.12.2
 - Forge:8.0.99.99
 - Mod Pack World of Dragons<14.57.189>:
 - Mod Name: Astral Sorcery/ Techguns
 - Mod Version:1.10.17

**Logs**
https://paste.dimdev.org/jakikahica.mccrash

Crash Report: 
Debug Log:
Latest Log:

**Additional context**

**Comment by Draconian4466** [comment]
Valpha3 please add your crash report to this https://github.com/pWn3d1337/Techguns2/issues/126

**Comment by kreezxil** [comment]
astral sorcery removed in major version 15+ because of this and other reasons
