### ISSUE TITLE
[please fix] Town Hall crashes private server

### ISSUE THREAD

**Issue by ChaosInClarity** [kreezxil/World-of-Dragons#173]
**Describe the bug**
Put a town hall down, renamed it, picked it back up with a vanilla Iron Axe, tried placing it in new location, get a prompt saying something like "You cant have more than one Town Hall, click DELETE to delete old town hall", click DELETE prompt thats in the chatbox, entire server crashes. 

Can't get visit or get near the chunk that it happened in and player can't load in because it loads the chunk, immediately crashing the server.

**To Reproduce**
1. Place Town Hall that you get from a supply chest.
2. Renamed Town Hall (dont know if this is even affects it).
3. Broke Town Hall block with an Iron Axe a few seconds after placed. 
4. Try to place it down again.
5. Get prompted with "Delete old Town Hall by clicking DELETE"
6. Left click DELETE in chatbox with mouse.
7. Server crash.
8. Getting near location of town hall block or player loading into its vicinity crashes the server again.

**Screenshots**
None since you can't get near chunk.

**Versions:**
Check Error Log attachment

**Logs**
Check Attachment: 
[crash-2019-05-13_23.19.23-server.txt](https://github.com/kreezxil/World-of-Dragons/files/3180830/crash-2019-05-13_23.19.23-server.txt)

**Additional context**
Cannot replicate in single player mode because it seems like there isnt a limit of town halls/colonies you can place. 

Private server for me and a handful of friend being ran off of a secondary PC. Player did the steps above and crashed the server. I edited his .dat file to move him to a safe location. He actually has the Town Hall block in his inventory. Don't know if that matters. I took town hall from him and followed his exact steps and recreated the crash. Now there are two locations in my server that are cannot be visited by anyone or it crashes immediately before even visibly loading in.

**Comment by ChaosInClarity** [comment]
Dropping Crash Report in comment if people don't want to download file: 

---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 2019-05-13 23:19:23 CDT
Description: Exception in server tick loop

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at com.minecolonies.api.colony.IColonyTagCapability$Impl.removeColony(IColonyTagCapability.java:120)
    at com.minecolonies.api.util.ChunkLoadStorage.applyToCap(ChunkLoadStorage.java:222)
    at com.minecolonies.coremod.util.ChunkDataHelper.addStorageToChunk(ChunkDataHelper.java:119)
    at com.minecolonies.coremod.util.ChunkDataHelper.loadChunk(ChunkDataHelper.java:78)
    at com.minecolonies.coremod.event.EventHandler.onChunkLoad(EventHandler.java:159)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_627_EventHandler_onChunkLoad_Load.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraft.world.chunk.Chunk.onLoad(Chunk.java:862)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:109)
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:728)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_171, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 5970586656 bytes (5693 MB) / 8107065344 bytes (7731 MB) up to 8107065344 bytes (7731 MB)
  JVM Flags: 2 total; -Xms4G -Xmx8G
  IntCache: cache: 2, tcache: 0, allocated: 13, tallocated: 95
  FML: MCP 9.42 Powered by Forge 14.23.5.2836 209 mods loaded, 209 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                              | Version                  | Source                                          | Signature                                |
       |:------ |:------------------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                       | 1.12.2                   | minecraft.jar                                   | None                                     |
       | LCHIJA | mcp                             | 9.42                     | minecraft.jar                                   | None                                     |
       | LCHIJA | FML                             | 8.0.99.99                | modpack_server.jar                              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                           | 14.23.5.2836             | modpack_server.jar                              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | foamfixcore                     | 7.7.4                    | minecraft.jar                                   | None                                     |
       | LCHIJA | obfuscate                       | 0.2.6                    | minecraft.jar                                   | None                                     |
       | LCHIJA | opencomputers|core              | 1.7.4.153                | minecraft.jar                                   | None                                     |
       | LCHIJA | randompatches                   | 1.12.2-1.15.1.0          | randompatches.jar                               | None                                     |
       | LCHIJA | gottagofast                     | 1.1                      | gotta-go-fast.jar                               | None                                     |
       | LCHIJA | techguns_core                   | 1.12.2-1.0               | minecraft.jar                                   | None                                     |
       | LCHIJA | charset                         | 0.5.5.7                  | charset-lib.jar                                 | None                                     |
       | LCHIJA | jei                             | 4.15.0.278               | jei.jar                                         | None                                     |
       | LCHIJA | abyssalcraft                    | 1.9.7                    | abyssalcraft.jar                                | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LCHIJA | chisel                          | MC1.12.2-0.2.1.35        | chisel.jar                                      | None                                     |
       | LCHIJA | mantle                          | 1.12-1.3.3.49            | mantle.jar                                      | None                                     |
       | LCHIJA | baubles                         | 1.5.2                    | baubles.jar                                     | None                                     |
       | LCHIJA | thaumcraft                      | 6.1.BETA26               | thaumcraft.jar                                  | None                                     |
       | LCHIJA | botania                         | r1.10-361                | botania.jar                                     | None                                     |
       | LCHIJA | forgelin                        | 1.8.2                    | shadowfacts-forgelin.jar                        | None                                     |
       | LCHIJA | librarianlib                    | 4.15                     | librarianlib.jar                                | None                                     |
       | LCHIJA | autoreglib                      | 1.3-28                   | autoreglib.jar                                  | None                                     |
       | LCHIJA | psi                             | r1.1-75                  | psi.jar                                         | None                                     |
       | LCHIJA | rpsideas                        | 2.3.0                    | random-psideas.jar                              | None                                     |
       | LCHIJA | tweakersconstruct               | 1.12.2-1.4.0             | tweakers-construct.jar                          | None                                     |
       | LCHIJA | tconstruct                      | 1.12.2-2.12.0.135        | tinkers-construct.jar                           | None                                     |
       | LCHIJA | acintegration                   | 1.8.1                    | abyssalcraft-integration.jar                    | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LCHIJA | redstoneflux                    | 2.1.0                    | redstone-flux.jar                               | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | cofhcore                        | 4.6.2                    | cofhcore.jar                                    | None                                     |
       | LCHIJA | craftstudioapi                  | 1.0.0                    | craftstudio-api.jar                             | None                                     |
       | LCHIJA | animania                        | 1.6.2                    | animania.jar                                    | None                                     |
       | LCHIJA | appleskin                       | 1.0.9                    | appleskin.jar                                   | None                                     |
       | LCHIJA | crafttweaker                    | 4.1.17                   | crafttweaker.jar                                | None                                     |
       | LCHIJA | conarm                          | 1.2.3.4                  | constructs-armory.jar                           | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHIJA | armoryexpansion                 | 1.1.10c                  | armory-expansion.jar                            | None                                     |
       | LCHIJA | armoryexpansion-custommaterials | 1.1.10c                  | armory-expansion.jar                            | None                                     |
       | LCHIJA | llibrary                        | 1.7.19                   | llibrary.jar                                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | iceandfire                      | 1.6.1                    | ice-and-fire-dragons.jar                        | None                                     |
       | LCHIJA | armoryexpansion-iceandfire      | 1.1.10c                  | armory-expansion.jar                            | None                                     |
       | LCHIJA | astralsorcery                   | 1.10.17                  | astral-sorcery.jar                              | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
       | LCHIJA | backpacks16840                  | 3.5.5                    | backpacks.jar                                   | None                                     |
       | LCHIJA | badwithernocookiereloaded       | 1.12.2-3.3.16            | bad-wither-no-cookie-reloaded.jar               | None                                     |
       | LCHIJA | bedpatch                        | 2.2                      | bed-patch.jar                                   | 6bf7527e690fb5e8719b9832bce5000a3e87dfe6 |
       | LCHIJA | betterbuilderswands             | 0.13.2                   | better-builders-wands.jar                       | None                                     |
       | LCHIJA | bibliocraft                     | 2.4.5                    | bibliocraft.jar                                 | None                                     |
       | LCHIJA | bigbeautifulbuttons             | 1.12.2-1.1.3             | big-beautiful-buttons.jar                       | None                                     |
       | LCHIJA | reborncore                      | 3.13.12.447              | reborncore.jar                                  | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | LCHIJA | techreborn                      | 2.22.1.979               | techreborn.jar                                  | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | LCHIJA | forestry                        | 5.8.2.387                | forestry.jar                                    | None                                     |
       | LCHIJA | binniecore                      | 2.5.1.188                | binnies-mods.jar                                | None                                     |
       | LCHIJA | binniedesign                    | 2.5.1.188                | binnies-mods.jar                                | None                                     |
       | LCHIJA | genetics                        | 2.5.1.188                | binnies-mods.jar                                | None                                     |
       | LCHIJA | botany                          | 2.5.1.188                | binnies-mods.jar                                | None                                     |
       | LCHIJA | extrabees                       | 2.5.1.188                | binnies-mods.jar                                | None                                     |
       | LCHIJA | extratrees                      | 2.5.1.188                | binnies-mods.jar                                | None                                     |
       | LCHIJA | bookshelf                       | 2.3.577                  | bookshelf.jar                                   | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | bookworm                        | 1.12.2-2.2.0             | bookworm.jar                                    | None                                     |
       | LCHIJA | caliper                         | 1.1.43                   | caliper.jar                                     | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | cctweaked                       | 1.82.3                   | cc-tweaked.jar                                  | None                                     |
       | LCHIJA | computercraft                   | 1.82.3                   | cc-tweaked.jar                                  | None                                     |
       | LCHIJA | chameleon                       | 1.12-4.1.3               | chameleon.jar                                   | None                                     |
       | LCHIJA | chiselsandbits                  | 14.32                    | chisels-bits.jar                                | None                                     |
       | LCHIJA | chunkpregenerator               | 2.1                      | chunkpregenerator.jar                           | None                                     |
       | LCHIJA | codechickenlib                  | 3.2.2.353                | codechicken-lib-1-8.jar                         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | cofhworld                       | 1.3.0                    | cofh-world.jar                                  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | cyclopscore                     | 1.2.0                    | cyclops-core.jar                                | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCHIJA | colossalchests                  | 1.7.1                    | colossal-chests.jar                             | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCHIJA | morpheus                        | 1.12.2-3.5.106           | morpheus.jar                                    | None                                     |
       | LCHIJA | comforts                        | 1.4.1.2                  | comforts.jar                                    | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHIJA | storagedrawers                  | 1.12-5.3.5               | storage-drawers.jar                             | None                                     |
       | LCHIJA | compactdrawers                  | 1.12.2-1.0.5.121         | compactdrawers.jar                              | None                                     |
       | LCHIJA | tombstone                       | 3.3.6                    | corail-tombstone.jar                            | None                                     |
       | LCHIJA | cosmeticarmorreworked           | 1.12.2-v4a               | cosmetic-armor-reworked.jar                     | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCHIJA | cosmeticbeds                    | 1.12.2-1.0.2.2           | cosmetic-beds.jar                               | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHIJA | craftingtweaks                  | 8.1.9                    | crafting-tweaks.jar                             | None                                     |
       | LCHIJA | crafttweakerjei                 | 2.0.3                    | crafttweaker.jar                                | None                                     |
       | LCHIJA | cucumber                        | 1.1.3                    | cucumber.jar                                    | None                                     |
       | LCHIJA | customnpcs                      | 1.12                     | custom-npcs.jar                                 | None                                     |
       | LCHIJA | diamondglass                    | 1.12.2-3.3.18            | diamond-glass.jar                               | None                                     |
       | LCHIJA | diethopper                      | 1.1                      | diet-hoppers.jar                                | None                                     |
       | LCHIJA | dimensionalcake                 | 1.12.2-1.0               | dimensional-cake-rebuilt.jar                    | None                                     |
       | LCHIJA | dirtdeco                        | 1.12.2-1.6.7             | dirt-deco.jar                                   | None                                     |
       | LCHIJA | discordintegration              | 3.0.4                    | discordintegration-mc1.12.2-3.0.5.jar           | None                                     |
       | LCHIJA | dynamictrees                    | 1.12.2-0.9.5             | dynamictrees.jar                                | None                                     |
       | LCHIJA | rustic                          | 1.1.0                    | rustic.jar                                      | None                                     |
       | LCHIJA | dynamictreestc                  | 1.12.2-1.4.1e            | dttc.jar                                        | None                                     |
       | LCHIJA | dummycore                       | 2.4.112.5.               | dummycore-unofficial.jar                        | None                                     |
       | LCHIJA | eplus                           | 5.0.177                  | enchanting-plus.jar                             | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | enderstorage                    | 2.4.5.135                | ender-storage-1-8.jar                           | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | ftblib                          | 5.4.1.99                 | ftblib.jar                                      | None                                     |
       | LCHIJA | shetiphiancore                  | 3.5.9                    | shetiphiancore.jar                              | None                                     |
       | LCHIJA | endertanks                      | 1.6.8                    | endertanks.jar                                  | None                                     |
       | LCHIJA | equaldragons                    | 1.1                      | equaldragons.jar                                | None                                     |
       | LCHIJA | exnihilocreatio                 | 1.12.2-0.4.2             | ex-nihilo-creatio.jar                           | None                                     |
       | LCHIJA | excompressum                    | 3.0.27                   | ex-compressum.jar                               | None                                     |
       | LCHIJA | exactspawn                      | 1.12-1.2.3.17            | exact-spawn.jar                                 | None                                     |
       | LCHIJA | shadowmc                        | 3.8.0                    | shadowmc.jar                                    | None                                     |
       | LCHIJA | extrarails                      | 1.3.0                    | extra-rails.jar                                 | None                                     |
       | LCHIJA | fairylights                     | 2.1.6                    | fairy-lights.jar                                | None                                     |
       | LCHIJA | farseek                         | 2.3.2                    | farseek.jar                                     | None                                     |
       | LCHIJA | fastleafdecay                   | v14                      | fast-leaf-decay.jar                             | None                                     |
       | LCHIJA | fasterladderclimbing            | 0.1-146                  | faster-ladder-climbing.jar                      | None                                     |
       | LCHIJA | fastbench                       | 1.7.0                    | fastworkbench.jar                               | None                                     |
       | LCHIJA | fencejumper                     | 1.0.5                    | fence-jumper.jar                                | None                                     |
       | LCHIJA | flopper                         | 1.0.3                    | flopper.jar                                     | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCHIJA | foamfix                         | 0.10.5-1.12.2            | foamfix-for-minecraft.jar                       | None                                     |
       | LCHIJA | fossil                          | 8.0.0                    | fossils.jar                                     | None                                     |
       | LCHIJA | ftbutilities                    | 5.4.0.96                 | ftb-utilities.jar                               | None                                     |
       | LCHIJA | itemfilters                     | 1.0.3.12                 | item-filters.jar                                | None                                     |
       | LCHIJA | ftbquests                       | 1.5.2.151                | ftb-quests.jar                                  | None                                     |
       | LCHIJA | furenikusroads                  | 1.0.3                    | furenikusroads.jar                              | None                                     |
       | LCHIJA | furnaceoverhaul                 | 2.2.0                    | furnace-overhaul.jar                            | None                                     |
       | LCHIJA | giacomosfoundry                 | 1.3.13                   | giacomos-foundry.jar                            | None                                     |
       | LCHIJA | grandeconomy                    | 1.0.1                    | grand-economy.jar                               | None                                     |
       | LCHIJA | grandexchange                   | 1.1.0                    | grand-exchange.jar                              | None                                     |
       | LCHIJA | placebo                         | 1.6.0                    | placebo.jar                                     | None                                     |
       | LCHIJA | refinedstorage                  | 1.6.14                   | refined-storage.jar                             | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
       | LCHIJA | growablecells                   | 3.1.0                    | growable-storage-cells.jar                      | None                                     |
       | LCHIJA | guideapi                        | 1.12-2.1.8-63            | guide-api.jar                                   | None                                     |
       | LCHIJA | harvestables                    | 1.2                      | harvestables.jar                                | None                                     |
       | LCHIJA | helpfixer                       | 1.12.1-1.5.18            | helpfixer.jar                                   | None                                     |
       | LCHIJA | hopperducts                     | 1.5                      | hopper-ducts.jar                                | None                                     |
       | LCHIJA | thermalfoundation               | 2.6.2                    | thermal-foundation.jar                          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | immersiveengineering            | 0.12-89                  | immersive-engineering.jar                       | 4cb49fcde3b43048c9889e0a3d083225da926334 |
       | LCHIJA | immersivecables                 | 1.3.2                    | immersive-cables.jar                            | None                                     |
       | LCHIJA | immersivepetroleum              | 1.1.9                    | immersive-petroleum.jar                         | None                                     |
       | LCHIJA | trackapi                        | 1.1                      | track-api.jar                                   | None                                     |
       | LCHIJA | immersiverailroading            | 1.6.1                    | immersive-railroading.jar                       | None                                     |
       | LCHIJA | immersivetech                   | 1.3.10                   | immersive-tech.jar                              | None                                     |
       | LCHIJA | igwmod                          | 1.4.4-15                 | in-game-wiki-mod.jar                            | None                                     |
       | LCHIJA | instantunify                    | 1.1.2                    | instantunify.jar                                | None                                     |
       | LCHIJA | inventorytweaks                 | 1.64+dev.146.2180b27     | inventory-tweaks.jar                            | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | ironbackpacks                   | 1.12.2-3.0.8-12          | iron-backpacks.jar                              | None                                     |
       | LCHIJA | ironjetpacks                    | 1.1.0                    | iron-jetpacks.jar                               | None                                     |
       | LCHIJA | jeid                            | 1.0.2-26                 | jeid.jar                                        | None                                     |
       | LCHIJA | journeymap                      | 1.12.2-5.5.5b5           | journeymap.jar                                  | None                                     |
       | LCHIJA | jepb                            | 1.2.1                    | just-enough-pattern-banners.jar                 | None                                     |
       | LCHIJA | jmh                             | 2.0                      | just-mob-heads.jar                              | None                                     |
       | LCHIJA | laggoggles                      | FORGE-1.12.2-4.3-HOTFIX  | laggoggles.jar                                  | None                                     |
       | LCHIJA | landlust                        | 1.12.2-0.3.6             | landlust-furniture.jar                          | None                                     |
       | LCHIJA | levelup2                        | ${version}               | level-up.jar                                    | None                                     |
       | LCHIJA | leverbuttonlights               | 1.12.2-1.5               | lever-button-lights.jar                         | None                                     |
       | LCHIJA | lunatriuscore                   | 1.2.0.42                 | lunatriuscore.jar                               | None                                     |
       | LCHIJA | magipsi                         | 1.3                      | magical-psi.jar                                 | None                                     |
       | LCHIJA | mekanism                        | 1.12.2-1.2.0             | mekanica.jar                                    | None                                     |
       | LCHIJA | metalchests                     | v4.0.1.g01955d6          | metalchests.jar                                 | None                                     |
       | LCHIJA | mtrm                            | 1.2.2.30                 | minetweaker-recipemaker.jar                     | None                                     |
       | LCHIJA | moartinkers                     | 0.6.0                    | moar-tinkers.jar                                | None                                     |
       | LCHIJA | morebeautifulbuttons            | 1.12.2-1.7.3.20          | more-beautiful-buttons.jar                      | None                                     |
       | LCHIJA | morebeautifulplates             | 1.12.2-1.0.3             | more-beautiful-plates.jar                       | None                                     |
       | LCHIJA | cfm                             | 6.2.0                    | mrcrayfish-furniture-mod.jar                    | None                                     |
       | LCHIJA | vehicle                         | 0.39.0                   | mrcrayfishs-vehicle-mod.jar                     | None                                     |
       | LCHIJA | blockout                        | @VERSION@                | blockout.jar                                    | None                                     |
       | LCHIJA | multipiston                     | @VERSION@                | multi-piston.jar                                | None                                     |
       | LCHIJA | naturescompass                  | 1.5.1                    | natures-compass.jar                             | None                                     |
       | LCHIJA | notenoughscaffold               | 1.8                      | notenoughscaffold.jar                           | None                                     |
       | LCHIJA | elevatorid                      | 1.3.10                   | openblocks-elevator.jar                         | None                                     |
       | LCHIJA | opencomputers                   | 1.7.4.153                | opencomputers.jar                               | None                                     |
       | LCHIJA | tinkersoc                       | 0.6                      | opencomputers-drivers-for-tinkers-construct.jar | None                                     |
       | LCHIJA | opendisks                       | 0.1.0.3                  | opendisks.jar                                   | None                                     |
       | LCHIJA | openfm                          | 0.1.0.19                 | openfm.jar                                      | None                                     |
       | LCHIJA | openprinter                     | 0.1.0.2                  | openprinter.jar                                 | None                                     |
       | LCHIJA | opensecurity                    | 1.0-23                   | opensecurity.jar                                | None                                     |
       | LCHIJA | oreexcavation                   | 1.4.140                  | ore-excavation.jar                              | None                                     |
       | LCHIJA | rangedpumps                     | 0.5                      | ranged-pumps.jar                                | None                                     |
       | LCHIJA | rebornstorage                   | 1.0.0                    | rebornstorage.jar                               | None                                     |
       | LCHIJA | redstonepaste                   | 1.7.5                    | redstone-paste.jar                              | None                                     |
       | LCHIJA | refinedstorageaddons            | 0.4.4                    | refined-storage-addons.jar                      | None                                     |
       | LCHIJA | roleplaycraft                   | 1.12.2-1.3.4             | roleplaycraft-recoded.jar                       | None                                     |
       | LCHIJA | rusticthaumaturgy               | 4.4a                     | rustic-thaumaturgy.jar                          | None                                     |
       | LCHIJA | securitycraft                   | v1.8.12                  | security-craft.jar                              | None                                     |
       | LCHIJA | flammpfeil.slashblade           | mc1.12-r22               | slashblade.jar                                  | None                                     |
       | LCHIJA | soulbottle                      | 1.1                      | soulbottle.jar                                  | None                                     |
       | LCHIJA | stackie                         | 1.6.0.48                 | stackie.jar                                     | None                                     |
       | LCHIJA | stevescarts                     | 2.4.30.134               | steves-carts-reborn.jar                         | None                                     |
       | LCHIJA | recipehandler                   | 0.13                     | stimmedcow-nomorerecipeconflict.jar             | None                                     |
       | LCHIJA | storagetech                     | 6.0                      | storage-tech.jar                                | None                                     |
       | LCHIJA | streams                         | 0.4.7                    | streams.jar                                     | None                                     |
       | LCHIJA | techguns                        | 2.0.1.2                  | techguns.jar                                    | None                                     |
       | LCHIJA | terracart                       | 1.12.2-1.2.3             | terracart-reloaded.jar                          | None                                     |
       | LCHIJA | thaumcomp                       | 0.4.4                    | thaumic-computers.jar                           | None                                     |
       | LCHIJA | thaumicgrid                     | 1.0.12                   | thaumic-grid.jar                                | None                                     |
       | LCHIJA | thermalexpansion                | 5.5.3                    | thermalexpansion.jar                            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermalcultivation              | 0.3.2                    | thermal-cultivation.jar                         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermaldynamics                 | 2.5.4                    | thermal-dynamics.jar                            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermalinnovation               | 0.3.2                    | thermal-innovation.jar                          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermalsolars                   | 1.12.2 V1.9.4            | thermal-solars.jar                              | None                                     |
       | LCHIJA | tinker_io                       | rw2.7.1                  | tinker-i-o.jar                                  | None                                     |
       | LCHIJA | tinkersaddons                   | 1.0.7                    | tinkers-addons.jar                              | None                                     |
       | LCHIJA | tinkerscompendium               | 1.4.2.26.2               | tinkers-compendium.jar                          | None                                     |
       | LCHIJA | tcomplement                     | ${version}               | tinkers-complement.jar                          | None                                     |
       | LCHIJA | tinkersjei                      | 1.2                      | tinkers-jei.jar                                 | None                                     |
       | LCHIJA | tinkertoolleveling              | 1.12.2-1.1.0.DEV.b23e769 | tinkers-tool-leveling.jar                       | None                                     |
       | LCHIJA | tinymobfarm                     | 1.0.5                    | tiny-mob-farm.jar                               | None                                     |
       | LCHIJA | toroquest                       | 1.12.2-5.3               | toroquest.jar                                   | None                                     |
       | LCHIJA | tramplestopper                  | 1.2.0.4                  | trample-stopper.jar                             | None                                     |
       | LCHIJA | underphangables                 | 1.0.0                    | underp-hangables.jar                            | None                                     |
       | LCHIJA | vanillafix                      | 1.0.10-SNAPSHOT          | vanillafix.jar                                  | None                                     |
       | LCHIJA | vanillafoodpantry               | 4.3.1                    | vanillafoodpantry-mod.jar                       | None                                     |
       | LCHIJA | wanionlib                       | 1.12.2-2.2               | wanionlib.jar                                   | None                                     |
       | LCHIJA | waystones                       | 4.0.67                   | waystones.jar                                   | None                                     |
       | LCHIJA | witherskelefix                  | 2.6.3                    | wither-skeleton-tweaks.jar                      | None                                     |
       | LCHIJA | worldedit                       | 6.1.10-SNAPSHOT          | worldedit.jar                                   | None                                     |
       | LCHIJA | gbook                           | 2.8.3                    | guidebook.jar                                   | None                                     |
       | LCHIJA | structurize                     | 1.12.2-0.10.93-ALPHA     | structurize-1.12.2-0.10.93-ALPHA.jar            | None                                     |
       | LCHIJA | minecolonies                    | 1.12.2-0.10.280-ALPHA    | minecolonies.jar                                | None                                     |
       | LCHIJA | techreborn_compat               | 1.0.0                    | TechReborn-ModCompatibility-1.12.2-1.1.0.38.jar | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | LCHIJA | armoryexpansion-conarm          | 1.1.10c                  | armory-expansion.jar                            | None                                     |
       | LCHIJA | librarianliblate                | 4.15                     | librarianlib.jar                                | None                                     |
       | LCHIJA | unidict                         | 1.12.2-2.9.2             | unidict.jar                                     | None                                     |
  Loaded coremods (and transformers): Inventory Tweaks Coremod (inventory-tweaks.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-for-minecraft.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      FarseekCoreMod (farseek.jar)
                                        farseek.core.FarseekClassTransformer
                                      OFMDepLoader (openfm.jar)
                                        
                                      TransformerLoader (opencomputers.jar)
                                        li.cil.oc.common.asm.ClassTransformer
                                      CTMCorePlugin (ctm.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      ObfuscatePlugin (obfuscate.jar)
                                        com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
                                      GottaGoFastLoader (gotta-go-fast.jar)
                                        com.thiakil.gottagofast.coremod.GottaGoFastASMTransformer
                                      LibrarianLib Plugin (librarianlib.jar)
                                        com.teamwizardry.librarianlib.asm.LibLibTransformer
                                      AstralCore (astral-sorcery.jar)
                                        
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      BCModPlugin (backpacks.jar)
                                        brad16840.core.ClassTransformer
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      ForgelinPlugin (shadowfacts-forgelin.jar)
                                        
                                      ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
                                        shetiphian.asm.ClassTransformer
                                      BedPatch (bed-patch.jar)
                                        com.mordenkainen.bedpatch.BedPatchASM
                                      OpenDisksUnpack (opendisks.jar)
                                        
                                      Techguns Core (techguns.jar)
                                        techguns.core.TechgunsASMTransformer
                                      SoundUnpack (opensecurity.jar)
                                        
                                      RandomPatches (randompatches.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      DCLoadingPlugin (dummycore-unofficial.jar)
                                        DummyCore.ASM.DCASMManager
                                      VanillaFixLoadingPlugin (vanillafix.jar)
                                        
                                      JEIDLoadingPlugin (jeid.jar)
                                        org.dimdev.jeid.JEIDTransformer
                                      NWRTweak (redstone-paste.jar)
                                        net.fybertech.nwr.NWRTransformer
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
                                   - chiselsandbitsIntegration (Enabled/Not Forced)
                                   - craftingtweaksIntegration (Enabled/Not Forced)
  Pulsar/tcomplement loaded Pulses: - ModuleCommons (Enabled/Forced)
                                    - ModuleMelter (Enabled/Not Forced)
                                    - ModuleArmor (Enabled/Not Forced)
                                    - ChiselPlugin (Enabled/Not Forced)
                                    - ExNihiloPlugin (Enabled/Not Forced)
  [Psi] Active spell: None
  RebornCore: Plugin Engine: 0
              RebornCore Version: 3.13.12.447
              Runtime Debofucsation 1
  [DummyCore]: 'Special case ASM modification mods: ''Note, that these mods might not be involved in the crash in ANY WAY!''DummyCore just prints some known mods for a lot of ASM modifications''dummycore''CodeChickenLib'
  Suspected Mods: MineColonies (minecolonies)
  Profiler Position: N/A (disabled)
  Player Count: 2 / 20; [EntityPlayerMP['KoroKaos'/803, l='', x=-1157.01, y=72.00, z=-872.02], EntityPlayerMP['KoroTenshi'/3801, l='', x=-456.52, y=69.18, z=962.81]]
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server (map_server.txt)

**Comment by kreezxil** [comment]
please update to the latest version of the pack which contains the latest minecolonies. you have build 280 of minecolonies, the pack is now using build 283 which promised to have fixed that issue. If it crashes again open a new report.

**Comment by ChaosInClarity** [comment]
Appreciated
