### ISSUE TITLE
[please fix] Mekanica and RandomPSIdeas crash

### ISSUE THREAD

**Issue by AceWolf456** [kreezxil/World-of-Dragons#174]
Apparently those two mods are causing an issue. I don't know what's up fully, my game just yelled at me for it.
https://paste.dimdev.org/ulefojapoc.mccrash

**Comment by kreezxil** [comment]
sent to the mod author/owner. here's hoping a fix is forthwith.

**Comment by kreezxil** [comment]
Btw, tell me what you were doing when it happened, the steps to reproduce would be helpful.

**Comment by AceWolf456** [comment]
I was standing on a cactus. I don't use either of those mods so I honestly have no idea what happened.

**Comment by kreezxil** [comment]
https://github.com/ForestryMC/ForestryMC/issues/2411

The forestry author pointed out that you are using optifine. I don't support optifine. Please remove it and try again.

**Comment by AceWolf456** [comment]
I didn't add optifine, the fuck? 
Just double checked before actually posting this comment, I don't have Optifine in the pack. Also my problem wasn't from forestry, and the crash log you shared with them wasn't my crash log.

**Comment by kreezxil** [comment]
I pasted the wrong cross link here, the optifine reference wasn't meant for you. I'm one person you know processing all these bug reports and all these packs and mods etc plus managing a giant discord with multiple game servers. so crossed-wires can and will happen. 

I've sent a report to the mekanica team which doesn't appear to accepting bug reports anymore. I'll be switching to Mekanism proper next release. It will occupy the same namespace and therefore you won't lose anything and I will then have place to submit bug reports.

**Comment by kreezxil** [comment]
interesting, stale, but should be fixed because we're removing random psideas because it causes lots of issue in console, perhaps causing lag.
