### ISSUE TITLE
[please fix] Failed to start from an Unknown mod

### ISSUE THREAD

**Issue by gigabit27** [kreezxil/World-of-Dragons#177]
**Describe the bug**
I tried to install this modpack and it just dosen't open, it says that a potantial "Unknown" mod might be the problem.
**Screenshots**
![Capture](https://user-images.githubusercontent.com/50723921/57896698-40e36e00-780f-11e9-9426-afa5bf21c4d4.PNG)

**Versions:**
 - Minecraft:1.12.2

**Logs**
https://paste.dimdev.org/fexekahozi.mccrash

**Comment by kreezxil** [comment]
You need to learn to read the crash reports, they are so revealing. This is
not an unknown mod error, in fact it's an out of memory issue. The top line
of stack trace says it all

```

com.google.common.util.concurrent.ExecutionError:
java.lang.OutOfMemoryError: GC overhead limit exceeded
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215)

```


You will need to allocate more ram to the pack, like maybe 6 to 8. If
this is too much consider playing Medieval Times which is the true
vision of what World of Dragons should've been.
