### ISSUE TITLE
Anti matter to cheat dragons

### ISSUE THREAD

**Issue by Draconian4466** [kreezxil/World-of-Dragons#179]
People are using anti matter to cheat underground dragons
You need anti matter for abyssal so no idea what to do.

**Comment by kreezxil** [comment]
Please describe it in detail?

Is anti-matter hard to craft? if it is then it's not really a cheat.

**Comment by daodragon** [comment]
anti-matter is not craft able you go find it in a special swamp.

**Comment by daodragon** [comment]
it's not cheating if there hundred other ways to trap the dragon and shoot it from afar.

**Comment by Draconian4466** [comment]
You can basicly kill it in a few mins with anti matter and its in a swamp not super rare and you only need one bucket to kill it

**Comment by Draconian4466** [comment]
Corailium infested swamp

**Comment by kreezxil** [comment]
technically the problem is abbyssalcraft.

the only real thing i can do here is to increase the dragon hp by a factor
of 10, I probably should do that.

**Comment by kreezxil** [comment]
abbyssalcraft removed in major version 15+ because of this and other issues.
