### ISSUE TITLE
[please fix] mining dynamite goes through claims

### ISSUE THREAD

**Issue by abakedpotato1** [kreezxil/World-of-Dragons#182]
**Describe the bug**
When crafting mining dynamite from cyclic and throwing it in a claimed area, in doing this the dynamite will explode in the area and break the blocks in it.

**To Reproduce**
1. Craft mining dynamite
2. Go to someone else's claimed area
3. Throw the dynamite
4. See the result

**Versions:**

 - Minecraft:1.12.2
 - Forge:14.23.5.2838
 - Mod Pack World of Dragons: 14.61.193
 - Mod Name: Cyclic
 - Mod Version: 1.19.9

**Comment by kreezxil** [comment]
make your own claim and try it there. it's possible the other person
enabled explosions for their claim

**Comment by kreezxil** [comment]
disabled
