### ISSUE TITLE
[please add] clans

### ISSUE THREAD

**Issue by kreezxil** [kreezxil/World-of-Dragons#186]
# Mod Nominated for Adding*
Mod Name: clans
Mod Link: https://minecraft.curseforge.com/projects/clans

# Reason for Nomination

Reason: Provides land claiming similar to Towny, supports factions, raiding, creating raid groups, raid claims, a server OP clan used for op level claiming. Also allows the claim owner to charge rent and sell plots.

I plan to switch to this claiming system over the one provided by FTB Utilities.

**Comment by Draconian4466** [comment]
raiding sounds fun

**Comment by kreezxil** [comment]
if I switch to this, i'm removing tombstone too. No sense in have player raids if you can die and easily recover your stuff. There needs to be a sense of loss.

**Comment by Draconian4466** [comment]
Yeah adds more of a chalenge

**Comment by kreezxil** [comment]
I"ve decided against it

**Comment by Draconian4466** [comment]
:(
