### ISSUE TITLE
raw pork hocks can't convert to salted pork hocks

### ISSUE THREAD

**Issue by iamweirdie** [kreezxil/World-of-Dragons#188]
The raw pork hocks, no matter which salt is used, can't be made into salted pork hocks.

Both pork hocks are from vanilla food pack.

**Comment by kreezxil** [comment]
please show screen shots

**Comment by kreezxil** [comment]
too bad you didn't give screen shots, i tested the recipe and works, had you shown screen shots I think we would've seen that you were using mekanica salt. I've adjusted the recipe to allow mekanica salt to be used too.
