### ISSUE TITLE
[Mod Request] Waystones

### ISSUE THREAD

**Issue by Cthuwu** [kreezxil/World-of-Dragons#19]
# Mod Nominated for Adding*
Mod Name: Waystones
Mod Link: https://www.curseforge.com/minecraft/mc-mods/waystones

# Reason for Nomination
My reason is that it is currently time consumeing to go frome place to place when your base is spread far out or want to stop by a friends house and it adds a teleport system that takes exp to teleport and the amount scales with the distance.

BTW this is froppy/Stormdragon75

**Comment by kreezxil** [comment]
sounds good, I should definitely disable the teleportation provided by ftb utilities then

**Comment by kreezxil** [comment]
mod is added
