### ISSUE TITLE
[please add] Stygian End: Biome Expansion

### ISSUE THREAD

**Issue by kreezxil** [kreezxil/World-of-Dragons#193]
# Mod Nominated for Adding*
Mod Name:
Mod Link: https://minecraft.curseforge.com/projects/stygian-end-biome-expansion

# Reason for Nomination

Reason: brings new variety to THE END

![2018-10-14_18](https://user-images.githubusercontent.com/3880072/59049834-7dbee580-884e-11e9-81a9-9cd0f9187413.png)

Stygian End adds two new biomes to the end dimension and a handful of new ender themed blocks and plants.

![image](https://user-images.githubusercontent.com/3880072/59049753-536d2800-884e-11e9-8b3c-de4e4ad060b1.png)
 
Stygian Growth:

A biome of plant life in the end. Patchy, purple grass dottted with grass and bioluminescent plants. Towering Wyrmwood grow here, but players harvesting their deep purple wood might encounter an endermite infestation. 

![image](https://user-images.githubusercontent.com/3880072/59049774-5f58ea00-884e-11e9-95a0-aa6e15ea2e86.png)
 

Acidic Plains

A harsh enderic acid spews from beneath the porphyry rock. The tainted liquid has corrupted the stone and plant life around it, making traveling through this biome dangerous.

**Comment by hellwolf95** [comment]
would be good to add and only requires the end to be deleted if needed. i added that a long time ago in ROM but if im correct it addes overworld generation of some small end stuff.

**Comment by Draconian4466** [comment]
This mod looks pretty good!

**Comment by kreezxil** [comment]
added
