### ISSUE TITLE
add Just Enough Dimensions

### ISSUE THREAD

**Issue by hellwolf95** [kreezxil/World-of-Dragons#194]
Mod Name: just enough dimensions
Mod Link: [mod link](https://minecraft.curseforge.com/projects/just-enough-dimensions)

Reason: allows us to create new dimensions on the fly in game. it also allows you to make dimensions like a tutorial dimension and set up a warp for it.

id also suggest dimensional mode to force players into a game mode on entering an area.

**Comment by hellwolf95** [comment]
i am using this on ROM and so far seems to be working just fine.

**Comment by kreezxil** [comment]
added

**Comment by kreezxil** [comment]
naw changed my mind, seems to add a level of complexity I don't want to deal with right now.
