### ISSUE TITLE
[please fix] When Dead Reservoir Deletes Itself

### ISSUE THREAD

**Issue by saderen** [kreezxil/World-of-Dragons#195]
**Describe the bug**

When you die, come back to your grave and open it the reservoir is no longer there (and perhaps any thermal foundation item).

**To Reproduce**
1. Craft/Have Reservoir.
2. Die.
3. Return Back to your Grave.
4. Retreive Your Items.

**Screenshots**

**Versions:**

 - Minecraft: 1.12.2
 - Forge: forge-14.23.5.2838
 - Mod Pack :
 - Mod Name: World Of Dragons
 - Mod Version: 16.1.201

**Logs**

Find out how to get me what I need at [What is a Crash Report](https://github.com/kreezxil/World-of-Dragons/wiki/Crash-Reports)

Crash Report: 
Debug Log:
Latest Log:

**Additional context**

**Comment by kreezxil** [comment]
can repeat this reliably in a single player world?

**Comment by saderen** [comment]
Oh. My. God.

[https://prnt.sc/nz8yvt](url)
