### ISSUE TITLE
[please fix] recent update made everything slow

### ISSUE THREAD

**Issue by Zebens** [kreezxil/World-of-Dragons#199]
This bug appeared today if fact. Just soon after I updated to the recent update, I logged into my Singleplayer world and saw that everything was slow. Like, all mobs, anything shot by an arrow/projectile, and even anything I dropped from my inventory. This wasn't like lag or anything, I think, cause I was going the normal speed and my world was still generating new chunks at a normal speed too. At first, It thought this had to do with my PC and all that, but then did some work and found that my PC wasn't that problem at all. I tried restarting my computer then logging into my world and nothing worked. I tried creating a new world and nothing worked. I even tried messing with my Video Settings, and still nothing worked. I also tried this on other modpacks I've played and they seem to word fine. Even vanilla Minecraft ran normally, but just this modpack is the issue. I'm not sure if an update to a mod caused this, but any world, in this modpack, is now unplayable to me. I just want this fixed so I can continue my world. Thanks for taking the time to read this.

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2838
 - Mod Pack :
 - Mod Name: World Of Dragons
 - Mod Version: 16.2.202

**Comment by iamweirdie** [comment]
The problem you're looking at is a new tool recently installed called tick dynamic.
https://minecraft.curseforge.com/projects/tick-dynamic

this isn't to excuse the bug, just to explain it. i hope this helps, and yes, i also hope this bug gets fixed.

**Comment by Zebens** [comment]
> The problem you're looking at is a new tool recently installed called tick dynamic.
> https://minecraft.curseforge.com/projects/tick-dynamic
> 
> this isn't to excuse the bug, just to explain it. i hope this helps, and yes, i also hope this bug gets fixed.

So, should I then increase or decrease the ticks to go back to the way it was? Also, what number?

**Comment by kreezxil** [comment]
Zebens for your private server simply remove tick-dynamic.jar, I'm working
on tweaks today.

**Comment by kreezxil** [comment]
turns out tick dynamic is broken so I've removed it.

**Comment by Zebens** [comment]
Thanks a lot. Fixed my issue completely.
