### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by altantis27** [kreezxil/World-of-Dragons#2]
**Describe the bug**
chopping down a tree an the game crashes, it dosent do it for every tree only after a few.
crash log looks like it the tree mod thats doing it

**To Reproduce**
chop down some trees

**Screenshots**

**Versions:**

 - Minecraft:
 - Forge:
 - Mod:

**Additional context**

**Comment by kreezxil** [comment]
Don't just talk about the crash log, send me the crash log, I need that
report to generate the report that the mod author will need to fix the
issue.

**Comment by kreezxil** [comment]
11 days?
