### ISSUE TITLE
[please add] Extra Bit Manipulation

### ISSUE THREAD

**Issue by iamweirdie** [kreezxil/World-of-Dragons#201]
Mod Link: [https://minecraft.curseforge.com/projects/extra-bit-manipulation](https://minecraft.curseforge.com/projects/extra-bit-manipulation)

Reason:
Adds tools to make chisels and bits mod even easier to use with pre-selected shapes. Also allows for chisels n bits made armor, much more customized than CosmeticArmor

**Comment by kreezxil** [comment]
added
