### ISSUE TITLE
[please add] LittleTiles

### ISSUE THREAD

**Issue by iamweirdie** [kreezxil/World-of-Dragons#203]
Mod Link: [https://minecraft.curseforge.com/projects/littletiles](https://minecraft.curseforge.com/projects/littletiles)

"You can hammer blocks into tiles which can be 4096 (or even more) times smaller than an ordinary minecraft block (you can do it even smaller, because its configurable). You can combine your tiles together to create doors, chairs, ladders, no-clip, storage and any kind of furniture structure."

similar to chisels n bits but slightly more powerful.
unfortunately, u can't blend one type of bit block with the other. having both is fine, though.

**Comment by kreezxil** [comment]
added
