### ISSUE TITLE
[please add] Redstone Arsenal

### ISSUE THREAD

**Issue by KillerJWB86** [kreezxil/World-of-Dragons#204]
# Reason for Nomination
Reason: Since we have already thermal expansion,it is a great mod that goes well with it and helps us with some cool tools to help us progress.Its super lightweight to add and does not cause any problems when added.(I tested it :)

Mod link: https://teamcofh.com/docs/redstone-arsenal/

**Comment by kreezxil** [comment]
test it again and tell me what the pack ram requirement jumps to during
load and after load. And if it's got something o.p. in it like Draconic
Evolution does, i won't be adding it.

**Comment by KillerJWB86** [comment]
I have my MC set to 6144 of ram and on load it never went above 3050. You can see that here
http://prntscr.com/o2sjkj   
 Im not sure what number you want when you say after load cause that will be very diffrent from person to person depending on where they are in MC and what blocks are around them.In game for me it uses 3767, you can see that here   
http://prntscr.com/o2sl9y
The mod only add 28 items,just click the link i posted before that takes you to the mod page.There is nothing i think is op,it just some tools a shield and sword and a armor set.

**Comment by kreezxil** [comment]
added
