### ISSUE TITLE
Losing connection when loading world

### ISSUE THREAD

**Issue by Pm0001** [kreezxil/World-of-Dragons#205]
When loading terrain it always says I lost connection but my internet is great and other modpacks work just fine.
USing the lates version
In the log it says several times: Unable to determine blocks eligibility
[Error Log.txt](https://github.com/kreezxil/World-of-Dragons/files/3294137/Error.Log.txt)

**Comment by kreezxil** [comment]
That log file doesn't reveal anything useful. Have you added any other mods
to the pack? If so remove them.

Also doesn't matter that other packs load fine for you, World of Dragons
uses some of the most intensive memory hogging and cpu sucking mods known,
the core mod Ice and Fire is one of them. I couldn't see how much ram you
had allocated to the pack, that is a factor. Also you need to be on the
latest pack version. If your friends are connecting to the server you have
then its definitely you.

If you're still at a loss of things then I need two things from you.

First I'll need a crash report, you can forcefully generate one by starting
the pack and then opening a single player world. When in the world hold the
F3 key down and also the 'C' key at the same time until  your client
crashes. You'll appear on a screen that says you crashed and gives the name
of a crash report and the option to go back and start again plus another
button that says "get link". **click the** get link button, which will take
you to a website, copy the url and put it here.

The next thing I want you to do is right click the Windows start button and
then choose "run", in the next box that appears, type **dxdiag** and then
hit the ok button. Tell the thing that pops up ok to scan everything if it
asks. There will be a green bar when that is done, the scan is done and
then click the button in the bottom right that says "save all information".
Note where you put the file, open that file, and copy everything in it.
Click "edit" then select all, click "edit" then copy, then goto ![](
https://pastebin.com) click in the big white box and hit **ctrl** + **v**
to paste. The hit submit. A new page will appear, copy that url and put it
here.

We'll go from there.

**Comment by kreezxil** [comment]
closing this as no response in 4 days (ie the weekend) assuming you moved on, reopen another issue if you have the problem again.
