### ISSUE TITLE
[Config suggestion] CGM crayfish gun mod 

### ISSUE THREAD

**Issue by hellwolf95** [kreezxil/World-of-Dragons#206]
# New Config

CGM aka mrcrayfish gun mod

[pastbin link](https://pastebin.com/M8vBCZQW)

i have noticed after playing around with this mod that they are kind of pathetic and get out right beat by every other weapon and this config file just gives them a boost in damage or/and other areas while at the same time nerfing some weapons in other areas. such as the mini gun having buffed damage and buffed max ammo while having damage falloff forcing players up close or the pistol having reduced max ammo with slightly buffed damage but a instant reload.

**Comment by kreezxil** [comment]
thank you, it's been added
