### ISSUE TITLE
add Baubley Heart Canisters

### ISSUE THREAD

**Issue by hellwolf95** [kreezxil/World-of-Dragons#207]
# Mod Nominated for Adding*
Mod Name: Baubley Heart Canisters
Mod Link: [mod link](https://minecraft.curseforge.com/projects/baubley-heart-canisters?gameCategorySlug=mc-mods&projectID=282947)

# Reason for Nomination
TLDR: gives player more health via drops that can help players in the long run fight dragons.

Reason: i have noticed that no matter what armor players have whether it be slime knight armor or even armor from psi like ebony players have a lot of difficulty still trying to kill dragons due to there damage output. this would help players who spend lots of time in game. there are 4 over all teirs to heart canisters requiring the player to kill mobs around the game from normal mobs to bosses like the wither to gain health. these canisters all go into bauble slots adding more value to them for the average player vs something like knightslime on top of that it adds more uses for the bauble slots that currently arnt used by many things.

**Comment by kreezxil** [comment]
added
