### ISSUE TITLE
[please add] Environmental Tech

### ISSUE THREAD

**Issue by XanthusMaximus** [kreezxil/World-of-Dragons#209]
# Mod Nominated for Adding*
Mod Name: 
Mod Link: https://minecraft.curseforge.com/projects/environmental-tech

# Reason for Nomination
Reason: Methods of automatic mining and power generation are already available through Mekanism, but the methods used often create performance issues. The Digiminer, a machine that automatically mines an area, often overticks and also destroys the ground for materials. Environmental Tech adds automated mining and energy production, with a focus on progression in order to better your machines. This would be a great addition, as it allows for automation, but without the dip in performance.

**Comment by kreezxil** [comment]
Sorry this one is big phat no. Environmental tech has several things in it
that I would immediately have to disable. Such that if I did you would say
"why did I add it". The watch of time which is not something I can limit
that amount you craft of can and will bring any server to a grinding halt.
On the Medieval Times version of World of Dragons, we install this mod and
immedately a player created 40 of them. Also it's just another power
generator and the other stuff ...

So no.
