### ISSUE TITLE
[please add] MrCrayfish's Gun Mod

### ISSUE THREAD

**Issue by iamweirdie** [kreezxil/World-of-Dragons#210]
Mod Link: [https://minecraft.curseforge.com/projects/mrcrayfishs-gun-mod](https://minecraft.curseforge.com/projects/mrcrayfishs-gun-mod)

Reason:
Dragons are a real threat to players on the server, both old and new. The greatest defenses we have against them are currently large stationary siege weapons or magic. I'd like to add this as another alternative. We already trust 2 of MrCrayfish's mods- the furniture mod and the vehicles mod. The server previously had TechGuns until we realized it was laggy/ had problems, so this could fill the niche, albeit a bit simpler.

**Comment by hellwolf95** [comment]
Umm thats already in

**Comment by iamweirdie** [comment]
> Umm thats already in

oops sorry
