### ISSUE TITLE
[please add] MmmMmmMmmMmm mod

### ISSUE THREAD

**Issue by iamweirdie** [kreezxil/World-of-Dragons#211]
Mod Link: [https://minecraft.curseforge.com/projects/mmmmmmmmmmmm](https://minecraft.curseforge.com/projects/mmmmmmmmmmmm)

Reason:
The server contains many weapons that can one shot smaller mobs like the skeleton or the zombie, but players need to know how their weapon fares against bigger mobs, like the dragon. This mob gives players a way to know how much damage a weapon deals without having to poke someone's eye out. I have been told it's possible entities cause lag, but I don't think it would unless hundreds or thousands of these were built.

**Comment by kreezxil** [comment]
this is a good suggestion, i will consider it.

**Comment by kreezxil** [comment]
added
