### ISSUE TITLE
[please add] Extra Utilities

### ISSUE THREAD

**Issue by XanthusMaximus** [kreezxil/World-of-Dragons#212]
# Mod Nominated for Adding*
Mod Name: 
Mod Link: https://minecraft.curseforge.com/projects/extra-utilities

# Reason for Nomination

Reason: Extra Utilities adds a number of useful tools for players in game, without causing lag, including well-known items like the Angel Block, solars, and grid power generators. It would be a great addition, if other packs have anything to show from their use of the mod.

**Comment by kreezxil** [comment]
No, no, and hell no. This mod introduces two power systems one on top of
the other. It's horribly broken and parts of it are horribly o.p. AF.
