### ISSUE TITLE
[please add] farming for blockheads

### ISSUE THREAD

**Issue by iamweirdie** [kreezxil/World-of-Dragons#213]
Mod Link: [https://minecraft.curseforge.com/projects/farming-for-blockheads](https://minecraft.curseforge.com/projects/farming-for-blockheads)

Some people would prefer not to go hunting outside for seeds, trees, and saplings. This provides a simple trading depot for those people, and for those more invested in cooking or other things involving food variety, this is a godsend. There aren't any overpowering crops, so it won't link a beginner to a god-tier healer, they still need to cook the food on their own to make it any better.

This mod does not add any of its own seeds or saplings, simply a trading post for them.

**Comment by kreezxil** [comment]
those people don't need to play Minecraft either, what they need is
something like chess or checkers, or even simpler, maybe hungry hungry
hippo.

I'm not going to add that.
