### ISSUE TITLE
[Bug] aw2 chests not containing loot

### ISSUE THREAD

**Issue by Draconian4466** [kreezxil/World-of-Dragons#214]
The advanced loot chests which are supposed to be dungeon loot chests have been empty i think they are bugged

**Comment by Draconian4466** [comment]
It looked like it was fixed on wod hell pretty sure a world wipe would fix this

**Comment by kreezxil** [comment]
I haven't even remotely touched it, AW2 has updated once since then however.

**Comment by kreezxil** [comment]
the mod is removed in M18
