### ISSUE TITLE
[Config File] Corail Tombstone

### ISSUE THREAD

**Issue by Warlok333** [kreezxil/World-of-Dragons#215]
In light of death being much more horrific, I would ask that the config for the Ankh recharge from Corail be considered for reduction in time. The Ankh gives a small amount of Knowledge of Death when it is used near a decorative grave, but the default setting is a 3-hour (real-world) recharge timer. Perhaps 1 hour would be more fitting?

**Comment by kreezxil** [comment]
the lowest i can go is 1 hour.

also done.
