### ISSUE TITLE
[please remove] redstone arsenal

### ISSUE THREAD

**Issue by Draconian4466** [kreezxil/World-of-Dragons#217]
to over powered the armor is pretty much like red matter armor from medievel times no dmg from a stage 3 dragon also the sword when empowered does more then any non tinkers sword

**Comment by kreezxil** [comment]
ok, that's gonna make @killerjwb very happy!

**Comment by iamweirdie** [comment]
> too overpowered ... no damage from a stage 3 dragon

It's not easy to obtain the armor, though, and aren't there any tinkers armors or psi spells able to withstand the same damage?

> the sword, when empowered, does more than any non-tinkers sword

That leads to the question, what's more powerful than a tinker's sword?

**Comment by Draconian4466** [comment]
the metal to make it all is actually pretty easy to obtain all you need is silver gold a grinder some way to get destabalized redstone (like a smeltery) and an induction smelter then you can make armor which can make you take no damage from a stage 3 dragon so the armor sounds easy to make and can survive something you are supposed to die from also i havent found any tinkers armor able to withstand it yet maybe if you spend 100 stacks of iron blocks on your armor sure but thats way more expensive

**Comment by iamweirdie** [comment]
fair enough...

**Comment by kreezxil** [comment]
rather than remove it I decided to try nerfing the values in the config. If players begin complaining that I ruined it then we know I've succeeded. If it is still OP AF then I will remove it next patch.

**Comment by Draconian4466** [comment]
did you nerf it? everything still seems pretty op

**Comment by iamweirdie** [comment]
> did you nerf it? everything still seems pretty op

TheQuantumRuby or TheKoolestAid [i think] also noticed that the client Redstone Arsenal config was still the same since the update.

**Comment by kreezxil** [comment]
I nerfed it hard in it's config. If it's still too o.p. I'll get rid of it.

**Comment by kreezxil** [comment]
the client, yeah but the server no, that's where I nerfed it.
