### ISSUE TITLE
[please fix] Stygian End causing Server Crash

### ISSUE THREAD

**Issue by Warlok333** [kreezxil/World-of-Dragons#218]
**Describe the bug**
Generating new chunks in Stygian End biomes appears to crash the server...likely due to calling on LavaDynamics to spawn volcanoes which cannot spawn in The End dimension.

**To Reproduce**
1. Generate Stygian biome (any of them, it seems) chunks in The End
2. Server crashes/resets.

**Versions:**
 - Mod Pack: 16.6.206
 - Mod Name: Stygian End v1.0.4
 - Mod Name: Lava Dynamics v1.12.2-5.5.7

**Additional context**
From chatting with admins with access to the server logs, our best guess is that the Stygian End biomes are calling for volcanoes to spawn from the Lava Dynamics mod but since volcanoes cannot spawn in The End, the process hangs and stalls out the server.

**Comment by kreezxil** [comment]
I fairly certain that's not the issue here. Good guess tho.
