### ISSUE TITLE
[feature request] Rats must Die

### ISSUE THREAD

**Issue by Zer0Gam3r** [kreezxil/World-of-Dragons#220]
I would like to see Rats added to the targeting algorithm for the ToroQuest guards and sentries. Realistically, anyone with a weapon would kill rats on sight in a time where plague rats and large farms are a thing.
I would also like the rats to be slowed down when eating, and for a short moment after (as if they were full).

That is all. I just really don't think they're well balanced yet.

**Comment by hellwolf95** [comment]
toro quest doesnt works like that its enemies are likely set to target any hostile entity if the rats are not tagged as hostile they wont attack them so complain about it to the rats mod maker or toroquest mod maker. Kree has no control over the mods code.

**Comment by kreezxil** [comment]
@Zer0Gam3r Alex the author of Rats has been very responsive in making bug fixes and requests. I attached your request to my recent bug report at https://github.com/Alex-the-666/Rats/issues/36

**Comment by kreezxil** [comment]
If you check that thread, Alex says the rats are listed as hostile, that the problem is with Toroquest.
