### ISSUE TITLE
Game / Server crash - within a AW2 structure

### ISSUE THREAD

**Issue by bgudehus** [kreezxil/World-of-Dragons#221]
Hi,
I was within an AW2 structure (small ruin with Orcs below), had just cleared it out, broke a brewing stand and was heading for a room with an obsidian obelisk when I crashed the server.  Every Time I relog, server crashes.

I had defeated the Orc Warlord and taken some of the loot (including some ElectroBlobs loot - books and Firebomb) along with some dothack weapons

**Comment by kreezxil** [comment]
Whose server is crashing? Mine or yours? If yours, i need the crash reports, if mine, I need the approximate times it was happening.

**Comment by bgudehus** [comment]
Yours - WOD USA.  Last crash at 9:51am MST

**Comment by kreezxil** [comment]
ok, get on and crash it again

**Comment by bgudehus** [comment]
Justs crashed the Server

**Comment by kreezxil** [comment]
when tho, you got to give me a time

**Comment by bgudehus** [comment]
Sorry - will do it again and note time.  I thought maybe you can see time stamp on a comment as the comment above I had just crashed the server 10 seconds before

**Comment by bgudehus** [comment]
Kreezxeil - I crashed the server on June 29, 2019 at 11:47 am MST (Mountain Standard Time) - see below the Discord msg
interchatBOTToday at 11:47 AM
MechnoVinci just joined the server!
Server crash detected!

<ADMIN> iamweirdie [lowest form]Today at 11:47 AM
ah can't believe you've done this lol

Hope this helps

**Comment by kreezxil** [comment]
Are you also Mechnovinci?

**Comment by kreezxil** [comment]
we've determined it was dynamic trees the whole time.
