### ISSUE TITLE
[please add] 'Vending Block'

### ISSUE THREAD

**Issue by TheQuantumRuby** [kreezxil/World-of-Dragons#222]
Mod Link:
https://www.curseforge.com/minecraft/mc-mods/vending-block

# Reason for Nomination

Reason: This mod should be added because it adds a vending block (as the name implies) that allows players to create shops that are not based on the honor system. This also means that players may create shops that people may buy from while the owner of said shop is offline. The mod also does NOT add a currency system, so players may use their own ideas of currency. For example, a player might sell a Scarab Gem (a rare item/modifier found from Fossils) for 4 Golden Dragon Coins from AW2. The mod also promotes a currency system, despite not adding an actual currency, as it would be easier to have a universal currency so all shops are compatible.

**Comment by kreezxil** [comment]
that mod is garbage

**Comment by iamweirdie** [comment]
Forestry has a shop mechanic based on trading implemented, it only requires about a week or 2 weeks of breeding. I was gonna spring the news that I now have the key bees, it's just a matter of mass producing the stuff needed and distributing it.

[https://forestryforminecraft.info/mail:tradestation](https://forestryforminecraft.info/mail:tradestation)
[https://forestryforminecraft.info/mail:catalogue](https://forestryforminecraft.info/mail:catalogue)

Yes, it requires people to be online for the trade station to operate, but we also have methods of sending requests to people offline:

[https://forestryforminecraft.info/mail:mailbox](https://forestryforminecraft.info/mail:mailbox)

**Comment by kreezxil** [comment]
please don't mass produce stuff, decided to add this mod, hopefully it's not garbage.
