### ISSUE TITLE
[please add] Wings horns and hooves

### ISSUE THREAD

**Issue by Draconian4466** [kreezxil/World-of-Dragons#223]
Mod Name: 
Mod Link: https://www.curseforge.com/minecraft/mc-mods/wings-horns-hooves-the-ultimate-unicorn-mod

Reason: in discord you said you could add this mod back and since it adds a bunch of horses which you can make aw2 npcs mount and adds a mob players are going to want to keep

**Comment by kreezxil** [comment]
I removed it, why not found out why, and then see if it's resovled whatever
it was.

**Comment by kreezxil** [comment]
added it back, everything appears fixed in the gitbucket, sooo we'll see.
