### ISSUE TITLE
[please add] Blood Magic

### ISSUE THREAD

**Issue by beefstek** [kreezxil/World-of-Dragons#224]
# Mod Nominated for Adding*
Mod Name: 
Mod Link:
https://www.curseforge.com/minecraft/mc-mods/blood-magic/files
# Reason for Nomination

Reason: this is a world of dragons and magic and i feel like necromancy and darker magics arent really emphasized in this pack, also blood magic is just a really cool and fun mod to have

**Comment by Draconian4466** [comment]
this mod looks pretty fun and adds another path of magic to go through especially if you want to be a dark mage

**Comment by kreezxil** [comment]
no, no, no, I had it once in the beginning, there are problems with it.

**Comment by Draconian4466** [comment]
What problems?

**Comment by iamweirdie** [comment]
one immediate problem i can think of right off the bat is blood farming.
If you really want to extensively use your OP weapons, you're gonna need a lot of mob blood. i've seen people set up MASSIVE witch cages for sacrifices of blood.
you guys were already complaining about how powerful redstone arsenal is versus how easy it is to obtain the items. in this case, it's how powerful the weapon is versus the amount of lag your eventual blood farm will generate.

**Comment by Draconian4466** [comment]
Im pretty sure kreezxil said he set mob spawners to only spawn things 20 times

**Comment by kreezxil** [comment]
I took that mod out.

**Comment by kreezxil** [comment]
I'll add it, let's see where it goes since all the issues I ever reported seem to have been fixed. https://github.com/WayofTime/BloodMagic/issues?q=is%3Aissue+author%3Akreezxil+is%3Aclosed
