### ISSUE TITLE
[please remove] Dynamic Trees

### ISSUE THREAD

**Issue by TheKoolestAid** [kreezxil/World-of-Dragons#225]
# Mod Nominated for Removal
Mod Name: **Dynamic Trees**

# Reason for Nomination
Reason: At the time of writing this, there have been several crashes on the server involving dynamic trees corrupting chunks when the tree's blocks were burnt and destroyed by a dragon's fire. There only have been two instances of errors, but many crashes have happened as a result. Two admins have already looked at the crash logs and fixed this. Both of which claimed that it was this mod. I'm simply the one posting the issue.

Sincerely,
TheKoolestAid.

**Comment by kreezxil** [comment]
This requires a world wipe, and as such a new pack based on Major 16 will
be released shortly. Since i don't want to wipe the world.

**Comment by kreezxil** [comment]
decided it doesn't require a worldwipe and it is now officially gone
