### ISSUE TITLE
[please add] Open Modular Turrets

### ISSUE THREAD

**Issue by iamweirdie** [kreezxil/World-of-Dragons#227]
Mod Link: [https://www.curseforge.com/minecraft/mc-mods/openmodularturrets](https://www.curseforge.com/minecraft/mc-mods/openmodularturrets)

Reason for Nomination:
In its current state, the modpack provides a mostly magical or medieval defense. The two pieces of defense technology we DO have, security turrets and MrCrayfish's gun mod, are quite limited. It would be beneficial to boost the choices for tech defense. In addition, the mod integrates with the RF and FE power systems, and it also has interesting features like camo and gun addons.

PS I know you said one mod per suggestion, but this is a small companion mod which contains defenses that match the aesthetic of the OMT mod.
[https://www.curseforge.com/minecraft/mc-mods/ompd](https://www.curseforge.com/minecraft/mc-mods/ompd)

**Comment by kreezxil** [comment]
hmmm ok
