### ISSUE TITLE
[please add] Cooking For Blockheads

### ISSUE THREAD

**Issue by iamweirdie** [kreezxil/World-of-Dragons#228]
Mod Link: [https://www.curseforge.com/minecraft/mc-mods/cooking-for-blockheads](https://www.curseforge.com/minecraft/mc-mods/cooking-for-blockheads)

I know I recommended this on the previous server on the argument of limited storage, but this mod has other features I'd like to focus on, particularly these 2:
[http://blay09.net/mods/cookingforblockheads/cooking_table](http://blay09.net/mods/cookingforblockheads/cooking_table)
[http://blay09.net/mods/cookingforblockheads/sink](http://blay09.net/mods/cookingforblockheads/sink)
You can create your kitchen out of components like the tool rack and the cabinet. Once finished and integrated, the cooking table allows players to craft based on what is in the [multi-block] Kitchen's inventory.
The other feature, the sink, "[w]hen ... used as part of a multiblock kitchen, recipes that require water buckets ... will automatically use water from the sink." [from wiki - http://blay09.net/mods/cookingforblockheads/sink]

**Comment by Warlok333** [comment]
My only concern with the sink is that is is often used in other modpacks as a cheap, infinite water source for machinery. This may be deemed acceptable or not, but I thought it was pertinent to bring it up.

**Comment by iamweirdie** [comment]
That's true, but water in itself is a cheap, renewable resource in Minecraft. The sink can't be pipes out, and while effectively providing water, it only provides water for food and potions. It's also possible to gain lots of water using the aqueous accumulator of the thermal mod series, but I don't really see any harm in having the sink or the aqueous accumulator.

**Comment by kreezxil** [comment]
to let you know, I will not be adding new mods to wod until all current
crashing issues are resolved. There is no sense in adding things when it's
already volatile. I'll leave everything open however.

**Comment by Draconian4466** [comment]
You said you would leave every thing open?

**Comment by kreezxil** [comment]
because I put them all in WOD Hell.
