### ISSUE TITLE
[Mod]Apotheosis

### ISSUE THREAD

**Issue by Yodown814** [kreezxil/World-of-Dragons#231]
Mod Name: Apotheosis
Mod Link: https://www.curseforge.com/minecraft/mc-mods/apotheosis

Reason: First of all, I think "enchanting" in wod could be somehow.... welp, useless or worthless, because there's no really any uses of them from any resources (By my personal opinion). So this mod, basically fulfills your wishes if you truely wanted something more to mess with and also a bunch of new cool features. Don't really wanna read a bunch of paragraphs on the mod forum? Let me conclude some of the features here:

1. Adds more very cool enchantments to the game, like "Berserker's Fury" which instantly drops your health to 3 hearts if attacked by also give some very strong positive affect at the same time.

2. More uses on Anvil! you can now repair it with iron blocks and even ENCHANT it and gives it some special abilities.

3. Want to mess with enchantments more? you can now craft an more "advanced bookshelf", which lets you enchant an item to over the old level cap 30, but now <100! which can both be good and bad, because you might get a "Masterwork" enchantments, or "Corrupted" enchantments. Sounds fun right?

4. The most exciting part, mobs. You might also find "Mini Bosses" and "Rougue Spawners" in some areas while exploring, and you can also COLLECT the spawner and adds modifiers to it such as increase/decrease the spawning delay.

So yeah, that's basically what this mod does, adds a bunch more features to "combat" and "mob" side, reuse the original Minecraft fashion equipments, and also created more opportunities on adventuring. I will also leave a YouTube video link down here if you are really curiously in how this mod works, thanks! 👍 :

https://www.youtube.com/watch?v=3TSXqwpymJQ

**Comment by Draconian4466** [comment]
I think.this mod was in medieval times and it looked pretty good

**Comment by kreezxil** [comment]
@Yodown814 you've made a good case for the mod, I wish other suggestions were like yours. I'll add it but it won't be until possibly sunday, sooner if JurassiCraft gets approved sooner.

**Comment by Yodown814** [comment]
> @Yodown814 you've made a good case for the mod, I wish other suggestions were like yours. I'll add it but it won't be until possibly sunday, sooner if JurassiCraft gets approved sooner.

Thank you! very appreciated it!

**Comment by Draconian4466** [comment]
The enchantments it adds should be dissabled for the advanced enchant table

**Comment by kreezxil** [comment]
added
