### ISSUE TITLE
[please fix] Un-fired Crucible Bug

### ISSUE THREAD

**Issue by IppSwitch** [kreezxil/World-of-Dragons#232]
The bug is, Crucible reverting to "Unfired" version. 

After placing the "Unfired Crucible" in the Furnace, it will cook as normal. After completion you will have a "Crucible". After picking it up and going to place it, if you place it directly OVER the lava block, it will revert to it's "Unfired" version.

This does not happen on a Candle.
Have not tried other heat sources.

**To Reproduce**
Create a Unfired Crucible.
Cook Crucible in Furnace (Vanilla)
Take finished Crucible and place over a Lava block.

**Screenshots**

**Versions:**

 - Minecraft: 1.12
 - Forge: Unsure Using twitch app so i'm assuming latest. 
 - Mod Pack World of Dragons
 - Mod Name: World of Dragons
 - Mod Version: 17.0.208

**Logs**
No crash.

Crash Report: N/A
Debug Log: N/A
Latest Log: N/A

Edit*: Candle, Netherrack fire and Petrol lava do NOT cause this effect.

**Comment by kreezxil** [comment]
Under versions you really answered stuff wrong
**Mod Name** is not the pack name, it's the mod with the item or block that is failing you
**Mod Version** is the mod's version not the pack version
**Forge Version** you can get it from the start screen of the pack.

You do have a debug log and latest log, left click the pack icon, not the play button and get the debug.log and latest.log from the logs folder, put them on https://paste.dimdev.org

**Comment by daodragon** [comment]
I have went and tried several ways of making the unfired crucible. getting them with a command, from creative inventory, making them then smelting them in different furnaces and placing the finished product over lava all of which reverted back to unfired crucible. Now we need you to first reproduce these then like kreezxil said we need you to give us the latest log and the debug log.


![Ra_Chaos_dragon on local game 2019-07-04 12_23_12 PM](https://user-images.githubusercontent.com/46076603/60679881-33ce1d00-9e57-11e9-808b-3bd83ffb3c4f.png)

**Comment by kreezxil** [comment]
for us we solved this by removing ex nihilo from the pack.
