### ISSUE TITLE
[please add] Wizardry

### ISSUE THREAD

**Issue by Draconian4466** [kreezxil/World-of-Dragons#234]
Mod Name:
Mod Link: https://www.curseforge.com/minecraft/mc-mods/wizardry-mod

# Reason for Nomination
Reason: 

- Adds a lot of customizable spells to help you become a master wizard

- Adds some mobs for some more excitement in the world 

- Mod updates pretty frequently so more likely to fix bugs when needed

- Adds some new dimensions for players to explore

 -capes with effects and for cosmetic 

- cool halos for cosmetic and has uses

- mana is very abundant with this mod so no need for huge lag machines

- easy to use spell system

Overall it adds another avenue of magic for the player to go down and enjoy

**Comment by kreezxil** [comment]
I believe this mod was broken in some way as to why we don't have it. Check
my githubs for the reason.Or check wizardry for the author kreezxil.

**Comment by Draconian4466** [comment]
Looked at wizardry for the author kreezxil saw nothing

**Comment by Draconian4466** [comment]
Didnt see it in any of your githubs

**Comment by kreezxil** [comment]
I have electroblob's wizardry, why do you need this one?

**Comment by Draconian4466** [comment]
Electrobobs wizardry is great but with the current aw2 bug it is very hard to do also this wizardry mod has spell making

**Comment by kreezxil** [comment]
like i also said I need questlines, and the pack will have to go on a diet
again to add more mods, haven't you noticed it's not as busy as it used to
be? this due wholly because of the size of the pack.

**Comment by kreezxil** [comment]
done
