### ISSUE TITLE
[please add] Mowzie's Mobs

### ISSUE THREAD

**Issue by Yodown814** [kreezxil/World-of-Dragons#238]
I knew that Kree said he wasn't planning to add any more mods until he gets done with his stuff, it's just a mod suggestion so he perhaps can add it into the server when he is free to do so.

**Mod Name**: Mowzie's Mobs
**Mod Link**: https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs

**Reason**: I suppose some people are started to get bored of playing, like me. Why? of course it's because we got nothing to do in the game! But we still love wod don't we? So, _**Mowzie's Mobs**_ is here! What does it do? let me tell you.

1. Mowzie's Mobs, of course, is related to "mobs". The mod introduced some very **unique** mobs, they all have their specialties in some way, like sounds and actions, so you don't get a mob like a zombie that can be just kill with almost **no equipment**. 

2. Not only it brings "mobs", they also come with some special items, like _"Axe of a Thousands Metals"_,  a GIANT axe that swings in 180 degrees and destroys the enemy at front of it. _"Sun's Blessing"_, which can call **sunstrike** and fire a **solar beam**.

Yes, that's all that I'm gonna tell you about the mod, if you ask: "Okay, sounds cool, but why is there such a little information about the mobs themselves?" Welp, because I want to YOU, to figure it out
yourself(Yes, like in Dark Souls lol), and also not to spoiler any details about the mobs, so you can have your own curiosity and fun while adventuring! 

    Please do consider telling me your ideas and thoughts about the mod, whenever you are positive or negative, they can help me greatly for further more mod suggestions like this. And just ignore some INTERESTING grammaring or spelling errors, I had just begun studying English like 2 years ago, shhh~

**Comment by Draconian4466** [comment]
Ive seen a bit of this mod and from what ive seen it looks really good i hope it gets added

**Comment by hellwolf95** [comment]
one huge problem with this mod is the plant monsters cause a server crash so they have to be turned off

**Comment by kreezxil** [comment]
added and noted, we'll test the plant thing in the pre-test which will happen in an hour or two.
