### ISSUE TITLE
[feature request] Boats are not accessible to early game players

### ISSUE THREAD

**Issue by Don-Silver** [kreezxil/World-of-Dragons#24]
When I joined the InDev version of WoD I noticed the addition of Better with mods which at first infuriated me but when I got to understand some of the basic mechanics it was tolerable. Until I attempted to sail away from spawn. As I was looking through the recipes to make a boat it soon became clear I first needed to make something called a saw in order to process wood to make wood "sidings." However, I hadn't ever used this mod and it soon became clear It was not so simple as making a saw, I had to make a processed type of leather-which in turn meant I had to make 2 other processing constructs (by this I mean multiple blocks needed to be combined in a specific layout for a single function) and iron mining I would have to mine, hunt for cows or rabbits, and research the processes to use said constructs. then I finally made a saw in hopes of finally getting a boat-after a day of working at this- only to find out that in order to power a saw I would need a windmill which is _you guessed it_ another construct. In order to craft a windmill one must farm hemp to make fabric and craft the different parts and -blah blah blah- this construct on the wiki is said to be "a large structure and therefore requires a 13x13x1 blocks of free space (6 block radius around the axle)." After having researched this and realizing the daunting task JUST TO MAKE A BOAT, I resorted to rtping around which thus loaded in chunks around the map.

My recommendation is to revert the crafting recipe for a boat to the original vanilla recipe, because even to make planks is a hassle enough for early game players

My alternative is to either provide boats at spawn or another easy travel alternative

I say planks are hard enough because in order to get planks one must hand punch the upper weaker branches of a tree (which generally yields 1-2 planks per branch broken) or to make planks from logs (you get logs by breaking any part of a tree with an axe type tool) you are supposed to craft logs and an axe together but that crafting recipe has a conflict and instead creates chopped logs which are basically useless. although you can make a mattock (which means getting into tinkers construct) to make planks from logs

If necessary I can provide both links to the wiki, and screenshots of the numerous jei recipes.

**Comment by kreezxil** [comment]
so what I"m getting from this is that I need to turn of ftb utilities' /rtp and put a cool down on the one in /mc rtp

**Comment by Don-Silver** [comment]
There is a cool down of 10 min for any rtp already kree

**Comment by kreezxil** [comment]
cheaper boat recipes turned back on.
