### ISSUE TITLE
Applying Horseshoe to Nightmare crashes Client

### ISSUE THREAD

**Issue by LittleDevilZed** [kreezxil/World-of-Dragons#240]
**Describe the bug**

After I put the obsidian horseshoe onto the nightmare horse from a mod, it causes my game to be froze and crashed 
**To Reproduce**
1. Go to the horse nightmare and get on him
2. Click on the button e to open the GUI and put on saddle, diamond horse armor AND the obsidian horseshoe
3. See error

**Screenshots**

**Versions:**

 - Minecraft:1.12.2
 - Forge:forge-14.23.5.2838
 - Mod Pack :17.1.209
ultimate_unicorn_mod-1.12.2-1.5.16.jar
 - Mod Name:Wings Horns & Hooves, the Ultimate Unicorn Mod
 - Mod Version:
1.5.16.

**Logs**

Find out how to get me what I need at [What is a Crash Report](https://github.com/kreezxil/World-of-Dragons/wiki/Crash-Reports)

Crash Report: https://paste.dimdev.org/sibufeyoge.mccrash
Debug Log:
Latest Log:

**Additional context**

**Comment by kreezxil** [comment]
Issue now posted with hackshop at https://bitbucket.org/ultimateunicornmod/ultimate-unicorn-core-mod/issues/16/applying-horseshoe-to-nightmare-crashes

**Comment by kreezxil** [comment]
and we're still waiting. I think they are waiting on more crash reports in regard to it.

**Comment by kreezxil** [comment]
I'm starting to remember why I removed this mod from my packs in the past. Will i remember the reason in the future?

It's because the mod author can't be arsed to fix it.

**Comment by kreezxil** [comment]
Yeah this mod will not exist in M19 of WOD
