### ISSUE TITLE
Nest breaks bedrock

### ISSUE THREAD

**Issue by NyanCatKrazy** [kreezxil/World-of-Dragons#243]
**Describe the bug**
An Ice and Fire dragon nest was created on bedrock thus replacing the bedrock with the nest

**To Reproduce**
1.Have dragons on bed rock as the floor
2.breed the dragons
3.the female lays a nest underneath her replacing the blocks
4. nest blocks can be broken thus leaving an empty space where bedrock used to be

**Screenshots**
![image](https://user-images.githubusercontent.com/52762853/61007162-5665a780-a329-11e9-976f-6ffa407c15ee.png)

![image](https://user-images.githubusercontent.com/52762853/61007182-68dfe100-a329-11e9-8948-148e6f2a326c.png)

**Versions:**

 - Minecraft: 1.12.2 
 - Forge: Forge-14.23.5.2838
 - Mod Pack: World of Dragons (17)
 - Mod Name:  Ice and Fire 
 - Mod Version: 1.7.1

**Comment by kreezxil** [comment]
not really a bug considering that bedrock is 3 layers deep. I'll pass it on
to the ice and fire guys or you can do that for me
https://github.com/Alex-the-666/Ice_and_Fire/issues

**Comment by kreezxil** [comment]
I think this is caused by having flat bedrock

**Comment by kreezxil** [comment]
Also please update wod 18, wod 17 is no longer supported.
