### ISSUE TITLE
[please remove] ancient warfare 2

### ISSUE THREAD

**Issue by hellwolf95** [kreezxil/World-of-Dragons#244]
Mod Name: Ancient Warfare 2

Reason:
After having this on the server for a bit i have noticed that at times some of the npcs and or work blocks from this mod stay loaded even without the player on. with some of the items and all the npcs having about 30 U/ts which after a while takes its toll on the server.

**Comment by Yodown814** [comment]
I personally am fine with this mod, I think it adds some pretty cool features for explorers, but if what hellwolf said was true, then remove this mod could help reduce some lags on the server.

**Comment by kreezxil** [comment]
Yes the odd chunk load capability of this mod is grounds for removal. So
basically it looks like you guys want a world wipe for major 18.

**Comment by kreezxil** [comment]
it's gone
