### ISSUE TITLE
[please remove] Binnies mod

### ISSUE THREAD

**Issue by hellwolf95** [kreezxil/World-of-Dragons#245]
Mod Name: Binnies Mod

Reason:
I dont think anyone uses this and so many items dont seem to work either

**Comment by Yodown814** [comment]
Same, plus how big it is, it might be a good decision to remove it.

**Comment by kreezxil** [comment]
this adds the bees that allow you to produce alcohol. Lots of players use
this.

**Comment by iamweirdie** [comment]
as a guy who played with the alcohol part of the mod, i hav yet to find an alcoholic beverage that does more than half a second of nausea effect. the useful alcohol might be from rustic or another mod, but i'm pretty sure it's not this mod. so alcohols of this mod are pretty bad.
the wood deco and glass deco system is cool but we also hav the chisel bits and littlethings mod to do similar if not same functions
the genetics system is actually a bigger nightmare than regular bee breeding.
the one thing i get from this mod that i rly cant complain about is the extra special bee frames like the soul frame. those dont come with vanilla forestry and they REALLY accelerate getting new bees quickly

**Comment by daodragon** [comment]
the useful alcoholic beverages are from rustic. the mead, the ironberry wine, the wine and the cider are all from rustic.

**Comment by kreezxil** [comment]
done
