### ISSUE TITLE
[please remove] Toro Quest

### ISSUE THREAD

**Issue by hellwolf95** [kreezxil/World-of-Dragons#246]
Mod Name: Toro Quest

Reason:
all though i like what this adds HOLY CRAP do the guards over spawn in villages and they never stop spawning either. even if the village is destroyed and the leader is killed and all of the people are killed as well. Unless there is something to reduce there spawns id say we think about removing this

**Comment by Yodown814** [comment]
I will also like it to be removed. I don't see anyone even play the mod, and the guards are very annoying too. So why not remove it to reduce the size and the lag from the modpack?

**Comment by kreezxil** [comment]
Just because you don't play it don't mean others aren't playing it. Also
the the public server population density is greatly reduced when it isn't
people do everything.

**Comment by kreezxil** [comment]
however, I agree, I've been unhappy with it too lately.
