### ISSUE TITLE
[please fix] popcorn smelting

### ISSUE THREAD

**Issue by daodragon** [kreezxil/World-of-Dragons#25]
The mods objective is to use lava to smelt ores and other smelt-able items.

mod special feature that make ores and smelted item float and not get burned by lava does not work, can't be sure about the smelting process because items get burned after a few second.

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2796
 - Mod: WOD 14.4.136

**Comment by kreezxil** [comment]
discovered it was missing in the server pack, added it to the server to resolve the issue.
