### ISSUE TITLE
[please remove] Non used Configs

### ISSUE THREAD

**Issue by hellwolf95** [kreezxil/World-of-Dragons#250]
the Following configs are from past mods that have been removed this will help in the long run to reduce time to download pack by a bit
Folders in config
Levelup2 folder, mekanism folder 
config files
animania.cfg, jurassicraft.cfg, levelup2 cfg, mekanism.cfg, natura.cfg, nopoles.cfg ,popcornsmelting.cfg, techguns.cfg, thermalsolars.cfg, tickdynamic.cfg, tinymobfarm.cfg

**Comment by hellwolf95** [comment]
these are the ones I know can be removed I can't say if any others can be removed or not

**Comment by kreezxil** [comment]
done
