### ISSUE TITLE
[please add] Roots 3

### ISSUE THREAD

**Issue by NyanCatKrazy** [kreezxil/World-of-Dragons#251]
# Mod Nominated for Adding*
Mod Name: Roots 3
Mod Link: https://www.curseforge.com/minecraft/mc-mods/roots

# Reason for Nomination

Reason: In this mod natural items can be used for magic! The mods smaller than blood magic and thaumcraft so it could fit perfectly for those who love to explore! It also suits the exploration part of the game! And the armor is very pretty! It's very easy for beginners to understand having a starter book and everything!

**Comment by Magicalllamasempai** [comment]
I am very much looking forward to being able to use this mod they made it a lot easier to get started by not having to find a fairy pond

**Comment by Draconian4466** [comment]
This mod looks really good and roots worked really good in midevel times its another form of magic too

**Comment by Draconian4466** [comment]
the items and spells are pretty fun too features a ritual system and has some cool armors

**Comment by Yodown814** [comment]
Have seen it a couple times, definitely a very cool mod, but if there could be some more information like a YouTube video that talked about the mod itself rather than why it should be added, that will be awesome.

**Comment by iamweirdie** [comment]
https://www.youtube.com/watch?v=3EiiMwVJz6o the video is a bit dated but it does the job

**Comment by Draconian4466** [comment]
If this mod is added i could probably do a questline on it

**Comment by kreezxil** [comment]
You guys forgot that Roots depends on Mystic World which adds insects and stuff and if memory servers right you guys complained (bitched) about it. Also Added, enjoy the pain.
