### ISSUE TITLE
[please remove] Extra rails

### ISSUE THREAD

**Issue by Draconian4466** [kreezxil/World-of-Dragons#254]
# Mod Nominated for Removal
Mod Name: Extra rails 

# Reason for Nomination
Reason: It just adds rails which havent been used and dont have too much of a use

**Comment by kreezxil** [comment]
did you even fucking talk this over with anyone, seems like you are posting removal suggestions for stuff that **YOU DON'T USE** not what **OTHERS DON'T USE**
