### ISSUE TITLE
[please add] Totemic

### ISSUE THREAD

**Issue by Draconian4466** [kreezxil/World-of-Dragons#258]
# Mod Nominated for Adding*
Mod Name: 
Mod Link: https://www.curseforge.com/minecraft/mc-mods/totemic

# Reason for Nomination
Reason:Adds totems which are like beacons but can be stacked for decor and special effects which would be good for defending against dragons also adds a few cool mobs also has instruments which players can use for music or the rituals it was also in Wod-hell and was pretty fun

**Comment by kreezxil** [comment]
added
