### ISSUE TITLE
[please add] Recurrent Complex

### ISSUE THREAD

**Issue by hellwolf95** [kreezxil/World-of-Dragons#260]
Mod Name: Recurrent Complex
Mod Link: [recurrent complex](https://www.curseforge.com/minecraft/mc-mods/recurrent-complex)

Reason:
I know players like to explore dungeons and everything and this can be a serverside only with a simple config change or can be added on the client to allow opped players to make custom structures. It also starts with over 200 structures to generate ranging from trees to entire dungeons that are randomized in layout [Strucutres](https://imgur.com/a/oQnb1).

**Comment by Yodown814** [comment]
As an exploring lover myself, this is definitely a mod that should be considered in order to replace the old aw2 structures and also adding **a lot** more structures, this is gonna be awesome!

**Comment by kreezxil** [comment]
added
