### ISSUE TITLE
[please add] Millénaire

### ISSUE THREAD

**Issue by Yodown814** [kreezxil/World-of-Dragons#262]
**Mod Name**: Millénaire
**Mod Link**: https://www.curseforge.com/minecraft/mc-mods/millenaire

**Reason**: Since the removal of aw2, I think this mod could perhaps replace it in a certain way, but in a better way.

_Millénaire_, a mod that mainly focused on NPC villagers, it is designed to replace the original Minecraft villagers, and of course, they are much more than just villagers ...

1. As NPCs, they can have different factions along each village. Norman, Mayan, Inuits, and even bandits! All NPCs have their own **personalities**, they have their own name, own skin, and even chat system!

2. Villagers surely can trade with you! Drop off the old Minecraft trade menu, the mod has it's own **trading system and GUI**, and they can now not only accept emeralds, but they also accept many more variety of things!

3. Of course, they aren't just that simple. You can also gain reputations from the villagers (Just like in ToroQuest), and as it grows, you might get something special from them, like a house that they built **just for you**!

That's it for now, in my personal opinion, this is a great mod to add in WOD because it gives the modpack a special seasoning to the mystery World of Dragons. And if you are interested in discovering more about the mod, I will also leave a link to its website page: www.millenaire.org

    Please do consider telling me your ideas and thoughts about the mod, whenever you are positive or negative, they can help me greatly for further more mod suggestions like this. And just ignore some INTERESTING grammaring or spelling errors, I had just begun studying English like 2 years ago, shhh~

**Comment by Draconian4466** [comment]
Mod looks interesting and looks like a good replacement for aw2

**Comment by kreezxil** [comment]
Added that plus the addons.

**Comment by hellwolf95** [comment]
Kree if this is done please tweak its configs as it does do chunloading if not
