### ISSUE TITLE
[please fix] SlashBlades Having Wrong Stats

### ISSUE THREAD

**Issue by Yodown814** [kreezxil/World-of-Dragons#265]
**Describe the bug**
The weapons that I crafted out from the mod **_SlashBlade_** seems to have a different stat than what the JEI showed, so I went to singleplayer and tested them out, it looks like 2/3 of the blades are having the different stat than what it's showing on the JEI(Including the Tinker addon blades).

**To Reproduce**
1. Open your Minecraft game
2. Get a random sword from SlashBlade
3. Compare the stats from the one in inventory and the stats that you saw on the JEI
4. ???

**Screenshots**
https://gyazo.com/f7687de2bc1ac821b7a8862fc906177d
https://gyazo.com/555ac0b1e34f024bf63587a9731a69e7

**Versions:**
 - Minecraft: 1.12.2
 - Forge: 14.23.5.2838
 - Mod Pack: WOD 18.0.210
 - Mod Name: SlashBlade
 - Mod Version: SlashBlade-mc1.12-r25

**Comment by kreezxil** [comment]
fixed by removing tweakers construct
