### ISSUE TITLE
[Server feature request] Morpheus

### ISSUE THREAD

**Issue by JayJay1989** [kreezxil/World-of-Dragons#266]
**Is your feature request related to a problem? Please describe.**
Cant skip the nights on multiplayer server

**Describe the solution you'd like**
% of online players sleep to skip night

**Comment by kreezxil** [comment]
no, not gonna happen, it stops access to overworld night mobs.

**Comment by kreezxil** [comment]
You're not suppose to skip the night. that's the point. if you want to skip
it on a multiplayer server then get a server from
https://bisecthosting.com/kreezxil and install the pack then manually add
morpheus to it.

**Comment by JayJay1989** [comment]
Ok, thanks for the response. 
It was only a feature request. Not a mandate to do it.
And wow that advertising. I'm not interested at all.

**Comment by kreezxil** [comment]
There is nothing wrong with advertising.

**Comment by JayJay1989** [comment]
CLOSE THIS THREAD!

**Comment by kreezxil** [comment]
There's no need for you to scream.
