### ISSUE TITLE
[please fix] Re-Usable morbs Not working

### ISSUE THREAD

**Issue by IppSwitch** [kreezxil/World-of-Dragons#268]
Re-usable morbs despawn after you have used them. Cannot regain them. 

 made a set of 8 Morbs on a tinkers workbench. Turned 3 into Reusable morbs using signalum. 
After capturing 2 sheep and a cow i released them one after the other and lost all 3 Reusable Morbs.

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2838
 - Mod Pack : 18.0.210
 - Mod Name: Thermal Expansion
 - Mod Version: ThermalExpansion-1.12.2-5.5.4.43-universal.jar

Crash Report: Didnt crash
Debug Log: Dont know how to find this.
Latest Log: https://paste.dimdev.org/dipomavutu.md

Edit* Adjusted steps for recreating event.

**Comment by iamweirdie** [comment]
i can also confirm the error exists, i did the same in admin mode. the mobs were released, but the reuseable morbs disappeared.

**Comment by kreezxil** [comment]
@iamweirdie please find the relevation report on Thermal Expansion and
attach the url of this report to it.

**Comment by kreezxil** [comment]
the only option for me is to disable the morb recipes until such time as they become fixed.
