### ISSUE TITLE
[please add] Advanced Chimneys

### ISSUE THREAD

**Issue by iamweirdie** [kreezxil/World-of-Dragons#269]
https://www.curseforge.com/minecraft/mc-mods/advanced-chimneys

This mod gives a beautiful array of chimneys which emanate smoke when proper machines, such as a lit furnace, are attached to them. You can make em tall, you can make em short. The mod author also has chimney vents, so that the chimney need not be directly attached to the furnace. This means you can create the smoke effect without directly placing the furnace next to the chimney, which is great for house builds that want machines away from walls.

This mod is mostly decorative, but it can also be a great marker of who lives where. At night, if a weary traveler stumbles upons somebody's base, they can see an active chimney from a certain distance and think, oh, someone lives in this area.

**Comment by kreezxil** [comment]
ok, added in 212
