### ISSUE TITLE
[please add] Cosmetic Armor Reworked 

### ISSUE THREAD

**Issue by Draconian4466** [kreezxil/World-of-Dragons#27]
# Mod Nominated for Adding*
Mod Name:Cosmetic Armor Reworked 
Mod Link:https://minecraft.curseforge.com/projects/cosmetic-armor-reworked

# Reason for Nomination
it makes it so that you can wear armor and its completely cosmetic and you can also wear armor that's for function

**Comment by kreezxil** [comment]
added to 14.9.141
