### ISSUE TITLE
[please fix] Tinker's Compendium Not Functioning Correctly

### ISSUE THREAD

**Issue by Yodown814** [kreezxil/World-of-Dragons#270]
**Describe the bug**
_Tinker's Compendium_ **IS** working, but there is something wrong with it which causes it not functioning correctly, like for armor materials. It seems like some stats are showing it's original code for the line(??) and has some traits that were never presented in the mod **_Tinker's Construct_**. So I guess they perhaps came from _Tinker's Compendium_. And after going through all the items that the mod had, I didn't really find anything that looks like a guide book, but I did find one item called "Book", and you could open it just like a regular mod guide book, but when I opened it up, the first 2 pages of the book was all blank and the last page of it it's calling out an error. Another thing is that once you crafted the armor from _Tinker's Compendium_, you cannot apply the regular **_Tinker's Construct_** modifiers to the armor, which is weird, but you still can apply modifiers from _Tinker's Compendium_ to them.

**To Reproduce**
1. Open your Minecraft game
2. Go to JEI and search @TinkersCompendium
3. Look through all the items 

**Screenshots**
https://gyazo.com/0258ed9d5e24b0efd36b207d25a4ac5a
https://gyazo.com/7bac2540e6856b7456e7481cb04fa0d4
https://gyazo.com/78e5cac6fcd75c66c0b3c8adfb39dc36
https://gyazo.com/ab42a5e537e18d443c642053e983444c

**Versions:**
 - Minecraft: 1.12.2
 - Forge: 14.23.5.2838
 - Mod Pack: WOD 18.0.210
 - Mod Name: Tinker's Compendium
 - Mod Version: tinkersdefense-1.4.2.28

**Comment by hellwolf95** [comment]
Its likely tinkers compendium is planning on adding in new stuff. Check on there page to see the changelogs and if any new features are coming out

**Comment by Yodown814** [comment]
> Its likely tinkers compendium is planning on adding in new stuff. Check on there page to see the changelogs and if any new features are coming out

It could be, but after checking the Files on the mod page, I found out that the mod we are currently using is on "Beta", which might be the reason why it's not functioning correctly, but just a guess.

**Comment by kreezxil** [comment]
You both are wrong, there is a mod in the pack that adjusts the values of
the materials in the game, especially for tickers construct.If you want a
vanilla experience where mods are in a pack and unconfigured consider
playing the very first version of World of Dragons from three years ago.

**Comment by kreezxil** [comment]
I'll have to delete this file, looks like there are more tweaks in the future.

**Comment by kreezxil** [comment]
I'm removing this mod.
