### ISSUE TITLE
[Config File] Thaumcrafts Quests

### ISSUE THREAD

**Issue by DaredEnemyKilla** [kreezxil/World-of-Dragons#271]
# New Config
**config filename**:
[ftbquests.zip](https://github.com/kreezxil/World-of-Dragons/files/3393718/ftbquests.zip)

## I created a huge questline for Thuamcraft that covers all 7 categories that thaum has in its tutorial book. That being Thaumcrafts Fundaments, Auromancy, Infusion, Golemancy, Alchemy, Artiface, and Eldritch. Each Catagory has around 10-15 quests excluding eldritch that only has 5 cause that's all the content Thaumcraft had for it. I think this would be a great addition to the server.

**Comment by iamweirdie** [comment]
thanks, i'll check this out and see if i can upload the quests :)

**Comment by DaredEnemyKilla** [comment]
awesome

**Comment by kreezxil** [comment]
added
