### ISSUE TITLE
[please fix] glitchy start

### ISSUE THREAD

**Issue by Kriimzun** [kreezxil/World-of-Dragons#272]
when ever you start a world the blocks dont break first try its like being on a multiplayer server but you playing single player

**Comment by hellwolf95** [comment]
Well there is only one fix for this BUY A BETTER PC. The problem with singleplayer is minecraft is not multicore so you are relying on one core to load and process everything in game.

**Comment by kreezxil** [comment]
Exactly @kriimzun that's why we play on servers. A Minecraft server can and
will use a multicore machine whereas as @hellwolf95 pointed out a single
player client will not.
