### ISSUE TITLE
[please fix] Can't enter in the server 

### ISSUE THREAD

**Issue by IceDragonKing** [kreezxil/World-of-Dragons#273]
When I go to Multiplayer the server WOD Major 18 says "Can't resolve hostname"

**Comment by hellwolf95** [comment]
If the issue is still present try resetting your internet or check your fire wall settings.

**Comment by IceDragonKing** [comment]
The issue persist, is the address "kermit.kreezcraft.com" ? Or is there an error?

**Comment by hellwolf95** [comment]
You should not need to change the address. Also make sure you are up to date. Also join the discord so you can get real time help.

**Comment by kreezxil** [comment]
@icedragonking use 199.127.60.214 in place of that address
