### ISSUE TITLE
[please fix] crash when starting game

### ISSUE THREAD

**Issue by pinky108** [kreezxil/World-of-Dragons#274]
**Describe the bug**

**To Reproduce**
1. Go to 'twitch world of dragons'
2. Click on 'play'

**Screenshots**

**Versions:**

 - Minecraft:
 - Forge:14.23.5.2838
 - Mod Pack :
 - Mod Name: world of dragons
 - Mod Version: 18.2.212

**Logs**

**Comment by pinky108** [comment]
i posted the crash log was it too big for the site?

**Comment by hellwolf95** [comment]
Well there is no crash log on this so how can we help determine the crash fix

**Comment by pinky108** [comment]
https://pastebin.com/BfKg4WN2

**Comment by pinky108** [comment]
should i also post the launcher log?

**Comment by kreezxil** [comment]
You have a corrupt pack install. This happens with twitch. Completely
delete the pack, right click and check the box for backups and then click
on "remove". Once it is completely gone, get the pack fresh from Twitch.
simply click on "browse mod packs" type in "world of dragons" and install.
All will be right in the world.
