### ISSUE TITLE
[please fix] crash when it starts

### ISSUE THREAD

**Issue by raydanbob** [kreezxil/World-of-Dragons#276]
**Describe the bug**
 right when the modpack is done loading it crashes

**To Reproduce**
1. Go to modpack
2. Click on play

**Screenshots**

**Versions:**

 - Minecraft:
 - Forge:
 - Mod Pack :
 - Mod Name:world of dragons
 - Mod Version:

**Logs**

Find out how to get me what I need at [What is a Crash Report](https://github.com/kreezxil/World-of-Dragons/wiki/Crash-Reports)

Crash Report: https://paste.dimdev.org/okazodapif.mccrash
Debug Log:
Latest Log:

**Additional context**

**Comment by hellwolf95** [comment]
you need more deditated wam

**Comment by raydanbob** [comment]
Thank you that fixed it
