### ISSUE TITLE
[please fix] Tech Reborn + RS bug.

### ISSUE THREAD

**Issue by IppSwitch** [kreezxil/World-of-Dragons#277]
Tech Reborn MFSU incompatable with Refined Storage Controller. MFSU is taking power from the RS Controller over the Solar panel directly. Power is then NOT being received by the Controller from the Solar panel. Unsure why. Or if it is, it is lower that the amount being drained.|
A Ultimate Solar Panel
Output during day: 1k FE
Output during Night 64.0 FE

Build a controller and MFSU, attach power imput to both from one generator or power source. 
I was using Tech Reborn Ultimate Solar Panel (Pic 1 for original set up.) While these are connected, the MFSU is only receiving 15 FE p/s during Day and about 1-3 FE p/s at night.
The controller being drained by about 20-40 FE p/s even though it says it's only using 6 FE p/s

The only way to resolve this from my testing is to have the MFSU attached to it's own power source. A separate Ultimate Solar panel. No issues happen when this is done. 

**Screenshots**
![Pic 1](https://user-images.githubusercontent.com/38470419/61454712-3cb10980-a994-11e9-9aad-0a85421e1b0e.png)

**Versions:**

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2838
 - Mod Pack : WoD18
 - Mod Name: Tech Reborn  Refined Storage
 - Mod Version: TechReborn-1.12.2-2.22.1.979-universal.jar refinedstorage-1.6.14.jar 

Unsure if there are logs for this. Will edit if informed otherwise. 

I'd love some additional testing done by someone that has more experience than me with this please. 

Edit*: Ok so the issue could possibly be something to do with Day/night cycle. When going to night, there is the reduced amount, but it doesn't return to it's original output during the next day. Will monitor.

**Comment by hellwolf95** [comment]
Try tweaking the sides of your mfsu

**Comment by IppSwitch** [comment]
Attempted to tweak the sides but it seems that all sides aside from the front panel (The dot in the center of it) are all input. The only effect was if you rotate the front panel to the cable it ejects all the energy stored and that rushes into the controller. In this set up, the MFSU is taking ALL the power and none is being received by the Controller. Intake of power is however at the proper 64.0 FE. However i have only had this test platform running for 1 night.
![2019-07-18_22 10 36](https://user-images.githubusercontent.com/38470419/61464474-e4383700-a9a8-11e9-89ad-e1e8459c48d5.png)

**Comment by IppSwitch** [comment]
https://www.youtube.com/watch?v=e5aIqN20ehc&feature=youtu.be

**Comment by IppSwitch** [comment]
It is now In game daytime. The MFSU is pulling 1k FE p/s  but still no power is being diverted to the Controller.

**Comment by kreezxil** [comment]
that video is unavailable, make sure it's public but unlisted if that's
what you want, a private video requires a password

**Comment by IppSwitch** [comment]
Oh, i'll change that now.

**Comment by IppSwitch** [comment]
So after waiting for the MFSU to charge to max capacity, the Controller finally powered up. I don't know why but the MFSU takes ALL the output power for itself until it's full. I have not tested this with other powered blocks.

**Comment by hellwolf95** [comment]
I forgot how i got mine to work but i did have it working on wod17

**Comment by IppSwitch** [comment]
Tech Reborn cables prioritize Tech Reborn Machine blocks over others.

**Comment by kreezxil** [comment]
@IppSwitch if you have posted this on Tech Reborns' issue tracker please grab that link to the report there and put here to help establish the support chain.

**Comment by kreezxil** [comment]
I believe that we came up with solution and determined that this isn't a true bug at all.
