### ISSUE TITLE
[please add] Phosphor mod

### ISSUE THREAD

**Issue by iamweirdie** [kreezxil/World-of-Dragons#278]
https://www.curseforge.com/minecraft/mc-mods/phosphor

This mod adds improvements to the general Minecraft lighting engine, as in computer resource-saving and bug fixing. The mod author also seems to provide a lot of information to back up his claims [even though i havent used the mod yet] but i'm convinced it's worth giving a shot for the sake of optimization. The mod author also provided a compatibility list, and none of the current mods in the pack seem to conflict with the list.

**Comment by kreezxil** [comment]
added
