### ISSUE TITLE
[please fix] terracotta wont stack in furnace

### ISSUE THREAD

**Issue by iamweirdie** [kreezxil/World-of-Dragons#280]
after the clay blocks bake, they dont stack the terracotta, causing the clay to stay there while the coal keeps baking nothing and eventually goes out.

**To Reproduce**
1. Have a vanilla furnace, clay blocks, and some coal
2. cook multiple clay blocks
3. wait for the first terracotta to finish baking
4. watch as the fire rolls away

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2838
 - Mod Pack : 18.3.213

**Additional context**
i needed terracotta for my blockheads kitchen but i didn't have any other furnace available, that's why i was using a vanilla furnace

**Comment by kreezxil** [comment]
does this happen reliably? What is the itemid of the clay you are baking?

**Comment by kreezxil** [comment]
fixed in next version, the problem was tbone library conflicting with custom npcs. the updated changelog says nothing about this fix but it's no longer a problem.
