### ISSUE TITLE
[please fix] lava sigil can place lava in claimed chunks

### ISSUE THREAD

**Issue by jam325** [kreezxil/World-of-Dragons#282]
**Describe the bug**

**To Reproduce**
1. Go to 'a claimed chunk from an other player where you have no permission to build'
2. Click on 'the lava sigil to place the lava'
3. See error

**Screenshots**

**Versions:**

 - Minecraft:1.12.2
 - Forge:14.23.5.2838
 - Mod Pack :
 - Mod Name: bloodmagic
 - Mod Version: 1.12.2-2.4.1-103

**Logs**

Find out how to get me what I need at [What is a Crash Report](https://github.com/kreezxil/World-of-Dragons/wiki/Crash-Reports)

Crash Report: 
Debug Log:
Latest Log:

**Additional context**

**Comment by kreezxil** [comment]
closing this because it appears to be stale now, we were unable to reproduce, and no one else has reported the issue.

Also it is probably an issue with the claiming system or you messed with your claim permissions in a very bad way.
