### ISSUE TITLE
[Crash] Fatal Error -- Llibrary might be the cause

### ISSUE THREAD

**Issue by IppSwitch** [kreezxil/World-of-Dragons#283]
Was doing a World TP/s check with LagGoggles.

Used /Gamemode 3, was traveling from player to player, Did a laggoggles at 
x: -1416 y:64 z: -401
Received Fatal Error. 

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2838
 - Mod Pack: WoD18 18.3.213

Crash Report: https://paste.dimdev.org/qazibeyiji.rb (Please note that Twitch either dates the Crash logs incorrectly, or it takes a day or two for it to come threw. I'm unsure. This log is dated 2019-07-18_16.18.58, but this is NOT when the crash happened. So i do not know if this log is for this particular fatal error. it was the latest in my crash log folder.)
Debug Log:
Latest Log: https://paste.dimdev.org/orewamohim.md 

Edit*: Crash report was delayed. But has been received and added on an additional post.

**Comment by IppSwitch** [comment]
Update*: Logged back into server and recieved this Crash report. 
https://paste.dimdev.org/opodituduy.mccrash

**Comment by hellwolf95** [comment]
What time did you use

**Comment by kreezxil** [comment]
this is not laggoggles, it's llibrary, as that's the only mod mentioned in the trace. 
![image](https://user-images.githubusercontent.com/3880072/61585711-55522880-ab28-11e9-9ae8-a9096043f585.png)

**Comment by kreezxil** [comment]
Ice and Fire has been updated, it's the mod that uses LLIBRARY. There have been no other reports of this. I'm closing it. If it happens again after todays update please file a new report.
