### ISSUE TITLE
[please fix] Mozies mobs masks cause lag

### ISSUE THREAD

**Issue by Cthuwu** [kreezxil/World-of-Dragons#286]
**Describe the bug**
When a player wears a mowzies mobs mask or helm it spikes their s/t to the 240s

**To Reproduce**
1. wear mowzies mobs mask

**Versions:**

 - Minecraft: 1.12.4
 - Forge: 14.23.5.2838
 - Mod Pack :  World of dragons 18.4.214
 - Mod Name: Mowzies Mobs
 - Mod Version:  1.5.4

**Logs**

Find out how to get me what I need at [What is a Crash Report](https://github.com/kreezxil/World-of-Dragons/wiki/Crash-Reports)

Crash Report: 
Debug Log:
Latest Log:

**Additional context**

Not a crash just lag

**Comment by Cthuwu** [comment]
This is Stormdragon75

**Comment by kreezxil** [comment]
added Item blacklist mod to allow blocking this item
