### ISSUE TITLE
The Killer Wormies

### ISSUE THREAD

**Issue by OmegaInferno49** [kreezxil/World-of-Dragons#29]
**Describe the bug**
Some sort of issue with Deathworms, despite being the size of a small pole, can one shot you, despite armor. I bring this up because they were only introduced maybe a couple months ago, maybe 7 even. But realistically, if the mod author did this, why would he make the worms, despite their size, so powerful with health and damage?

**To Reproduce**
All you have to do is approach them with your best gear, and they'll one shot you with a simple bite.

**Screenshots**
Even worms the size of THIS one can one-shot.
https://imgur.com/a/mnYYh9w
Wiki Entry: http://ice-and-fire-mod.wikia.com/wiki/Death_Worm

**Versions:**

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2796
 - Mod: Ice and Fire

**Additional context**
I've done research, and looked all over for any feedback on if anyone has the same problem; no one has reported this issue, nor has there been a Ice and Fire update saying that they were buffed. In fact, in a previous update of Ice and Fire, their damage and health were nerfed. Their health is also high, scarily high, from 650 to the 800's. Giant Deathworms have the health of dragons, being 2048.
With 20 def from Tinker armor, worms can still one shot. In the above picture, that worm one-shot me while I was wearing a full set of Ice and Fire's red dragon armor, a little better then diamond.

Finally, according to the wiki, the deathworm is only supposed to have 10 hp and 1.5 damage, it also depends on size. But not one of these deathworm's stats are even close to this small percentage. All over Ice and Fire mobs display hearts for health, while deathworms show a number, as well as dragons, but for this mod, Dragon's have a reason to be powerful.

**Conclusion**
I'm assuming something in the modpack must've been accidentally tinkered with in the configs, OR, a maybe a mod is somehow adjusting the deathworm's stats.

**Comment by kreezxil** [comment]
I may have jacked their abilities up. I'll adjust the configs. Lots of configs are from major version 13 where people had rampant runaway o.p. armor and weapons.
