### ISSUE TITLE
[please add] Tweakers construct

### ISSUE THREAD

**Issue by Draconian4466** [kreezxil/World-of-Dragons#290]
# Mod Nominated for Adding*
Mod Name:
Mod Link:https://www.curseforge.com/minecraft/mc-mods/tweakers-construct

# Reason for Nomination
Reason:Removing it didn't seem to help with the slashblades issue and with it we can tweak armor values to not have such high defence and with it we can add and remove traits from materials

**Comment by kreezxil** [comment]
I'm not bring it back and I will likely remove more mods.

**Comment by Draconian4466** [comment]
I think the sashblades issue is an issue with the mod itself

**Comment by Draconian4466** [comment]
Also currently a very cheap metal is stronger than manyulin mithril dragon scales and pretty much everything else

**Comment by kreezxil** [comment]
@Draconian4466 where is the cheap metal coming from?
