### ISSUE TITLE
[please fix] MetalChests Upgrades crash you

### ISSUE THREAD

**Issue by iamweirdie** [kreezxil/World-of-Dragons#291]
When a player tries to pick up a MetalChest upgrade from the ground, the player gets kicked and will 

**To Reproduce**
1. Find a dropped MetalChest upgrade
2. Try to pick it up
3. Proceed to yell at your computer as you get kicked
4. Try to login within the radius of the upgrade, keep getting kicked

**Versions:**

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2838
 - Mod Pack : World of Dragons v. 18.5.215
 - Mod Name: MetalChests
 - Mod Version: 5.8.9

Crash Report: https://paste.ubuntu.com/p/vc648MXV4D/
Debug Log:
Latest Log:

**Comment by kreezxil** [comment]
@iamweirdie you're telling me that I should be able to reliably cause this crash by picking up a dropped metal chest upgrade?

If that is the case, I'll attempt to replicate.

**Comment by kreezxil** [comment]
turns out there was nothing you could intercept, the error is an exception thrown on the server.

I captured it tho

https://pastebin.com/LArKR7Bi

**Comment by kreezxil** [comment]
This has been resolved by removing cuisine mod.
