### ISSUE TITLE
[please fix] Unable to download in Twitch

### ISSUE THREAD

**Issue by roonian** [kreezxil/World-of-Dragons#292]
Trying to download the modpack in the Twitch app fails, and gives the message "Object reference not set to an instance of an object"

**To Reproduce**
1. in twitch app, try to install

**Versions:**
 - Mod Pack Version 18.5.215

**Logs**
I would provide logs, however since it is a download error and not a minecraft crashing error, i'm not sure logs will be available

**Comment by kreezxil** [comment]
It's an issue with Twitch. Get MultiMC from https://multimc.org.

Create a new instance
choose import from zip
download that pack from curseforge.com
feed that zip file to the importer
profit

Just the same I'll be releasing an update to the pack in the next 12 hours,
hopefully that resolves the issue.
