### ISSUE TITLE
[please add] Champions

### ISSUE THREAD

**Issue by Draconian4466** [kreezxil/World-of-Dragons#298]
# Mod Nominated for Adding*
Mod Name:
Mod Link: https://www.curseforge.com/minecraft/mc-mods/champions

# Reason for Nomination
Reason: Gives random mobs random effects seems to work good with mine and slash and would replace the mobs created by apotheosis so that module can be disabled cause they are frequently in the red

**Comment by kreezxil** [comment]
added
