### ISSUE TITLE
[please fix] Fireball causes server crash,

### ISSUE THREAD

**Issue by Kaleiomaidus** [kreezxil/World-of-Dragons#299]
When I set the keybind for the fire attack and used it, the whole server crashed. Also, cant be picked up by piggyback item from Tinkers' Construct. Currently using modpack: World Of Dragons 18.6.216 in the official server 

1. Go to 'A kirin mount, then try the fireball attack it has.'

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2838
 - Mod Pack 18.6.216
 - Mod Name: Wings, Hooves and Horses
 - Mod Version: 1.12.2-1.5.16

**Additional context**
Dragon's don't always manage to crash server when using the fireball attack, but sometimes it does.

**Comment by hellwolf95** [comment]
Please limit 1 issues to a issue post.

**Comment by kreezxil** [comment]
inconsistent steps to reproduce means it's not what you think it is, also like @hellwolf95 says, issues should be one per filing.
