### ISSUE TITLE
Mob Spawn Issue

### ISSUE THREAD

**Issue by OmegaInferno49** [kreezxil/World-of-Dragons#30]
**Describe the bug**
Compared to single player and multiplayer, mobs just aren't spawning.

**To Reproduce**
Despite what you do, explore, mine, or sit around, mobs don't seem to be around. Mainly at night, and in cave systems. I've found there aren't just any hostiles, while passives are decently around.

**Screenshots**
Singleplayer: https://imgur.com/a/nUWcH2p
Multiplayer: https://imgur.com/a/Ac0icbd

**Versions:**

- Minecraft: 1.12.2
- Forge: 14.23.5.2796
- Mod: Gravestone mod

**Additional context**
The main mob in the above screenshots seem to be Drowned, blue underwater zombies from the "Gravestone mod". They're all the red dots in the bodies of water; in singleplayer, they spawned instantly when water was rendered, in multiplayer (USA server), they spawned in smaller amounts, and took a couple more seconds to pop up.
The lack of mobs is troubling as I've explored, such as passive mobs needed for leather and meat, or other aggressive mobs, like the regular Minecraft mobs, or now the exclusive deathworm which I see very little of. They were everywhere, despite being said to be 'rare' in the Beastiary, and it's spawn rate was adjusted in a prior update of Ice and Fire.

**Conclusion**
By the looks of it, the mob rate in multiplayer seems to be stunted on a decently big level. This may be due to the amount of Drowned that spawn, or a mob limit being hit in the world? Maybe unused chunks need to be wiped again with the previous plug-in / mod, "Lag'b'gone". The "Possessed Armor" may be another culprit as it's from the same mod, and they were shown to be the only one's spawned in the above screenshot.
(Don't worry, the torch was placed after they were already there, and during a server lag spike.)

**Comment by kreezxil** [comment]
ok, removing the crystals mod and further change spawn rate of mobs from gravestones literally allowed regular mobs and those from other mods to spawn!
