### ISSUE TITLE
server crash or some shit

### ISSUE THREAD

**Issue by LordThumbsquah** [kreezxil/World-of-Dragons#300]
https://paste.dimdev.org/utiyileyed.mccrash

**Comment by hellwolf95** [comment]
This is something about about a grenade launcher projectile being ticked. So the mod causing the crash would be open turrets. Try to see if it crashes again upon the grenade launcher firing

**Comment by hellwolf95** [comment]
If it does we can disable it/ban it from the server to keep others from having crashes

**Comment by kreezxil** [comment]
ADMIN please use the tools that I gave you to find and eliminate the ticking item in this crash report. then amend this report to say that you fixed it.

**Comment by kreezxil** [comment]
I think some other admin or player fixed the issue because there were no turrets, I deleted one chunk anyways. i'm closing this.
