### ISSUE TITLE
[please fix] chunk with bad grenade launcher

### ISSUE THREAD

**Issue by iamweirdie** [kreezxil/World-of-Dragons#301]
**Describe the bug**
2 players have reported making a chunk unable to enter. Their last activity was building a grenade launcher turret.

**To Reproduce**
I will ask them to comment in this github, however, i've tried to enter their chunk located at
<img width="128" alt="Kurter's Position" src="https://user-images.githubusercontent.com/34356883/62602334-60d37c80-b8a8-11e9-9c01-10d7f5d6b880.PNG">

**Versions:**

 - Minecraft: 1.12.2
 - Forge:14.23.5.2838
 - Mod Pack : World of Dragons 18.6.216
 - Mod Name: [possibly] OpenModularTurrets
 - Mod Version: 3.1.3-355

**Logs**

Crash Report: https://paste.dimdev.org/onuwulubak.rb
Debug Log:
Latest Log:

**Comment by kreezxil** [comment]
did you bother to fix their chunks like I've shown you before using
NTBExplorer?

**Comment by kreezxil** [comment]
unable to duplicate

not to ADMIN if players are high as kite, wait until they come down from the near fatal drug overdose before championing their bug report.
