### ISSUE TITLE
[please fix] Crashing on crafting ANYTHING

### ISSUE THREAD

**Issue by Dejavroom** [kreezxil/World-of-Dragons#305]
**Describe the bug**
After picking up a Tulip, I now crash when I craft any item, Including vanilla. Crash report states unknown and I have 3 Crashlogs to go with these crashes.

**To Reproduce**
There is no way I am aware of to reproduce this problem as the crash logs upon crashing out of my server is stated as "Unknown" and provides me with a link to the crash report. However I am not a coder and have no idea what these logs are providing me with.

**Versions:**
 - Minecraft: 1.12 (modded)
 - Forge:  forge-14.23.5.2838
 - Mod Pack 18.6.216:
 - Mod Name: Unknown
 - Mod Version: Unknown

**Logs**
Pastebin Crash Reports here:
1) https://paste.dimdev.org/tisiqazixe.mccrash
2) https://paste.dimdev.org/hakizucamo.mccrash
3) https://paste.dimdev.org/oyidodosoh.mccrash

Crash Report: NA
Debug Log: NA
Latest Log: https://paste.dimdev.org/oyidodosoh.mccrash

**Additional context**
I have 0 idea on what is causing this and have no way of reproducing it aside from logging back into my server, And Crafting any item, vanilla or otherwise.

**Comment by hellwolf95** [comment]
Are you clicking the green book. Also are you using your inventory or crafting table for crafting

**Comment by kreezxil** [comment]
did you bother to modify your screen size at all?
 ```
Screen size: Scaled: (640, 339). Absolute: (1920, 1017). Scale factor of 3
```
I'm confused that the scaled size is 640 x 339 when your monitor can do 1920 x 1017 at least. Try changing the size of the client and see if that helps. I'll try and see if a tulip will cause me the same problems.

**Comment by kreezxil** [comment]
@Dejavroom actually please update your server and client to build 217, I removed apotheosis for a reason and also a lot of the updates in 217 resolve a smack ton of issues one of which is this issue right here because I added "no more recipe book". 

I'm closing this because you are now on an unsupported version of the pack.
