### ISSUE TITLE
[Config] Fix for the Gelum aspect

### ISSUE THREAD

**Issue by lagonnebula** [kreezxil/World-of-Dragons#309]
# New Config
I Added ModTweaker 4.0.17 ( and it depency MtLib) which is a mod that add support into CraftTweaker from some mods ( like thaumcraft )

And Added a script file :
`<minecraft:ice>.setAspects(<aspect:gelum>*2);
<minecraft:packed_ice>.setAspects(<aspect:gelum>*8, <aspect:aqua>*4);
<minecraft:snowball>.setAspects(<aspect:aqua>*8);`
(Value are random ! )

And regenerated the thaumicjei_itemstack_aspects.json
 
## Why we should use it
Removing the quest that create Gelum.

**Comment by hellwolf95** [comment]
So what exactly is the point of this post

**Comment by lagonnebula** [comment]
basicly fixing an issue that override aspect for minecraft item with the Ice And Fire mod

**Comment by kreezxil** [comment]
they posted this to me in private, I told them to post it here so I can
have a record of it when I update the pack next time.

**Comment by kreezxil** [comment]
added in today's build 220.
