### ISSUE TITLE
Dragons can break graves

### ISSUE THREAD

**Issue by OmegaInferno49** [kreezxil/World-of-Dragons#31]
**Describe the bug**
I've heard other people complain about dragon's breaking graves, and I've experienced it with myself, multiple times. Thankfully Tinker tools and armor has some sort of indestructibility when on the ground, but for other items like books.. not so much.

**To Reproduce**
Have a dragon walk over a grave, and most of the time, it'll stomp it as well as other blocks, breaking them and breaking the grave in the process.

**Screenshots**
![NoGrave](https://imgur.com/a/hhkDp2u)
As you can see here, there's no graves, there's no items. The only item I picked up is a bolt that I had on me. A fire dragon used it's fire attack on me, instantly killing me in my best armor of 20 def, and destroyed every single item I had on me. Breaking the grave and destroying my tinker tools and armor, forcing me to make them all again with the spare material and expensive material I have extra. This happened recently, today, when I was in them middle of battling a dragon when the server crashed, and another one joined it and torched me down.

**Versions:**

- Minecraft: 1.12.2
- Forge: 14.23.5.2796
- Mod: Gravestone mod

**Additional context**
It seems that their fire attack can go through maybe blocks, as I was behind a hill when I came back to retrieve my stuff, and the dragon was about give blocks away, on the other side. I could tell by the neutral entity on my minimap, as nothing else was nearby. Passives would be killed by the dragons, the guards don't show on the minimap..

**Comment by kreezxil** [comment]
In order to fight lag we have turned off the dragons' ability to break blocks and dig when stuck. This also solves the issue with graves.
