### ISSUE TITLE
[feature request] Changing Tinkers Armor Values

### ISSUE THREAD

**Issue by Don-Silver** [kreezxil/World-of-Dragons#310]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when, entire materials are banned instead of editing/fixing the problem.  

**Describe the solution you'd like**
The addition, and then subsequent removal of Tweakers Construct. The changed vales stay, even without Tweakers Construct still installed. By adding this mod momentarily, and changing the values you can unban those materials. I am ready and willing to go through the configs and change the values, I am have already went through all Tinker's Armor values and highlighted the problem children. I have Tweakers Construct on my client, and would make the necessary config changes for you, to alleviate time and effort on your behalf.

If there are any other values you would like me to change, IE:Toughness, Mining Speed, Attack, please let me know.

**Additional context**
[Attached](https://docs.google.com/document/d/1lJH33rcBrIJpq-SUN1YvGGX0GG1SfF2xb1unpUicqvM/edit?usp=sharing) is my google doc with the list of ALL **BASE** armor values from tinkers armory.

**Comment by kreezxil** [comment]
this mod has long beed readded and I heavily nerfed all the tinkers values. IMO tinkers should've never been added to the pack.
