### ISSUE TITLE
Game crashing after starting the game

### ISSUE THREAD

**Issue by Kulovicz** [kreezxil/World-of-Dragons#311]
Crashing after starting the game

**To Reproduce**
1. Go to Twitch app
2. Click on play modpack
3. Click on play in minecraft launcher
4. See error log with fatal error  : 
[crash log.txt](https://github.com/kreezxil/World-of-Dragons/files/3515546/crash.log.txt)

This problem occurs on every modpack I install trough Twitch app with version 1.12.2.
Im unable to find solution anywhere.

**Comment by hellwolf95** [comment]
Please us things like pastebin to post your crash log here. It makes it 100x easier and doesnt require is to download any thing

**Comment by hellwolf95** [comment]
Also your minecraft itself is corrupted redownload and try again.

**Comment by Kulovicz** [comment]
here is crash log : https://pastebin.com/Ljf7Zfn9
Also repairing or total uninstalling of Minecraft or Twitch did not help.

**Comment by Kulovicz** [comment]
Nevermind, after restart and again unistalling Minecraft and Twitch, the game seems to work perfectly. Thank you for your help.

**Comment by kreezxil** [comment]
please close your reports when you have discovered it's you and not us.
