### ISSUE TITLE
[please add] MMO Style Mod suite (friends, merchants, mailing, and camps)

### ISSUE THREAD

**Issue by AzureZhen** [kreezxil/World-of-Dragons#314]
Mod Name: Oxygen mod suite
Mod Link: https://www.curseforge.com/members/austeretony/projects

Reason: 
Gives a social experience that would be expandable across different WOD servers. Friend lists are client side and thus you can see your friends on other servers. The mail allow players a safe way to send items to other players. Currency/Exchange/Merchants would allow for an Admin controlled shop system and players to trade in person safely.

**Comment by kreezxil** [comment]
this will be added to build 224, I'm building Bane of Dragons 1.12.2-1.0.1 now and this suite is being added to it as I type now.

**Comment by kreezxil** [comment]
this was done so yesterday, well last week
