### ISSUE TITLE
Tinkers armor + entity dmg testing. 

### ISSUE THREAD

**Issue by IppSwitch** [kreezxil/World-of-Dragons#316]
Tinkers armor makes Entity damage minimal if not non-existent. 

For that instance i was wearing
  - Adv Alloy Helmet (8 armor; 50 defense)
  - Adv Alloy Pants (15 armor; 50 defense)
  - Emerald Jetpack (4 armor; 0 defense)
  - Slime Boots. (0 armor; 0 defense)

Total - 27 armor; 100 defense

Second time i took damage was from a lvl 75 fairy. It was hitting me for 1 damage.

I tested the dragons again wearing nothing. and was taking a total of about 35-45 dmg per hit. 
I survived 4 hits in total before dying and was actually able to take off about 50 health from dragon (fists lol). 

Note*: While testing this i went to spawn in some advanced alloy armor and noticed that my armor (Unmodified helmet) Was 8 Armor 50 Defense vs current build Helmet, 3.6 armor and 22.5 defense. Re-testing with new flat armor. 
![Items](https://user-images.githubusercontent.com/38470419/63993236-1f8a6180-cb22-11e9-8e12-7f94d5a66bd8.png)

So on a final test using Unmodified Up-to-date armors from tinker from build 223.
Total armor = 22.5 armor; 90 defense
Total damage per hit (physical) - 2-5
Total damage per tick (Fire) - 1

I am unsure as to why with less overall rating on my armor i took less damage but this is how my testing went. 
At first i though it was a bug, now i believe it's simply too powerful for the current mod map. 
I believe either Removal or Tweaking is required.

**Comment by hellwolf95** [comment]
The tinkers stuff is likely going to be removed in the future

**Comment by kreezxil** [comment]
i blame it on all the tinkers' addons for now.

**Comment by kreezxil** [comment]
i figured it out, but it's too late and I found other reasons to get rid of the tinkers suite of mods.
