### ISSUE TITLE
Vending Block

### ISSUE THREAD

**Issue by Cthuwu** [kreezxil/World-of-Dragons#32]
# Mod Nominated for Adding*
Mod Name: Vending Block
Mod Link: https://www.curseforge.com/minecraft/mc-mods/vending-block

# Reason for Nomination

Reason: I believe the pack needs some kind of player market/trade system and with conjunction with waystones it can be done with the global setting when placing one down, r=the trade system would add a buy and demand without the need for a standardized currency.

**Comment by kreezxil** [comment]
I'm not a big fan of that mod, but I will give Economy Inc. a shot.
