### ISSUE TITLE
Mine Colonies Guard Tower Crash

### ISSUE THREAD

**Issue by IppSwitch** [kreezxil/World-of-Dragons#320]
A hired guard for the Guard Tower would attack a target with a ranged attack (bow) and the server would crash each time. 

Build a Mine Colonies Guard Tower. 
Hire a Guard
Should crash when either melee or ranged guard attacks. 

 - Minecraft: 1.12.2
 - Forge:  forge-14.23.5.2838
 - Mod Pack: 18.13.223
 - Mod Name: Minecolonies
 - Mod Version: minecolonies-1.12.2-0.10.348-RELEASE-universal.jar

Crash Report: https://paste.dimdev.org/kilifusipa.mccrash
Debug Log:
Latest Log: https://paste.dimdev.org/becidexupo.md

**Comment by hellwolf95** [comment]
Well what weapon are you giving them

**Comment by IppSwitch** [comment]
This is with both a normal bow and a wooden sword.
Both guard types caused the servers to crash.

**Comment by kreezxil** [comment]
please cross post this to the minecolonies team, make sure to paste a copy
of github url from there for the issue to here.

**Comment by IppSwitch** [comment]
https://github.com/ldtteam/minecolonies/issues/3820

**Comment by kreezxil** [comment]
that br to the ldteam says it's fixed.
