### ISSUE TITLE
ice and fire dragons not spawning

### ISSUE THREAD

**Issue by galixywolf13** [kreezxil/World-of-Dragons#321]
I've even gone into single player worlds and messed with spawn rates, I set it to 1 and only got a lot of snowy villigas. or set it to max at like 9000 but still no dragons, underground or above ground. I have no idea what to do, but they dont spawn naturally at all.

**Comment by Drakyl** [comment]
Can you copy your ice and fire config to pastebin and give us the link please.

**Comment by kreezxil** [comment]
by default you must travel 512 blocks before seeing any dragon or mythological creature. In M19 coming today, you will have to travel 2500 blocks from spawn to find one.
