### ISSUE TITLE
[Please Fix] Anti-Spawner Camping too aggressive

### ISSUE THREAD

**Issue by andr9528** [kreezxil/World-of-Dragons#323]
**Describe the bug**
When going near a spawner that previously has spawned 10 or more mobs, the mod Anti-Spawner Camping spawns a seemingly invisible primed TNT on the player, without any prior warning, of eminent "Death".

This does fit with what the mods should do, but i fell like it is missing a warning. On top of this i fell like the spawner should be approachable given some time to "cool off", which i do not fell like it does right now, rendering Despawning Spawners redundant, as no player can stay within the 16 block range needed for them to spawn, without dying.

This is especially a problem with blazes as their primary source are from the spawners in nether fortress'.

To fix this i have a few possible ways, some can be done simply via configs, the other requires changes to Anti-Spawner Camping.
- Nr 1. Remove Anti-Spawner Camping BUT heavily lower the amount of mobs spawned before the spawner Despawns. Down from 100 mobs to like 20. this would mean spawners would be a boost to loot/exp, while still forcing the player to explore.
- Nr 2. Introduce a few second grace period with a warning, before the TNT is spawned on the player. Doing this there should also be introduced a cooldown on when a spawner becomes approachable again, so as to not make Despawning Spawners redundant

**To Reproduce**
1. Go to a Spawner, eg a Blaze spawner
2. Wait for it to spawn 10 or more mobs
3. Die horribly to TNT spawned on player without warning

**Versions:**
 - Minecraft: 1.12.2.
 - Forge: 14.23.5.2847
 - Mod Pack: World of Dragons, Version: 18.14.224

**Additional context**
As the minecraft gamepedia states, as players needs to be withing 16 block of the spawner for it to spawn, but due to the Anti Spawner Camping radius being 20 blocks, it is impossible to get close for it to spawn, without dying to the tnt
https://minecraft.gamepedia.com/Spawner

**Comment by andr9528** [comment]
Instead of punishing the player for grinding a Spawner, maybe the difficulty of spawned mobs could scale with total amount spawned, This would make it still possible to grind them, at an increasing difficulty, until the spawner despawns when it is "out of mobs". Making them harder, would also mean it is not something done for extended period of time to get gear as they would be too difficult to kill without good gear beforehand, but would allow the player to get items like Blazerod a bit easier.

**Comment by hellwolf95** [comment]
Here is a better solution. Mob spawners spawn 1 mob and break. 


The reason this mod is in is so that certain players stop building mob farms. The farms lead to reduced mobs on the server making it hard for others to level up. If you on singleplayer or your own server tweak it to your liking. Other then that players should be punished for mob grinding spawners. It defeats the spirit of the pack as a whole. The pack is about exploring and fighting dragons not camp a zombie spawn for loots.

**Comment by kreezxil** [comment]
this mod is shipped disabled now. turn it on your server if you find players camping mob spawners and thus causing lags or essentially cheating the M&S mechanic via that action.

Turn it on in Single Player for a great challenge.
