### ISSUE TITLE
Twitch stuck on loading... when launching profiles temporary fix

### ISSUE THREAD

**Issue by WolfBV** [kreezxil/World-of-Dragons#329]
https://www.minecraftforum.net/forums/support/java-edition-support/2985317-attempting-to-launch-minecraft-using-twitchs

**Comment by hellwolf95** [comment]
This is a twitch problem and doesnt concern the mod pack as the github is for actual WOD issues or suggestions.

**Comment by kreezxil** [comment]
i told him to post it here
