### ISSUE TITLE
[please fix] The staff of Rending

### ISSUE THREAD

**Issue by daodragon** [kreezxil/World-of-Dragons#33]
AbyssalCraft's Staff of rending and its subsequent upgrades does not harvest energy from abyssal mobs even tho it damages them and kill them.

to collect energy from the staff you right click with the staff in your hand and the crosshair on the abyssal mob

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2806
 - Mod: WOD 14.10.142

**Comment by kreezxil** [comment]
Btw, where it says mod, it's not asking for the modpack version.

**Comment by kreezxil** [comment]
Resolved by removing scaling health.
