### ISSUE TITLE
mounting animals now doesn't function

### ISSUE THREAD

**Issue by TDudes** [kreezxil/World-of-Dragons#330]
**Describe the bug**
With the last update from V. 18.13.223 to V. 18.14.224 mounting animals now doesn't function and you will bounce back and force between trying to mount and one out of may 10-100 tries will allow you to ride mobs.

**To Reproduce**
Right clicking a tamable mob (I mainly used horse) in V. 18.14.224

**Screenshots**
Cannot be given as it will just bounce you from trying to mount to not mounted (even tamed mobs) without any animation.

**Versions:**
Mod pack: V. 18.14.224

**Logs**
Doesn't produce any error logs that I have found.

Crash Report: 
Yet again doesn't produce any logs

**Additional context**
I went back to the last update so that I can use my mounts.

**Comment by hellwolf95** [comment]
Provide debug logs then. As we can at least read that and try to help.

**Comment by TDudes** [comment]
I would love to provide a debug log, But when ever I use the /debug start command It states "starting profiling", and then after doing the action and typing /debug stop it only tells me that It cannot stop what it hasn't started.

If you think that this isn't worth it close the bug report, as I'll just be playing on the older version, as It seems that even upping my RAM to 10+ GB of RAM doesn't have any effect on this or to get the debugging report to function.

**Comment by hellwolf95** [comment]
Thats not a debug log. The debug log is made as soon as you start minecraft and logs every bit from forge failing to load something to minecraft taking to long to respond.

**Comment by kreezxil** [comment]
the debug.log is found in the same location that the latest.log is found in the "logs" folder.

You get there by opening the profile for World of Dragons, by left clicking the icon, not the purple play button. On the next screen click on the "sprocket"/"gear" icon in the upper right corner, and then choose "open folder" now find the "logs" folder, open that and send us the two files we've described.
