### ISSUE TITLE
Spawned underground on new server

### ISSUE THREAD

**Issue by Paladin1979** [kreezxil/World-of-Dragons#331]
**Describe the bug**
After logging in to the new server, I spawned underground (254,104,64). interestingly, despite spawning in a solid block, I did not suffocate. Still an annoyance, though.

**Versions:**
 - Mod Pack : World of Dragons, 19.0.225

**Comment by kreezxil** [comment]
FTB Utilities prevents you from suffocating, it's an oversight, I'll fix this if an admin hasn't already.
