### ISSUE TITLE
[Bug] missing textures bug

### ISSUE THREAD

**Issue by mayront** [kreezxil/World-of-Dragons#333]
There is a lot of mixing textures: potions, torches, lit furnaces, redstone, etc

Not much to be done, just create a world and find the items

https://i.imgur.com/RECiMNL.png

**Versions:**

 - Minecraft: 1.12.2
 - Forge: 1.12.2 -14.23.5.2838
 - Mod Pack: World of dragons
 - Mod Version: 19.0.225

4gb ram allocated
8gb ram total

**Comment by kreezxil** [comment]
this could be an issue with the Resource Pack I"ve decided to try.

**Comment by kreezxil** [comment]
you don't have enough ram, but you learned this already. Allocate 6GB and you'll see the textures appear.
