### ISSUE TITLE
Tool: Axe turning to M&S

### ISSUE THREAD

**Issue by IppSwitch** [kreezxil/World-of-Dragons#334]
When creating an Axe Tool, you get the standard axe (stone/iron/ect), but after being used once it is turned into a M&S weapon and is no longer usable as an Axe. It mines slower than if you use your fist. 

The other issue is these axes can randomly turn into Legendary or Mythical level items without having to do anything. 
![2019-09-17_13 04 57](https://user-images.githubusercontent.com/38470419/65013140-6bc00900-d94c-11e9-9624-ebdc837394eb.png)

To Re-create simply make an axe of any type and break a block with it.
It will turn to a M&S weapon after the block breaks.

**Comment by IppSwitch** [comment]
Temp solution : Use Thermal/Tech reborn/Mystical World Tools until fixed.

**Comment by hellwolf95** [comment]
I dont know if this is a glitch on m&s or the axes are in the compat list

**Comment by kreezxil** [comment]
I'm not using a compat list, this is likely in regard to the new code that
I asked AzureDoom to add to auto add all that stuff. Because I told him
it's a true pain to add 1000's of armor, weapons, etc.

**Comment by AzureZhen** [comment]
Fixed in 1.7.3

**Comment by kreezxil** [comment]
just grabbed that update
