### ISSUE TITLE
[please fix] unable to download pack due to missing mod

### ISSUE THREAD

**Issue by kohlth** [kreezxil/World-of-Dragons#337]
**Describe the bug**
cant download pack due to missing mod on curse id 237664

**To Reproduce**
1. try to download the most recent pack version 
2. fail due to mod no longer on curse

**Screenshots**

![issue](https://user-images.githubusercontent.com/28970985/65378936-c1b2ea80-dc85-11e9-96f1-4f1af25a8b4d.PNG)

**Comment by hellwolf95** [comment]
Well this is a twitch issue as all mods currently in the pack are still on twitch. Just wait a bit and try again.

**Comment by kreezxil** [comment]
alternatively uninstall twitch and reinstall twitch and then any packs.

That error can also come from a bad internet connection, not necessary your
service provider, just something bad between you and twitch and curse
simply acting up and mangling data.

I'll delete my profile and see if I can duplicate it.

...

I could not duplicate it, everything installed.
