### ISSUE TITLE
[please fix] cannot cook concrete powder to obtain concrete

### ISSUE THREAD

**Issue by ParsaMT** [kreezxil/World-of-Dragons#34]
**Describe the bug**
 one cannot put a concrete powder block in the furnace in order to get concrete block.

**To Reproduce**
1. get/craft a concrete powder
2. try putting it in a furnace 
3. see error

**Screenshots**

**Versions:**

 - Minecraft:1.12.2
 - Forge:14.23.5.2806
 - Mod Pack :World of dragons 14.10.142 
 - Mod Name:
 - Mod Version:

**Additional context**

**Comment by kreezxil** [comment]
Now that I see it in writing and with a fresh cup of coffee.

You don't bake concrete powder. It's powder. You're just making hot powder
in a furnace. Therefore nothing.

Put concrete powder down and make it come in contact with water or lava.
It'll form concrete just like obsidian and stone is made.

https://minecraft.gamepedia.com/Concrete

**Comment by ParsaMT** [comment]
omg i totally forgot that you dont cook them i guess i played modded for so long that i forgot basic vanilla stuff!

**Comment by kreezxil** [comment]
Concrete was introduced in 1.12.2 so technically it's a new block with a
new mechanic. It threw me at first.
