### ISSUE TITLE
Mod Suggestions for the upcoming WORLD OF DRAGONS - EXTREME EDITION, a pack designed for gaming rigs exceeding 8GB

### ISSUE THREAD

**Issue by goldenfire1300** [kreezxil/World-of-Dragons#340]
# Mod Nominated for Adding*
Mod Name: 
Mod Link:https://www.curseforge.com/minecraft/mc-mods/decocraft

# Reason for Nomination

Reason:
Increased furniture options for decorating houses and vases really add to the fun of modpacks and mods like decocraft or mr. Crayfish's furniture mod do the trick.

**Comment by hellwolf95** [comment]
I personally would like to see this mod in but at the same time I don't. Due to the fact most people barely use the decorating mods we have now besides a select few.

**Comment by kreezxil** [comment]
I had this mod before and it added such overhead that many 4GB players were
no longer able to play.

I can make WOD EXTREME EDITION that would be targeted on at 8 TO 16GB
gamers.

**Comment by goldenfire1300** [comment]
I would totally be down for a WOD extreme edition for higher GB gamers.

**Comment by kreezxil** [comment]
Ok, I start a build on it next month. no ETA.

**Comment by kreezxil** [comment]
@goldenfire1300 I'm still waiting on the rest of your suggestions.

**Comment by goldenfire1300** [comment]
Industrial Foregoing is another great technology mod. Its a good all around tech mod I feel

**Comment by Draconian4466** [comment]
Astral sorcery is a good magic mod

**Comment by Draconian4466** [comment]
Nuclear craft is a cool tech mod that has nuclear stuff

**Comment by kreezxil** [comment]
Nuclear Craft was incomplete that last time I removed it.
Astral Sorcery conflicts heavily with other mods.

Industrial Foregoing plays fair tho. So it's a candidate.

**Comment by daodragon** [comment]
nuclear craft machines are all done, the author is mostly now working on expanding some stuff like creating a fallout effect on the world, where too much radiation will actually corrode the world. it is also pretty much compatible with all tech mods.

**Comment by Draconian4466** [comment]
What mods did astral sorcery conflict with? The only one i can think of is techguns and that only happened to me

**Comment by kreezxil** [comment]
let's not consider adding mods that we know to have issues. if astral had
issues with techguns it likely has issues with other mods. We've installed
nearly all the mods at one time or another. So If I say something has an
issue, then what you should do as someone who wants the mod is not
**challenge me** but instead **go find out** if the mod has any fixes and
has been made more compatible with other mods.

This Extreme Edition is a chance to make a pack that has way more to offer
the 16gb player that doesn't cause them to say "Yeah, Extreme, my ass,
Exteme Piece of Shit ... maybe". We don't want them saying that. So with
this vision for the extreme player i'm gonna be super hard about gets
added. But i'm not going to go out of my way to research every suggestion
either. You guys can do that.

**Comment by Draconian4466** [comment]
Ok

**Comment by kreezxil** [comment]
I would like to point out there is a bloated pack with 75% of the known mods in it called **Dungeons, Dragons and Space Shuttles**. I'm not entirely sure how its becoming popular other than it's bloated to the gills with everything.

I suggest folks try it out and see what they like and what isn't crash there and I'll consider adding it to the extreme addition.

However, it feels like one of those why bother situations.

Considering I'm fixing to compete with all Dragon packs in a way none of them are going to be able to deal with, that includes my packs. And yes, I'm alluding to the WOD-NEW AGE pack.

**Comment by Draconian4466** [comment]
I like Galacticcraft and it dosent seem to crash

**Comment by kreezxil** [comment]
so you want the extreme edition to compete with the "**Dungeons, Dragons,
and Space Shuttles**" pack?

**Comment by Draconian4466** [comment]
well other than that I don't know it has a bunch of mods that we have tried and removed.Techguns did fix the issue with astral sorcery

**Comment by kreezxil** [comment]
ok, this conversation is dead.
