### ISSUE TITLE
Server crash on barbarian raid

### ISSUE THREAD

**Issue by Paladin1979** [kreezxil/World-of-Dragons#341]
**Describe the bug**
The server (WoD 19) crashes as soon as my wife (franciskaf) or I (paladin1979) try to log in (not sure about others)

**To Reproduce**
It looks like a barbarian raid is crashing the server
I was showing my wife (franciskaf) around my colony when a raid was triggered - as soon as she started fighting with one of the invaders the server crashed (or at least, that's what it looked like)
happened again when logging back in. 
I notice that as soon as I log in I get the message "you succesfully defended your colony" and then the server crashes.

I'm aware there were problems with guard towers and/or raids earlier, but I understood those were fixed - so the colony did have guard towers and about 19 colonists (maybe 20 - don't know if this information helps)

**Comment by Paladin1979** [comment]
ok, according to katherine the archers firing are what causes the crash - problem is that because there are still invaders, I can't get near the guard tower to make the archer stop without him starting to shoot at the invaders. Can an admin delete the archer somehow?

**Comment by Paladin1979** [comment]
ok, I managed to log in and fire the archers. problem solved (for now)

**Comment by kreezxil** [comment]
I don't think I would've closed this. When you say it looked like the
server crash, did you get the screen that said a bunch of words and had the
name of a crash report in the middle and then had two buttons? back to main
and get link?

Because I really need get link so i can send this to the Minecolonies
developer.

**Comment by Paladin1979** [comment]
No, I had nothing of the sort or I would have copy-pasted the crash report. I just got the message "server closed" - it was the discord channel that reported the server as crashed. As for reproducibility: I'd probably try setting up a test server and creating a colony with a ranger - not sure what it takes to trigger a raid. I think Katherine was correct that it was the archers firing, but I wouldn't want to try that again on the server people are playing on. (it would be easy enough - the guard tower is still there (set to manual recruit), so it would be a matter of recruiting a ranger, giving him/her a bow and waiting for a raid...)

**Comment by Paladin1979** [comment]
One more detail: I remembered after katherine made her suggestion that the raid started and I thought "oops, I haven't given a bow to my ranger yet" - the problems started shortly after I gave the ranger a bow.
