### ISSUE TITLE
[please fix] magic seeds can’t be crafted(?)

### ISSUE THREAD

**Issue by WolfBV** [kreezxil/World-of-Dragons#342]
![2CCB92A9-3004-469C-B7C5-0443C550E715](https://user-images.githubusercontent.com/47493126/66251967-17b67200-e70b-11e9-9fa3-afe454814412.jpeg)

**Comment by WolfBV** [comment]
Katherine told me to delete all the text so I did.

**Comment by kreezxil** [comment]
so you posted a giant graphic instead. however, ebwizardry guying saying
this sounds oh so stupid, because why doesn't he just release a build that
has the fixed recipe in it?

**Comment by kreezxil** [comment]
fixed in tonite's new version
