### ISSUE TITLE
Unable to find nickel

### ISSUE THREAD

**Issue by LucaMil** [kreezxil/World-of-Dragons#343]
Not sure if this is a bug, I have been playing the modpack for around a week and haven't found any nickel. Not sure if im looking in the wrong biomes or if its found in a different dimension.

**Comment by WolfBV** [comment]
Have you been looking between Y=5 and Y=20?

**Comment by hellwolf95** [comment]
one does not simply find something that spawns about 1 per chunk.

**Comment by T0uchMeSenpai** [comment]
Because nickel is integral to the tech part of the 'magic and tech' thing of the mod. That aside, to make nickel, you need a pulverizer or industrial grinder, throw iron ore in them and get nickel dust to make nickel ingots.

**Comment by kreezxil** [comment]
so what you are saying is that you found a way to make nickel?

**Comment by jam325** [comment]
If you put iron into a pulveriser you get nickel (i think just 25%)

**Comment by kreezxil** [comment]
that counts a resolved, doesn't matter that you can't find the ore.
