### ISSUE TITLE
[please fix] Anti spawner camping doesn't work

### ISSUE THREAD

**Issue by jam325** [kreezxil/World-of-Dragons#344]
1. Go to 'a spawner'
2. Kill mobs
3. see error

 - Minecraft:
 - Forge:
 - Mod Pack <19.5.230>: World of Dragons
 - Mod Name: Anti spawner camping
 - Mod Version:

**Comment by kreezxil** [comment]
how did you know then it was anti spawner camping?

**Comment by jam325** [comment]
i know that anti spawner camping was a thing, but i didn't knew it was removed

**Comment by kreezxil** [comment]
and yet it is added back, sooo... i'm a close this for now.
