### ISSUE TITLE
[please fix] sitting on toilets crash the game

### ISSUE THREAD

**Issue by jam325** [kreezxil/World-of-Dragons#345]
1. craft toilet
2. sit on it
3. see error

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2847
 - Mod Pack : World of dragons (19.6.231)
 - Mod Name: MrCrayfish's Furniture Mod
 - Mod Version:

Crash Report: https://pastebin.com/p2mKuB89

Latest Log: https://pastebin.com/dXUhPiXT

**Comment by kreezxil** [comment]
https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/476

**Comment by kreezxil** [comment]
@jam325 did you reassign to key to something else? if you click on the issue I linked above you can see what the 1.12.2 author is doing and asking.

He wants a screen shot of the key you have assigned to the fart action.
And if possible a video of what happens.

I'd appreciate it if you can go to his copy of the bug report and interact with him directly.

**Comment by kreezxil** [comment]
#361 removed the recipe for now.
