### ISSUE TITLE
I&F Tidal Armor causes tps

### ISSUE THREAD

**Issue by IppSwitch** [kreezxil/World-of-Dragons#346]
Issue with the Tidal Armor (Pants/torso/helmet/gloves/boots) cause the players to produce over 200tps consistantly. 

Find or create tidal armor (any color)
wear armor
Run lag goggles to see tps

 - Minecraft: 1.12.2
 - Forge: forge-14.23.5.2847
 - Mod Pack : World of Dragons 19.7.232
 - Mod Name: Ice and Fire: Dragons in a whole new light!
 - Mod Version: iceandfire-1.8.3.jar

Crash Report: Not sure on what log to use for this.
Debug Log:
Latest Log:

found this on two separate players wearing various colors.

**Comment by Draconian4466** [comment]
This should be fixed in the next i&f update

**Comment by kreezxil** [comment]
and this has been fixed too.
