### ISSUE TITLE
[please fix]create infinite rooms with Wesley's Roguelike Dungeons 

### ISSUE THREAD

**Issue by Draconian4466** [kreezxil/World-of-Dragons#348]
**Describe the bug**
There is a bug/feature in Wesley's Roguelike Dungeons that makes dungeon rooms spawn with a block outside of the dungeon on the corner and you can pick it up and place it down to create a room
**To Reproduce**
1. Go to a dungeon
2. Break the block
3. place it down
4. a room is created

**Screenshots**

**Additional context**
This can be used to create rooms with Wesley's Roguelike Dungeons I am unsure if this can spawn rooms with chests in them but I have tested and in the overworld made a library full of bookcases and a zombie spawner the block can also be picked up infinitely also only takes a stone pick to break

**Comment by kreezxil** [comment]
please post this on the roguelike dungeons tracker and put the tracker url
here so that the two are linked.

**Comment by kreezxil** [comment]
I'll double check that probably I do but still I need you to go post that
on that other guys mod page and like that back to here.

**Comment by kreezxil** [comment]
https://www.curseforge.com/minecraft/mc-mods/wesleys-roguelike-dungeons?comment=78

**Comment by kreezxil** [comment]
I can't use the current 0.8.0 version of the mod as it causes a network connection error

https://www.curseforge.com/minecraft/mc-mods/wesleys-roguelike-dungeons?comment=79

**Comment by kreezxil** [comment]
i'm nominating this for removal simply because of MCREATOR. All of us DEVS know that MCREATOR is shit.

**Comment by kreezxil** [comment]
fixed in todays patch
