### ISSUE TITLE
[please fix] Infinite Durability on crafted items

### ISSUE THREAD

**Issue by Tarlin83** [kreezxil/World-of-Dragons#349]
**Describe the bug**
After creating a copper axe, no durability appears on the item. Using the copper axe on trees or wood does not cause durability ticks or damage to the axe. The exception to this is if you chop leaves or chop a birch tree, then a durability bar will appear and it will take damage. After attacking leaves or a birch tree, then chopping any other type of wood, the durability will still stay the same and will not reduce with each use of the axe.

**To Reproduce**
1. craft a copper axe with 2 sticks and 3 copper ingots.
2. chop any wood from the trunk of a tree, this will activate the tree feller plugin, but will cause no durability to the axe itself to be reduced.
3. Chop leaves or a birch tree, durability will appear and axe will take damage.
4. Continue to chop any other tree, no damage to axe.

**Screenshots**
n/a

**Versions:**

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2847
 - Mod Pack : Major 19
 - Mod Name: Mystical Worlds
 - Mod Version: 1.1.0

**Logs**

*****No crash report****
Crash Report: N/A 
Debug Log: N/A
Latest Log: N/A

**Additional context**
Other players have reported the same issue with other items, but I can not confirm this yet.

**Comment by kreezxil** [comment]
can you get me the modname:itemid of the copper axe?

**Comment by T0uchMeSenpai** [comment]
Some non-vanilla axes have this behavior. You can make a gem axe, it also seems to have infinite durability when used on trees. Probably an interaction with the mod that lets you quickly chop trees.

**Comment by Tarlin83** [comment]
Just saw this, do you still require the item id's of affected items?

**Comment by kreezxil** [comment]
hey there, you realize this is the wod19 issue tracker.

**Comment by Tarlin83** [comment]
Yes, it is a WOD19 issue described above.

**Comment by kreezxil** [comment]
thanks for NOT reporting this to the Mystical World dev all those moons ago, they've lost a lot of time in a chance to fix this. Now we wait from this day forward as I have posted it. https://github.com/MysticMods/MysticalWorld/issues/86

**Comment by Tarlin83** [comment]
You're right, my bad. Lesson learned and acknowledged. Thank you for reporting.

**Comment by duely** [comment]
I would recommend reporting this to the Tree Feller plug-in or whatever it is that you're using, as I don't see any reasonable paths that could cause our axes to behave like this when they are based almost entirely on the Vanilla axe, and we don't touch any of the code that handles damaging items/durability.

**Comment by kreezxil** [comment]
author says its fixed
