### ISSUE TITLE
[please fix] ender dragon doesnt take damage

### ISSUE THREAD

**Issue by ParsaMT** [kreezxil/World-of-Dragons#35]
**Describe the bug**
i tried every possible way to land a single hit on the enderdragon but none of them worked i cant hit him with a sword,bow,shuriken,crossbow, .( yes i have destroyed all the healing crystals)

**Versions:**

 - Minecraft:1.12.2
 - Forge:14.23.5.2806
 - Mod Pack :World of dragons 14.10.142

**Comment by daodragon** [comment]
Kree the dragon is having an hitbox issue. i have no idea why. I am Ra_Chaos_Dragon.

**Comment by kreezxil** [comment]
resolved by removing scaling health
