### ISSUE TITLE
Electroblobs wands cant be upgraded

### ISSUE THREAD

**Issue by Paladin1979** [kreezxil/World-of-Dragons#350]
**Describe the bug**
I have crafted a wand for elektroblobs (novice level) and I have the books to upgrade it from novice to apprentice level and from apprentice to advanced level (are those the right terms? I'm doing this off the back of my head)

Long story short - the books don't work. I've placed them on the arcane workbench from electroblob's and the upgrade just doesn't happen.

this is a major pain because (imho) it takes a LONG time of using the wand before it upgrades by itself (I haven't managed it yet - I was at about 25% once and then I lost the wand and had to start all over again)

**To Reproduce**
Place a novice level wand and the book to upgrade up to apprentice level in the arcane workbench. Press the button to upgrade - there's a sound and animation, but the wand is not upgraded and the book is not consumed.

**Versions:**
Last tried with WoD 19.8.233

**Additional context**
This feels like a compatibility issue with mine and slash - the wands are modified with M&S stats, maybe this causes the upgrade mechanism to fail?

to be honest, the compatibility for the electroblob's wands (damage stats and all) doesn't feel particularly useful - personally at least I don't use them to hit mobs - I use them to cast spells! Maybe this can be fixed by removing the item compatibility for elektroblob's wands? (not the armor! can it be configured to that level?)

**Comment by AzureZhen** [comment]
You have to get the wand fully ready, it doesn't auto level up, you still need to use the books to upgrade it.

The stats do affect the damage of spells though as they are treated as physical. Another dev is working on a proper mod for Mine and Slash and EB Wizardry integration but i have to finish the new stats system which is complex to say the least.

**Comment by AzureZhen** [comment]
Oh another note: if its a dothack weapons from my mod, upgrades are disabled due a bug where it was giving you a EB Wand instead of my weapon with the upgrade. I'm currently working on how to fix this still.

**Comment by Paladin1979** [comment]
not a dothack wand, but I didn't know I had to get the wand ready AND have a book. I'll try to get there and see what happens. Probably not a bug then, though.
