### ISSUE TITLE
[please add]  Oxygen: Trade

### ISSUE THREAD

**Issue by AzureZhen** [kreezxil/World-of-Dragons#353]
Mod Link: https://www.curseforge.com/minecraft/mc-mods/oxygen-trade

Reason:
Adds a new way of trading between players by adding a WoW-like player marketplace. Items are held in the market for a set amount of time. It's a safer way of trading and drives players to earn more currency for use in their colonies and any merchants if you add them once that's updated.

**Comment by kreezxil** [comment]
added
