### ISSUE TITLE
[please add] TechGuns

### ISSUE THREAD

**Issue by T0uchMeSenpai** [kreezxil/World-of-Dragons#354]
# Mod Nominated for Adding*
Mod Name: Techguns
Mod Link: https://www.curseforge.com/minecraft/mc-mods/techguns

# Reason for Nomination

Reason: I will be brief and precise: one, I feel the 'tech' side of the mod is lacking in offensive representation. Magic has, well, various magic books and stuff and melee (could use spartanweaponry but that's a whole different issue) has swords. Plus, the idea of fighting dragons with shooty shooties sounds cool.

**Comment by kreezxil** [comment]
the better question tho is ... will mine & slash behave and not make the
shooty shooties not feel like pea pea guns

**Comment by AzureZhen** [comment]
They would need added as say bows.

**Comment by kreezxil** [comment]
i'm adding them, so let the fun of tweaking begin! start a new issue when balancing becomes an apparent issue
