### ISSUE TITLE
RE: Void Thaumaturge Armor Infusing

### ISSUE THREAD

**Issue by eliotmanny** [kreezxil/World-of-Dragons#356]
I previously posted a bug report stating that you could not craft more than one piece of Void Thaumaturge armor but after further experimentation, you can craft it but both the void armor and the thaumaturge cloth armor have to be the same durability (new) or it will not work.

Same versions as per previous report.

**Comment by eliotmanny** [comment]
To replicate: I don't really know. I repaired the thaumaturge robes (they were damaged when I first tried) and they worked for infusion, and made a new set of cloth pants and they worked too.

**Comment by WolfBV** [comment]
So like how in Thaumcraft 4 infusions will fail when using damaged items

**Comment by kreezxil** [comment]
As I've stated before the only way to fix thaumcraft is to remove it. It's
been abandoned for a year come november 18.

**Comment by kreezxil** [comment]
thaumcraft still not updated, confirmed abandoned
