### ISSUE TITLE
[please fix] get in the bucket mod not working

### ISSUE THREAD

**Issue by T0uchMeSenpai** [kreezxil/World-of-Dragons#357]
**Describe the bug**
Simple: you cannot empty animals in buckets, the bucket empties but no animal is spawned.

**To Reproduce**
1. Find any animal, with an empty bucket in hand.
2. Right click on it, to put it in the bucket.
3. Right click on it again, to empty the bucket.
4. Bucket empties, animal doesn't spawn/appear.

**Additional context**
Nothing to add, it's on WoD 19, version ending in 234. No logs to be had either.

**Comment by kreezxil** [comment]
I've reported this.

**Comment by kreezxil** [comment]
fixed in the new release tonite.
