### ISSUE TITLE
[please remove] divergant underground

### ISSUE THREAD

**Issue by crazedcutegirl** [kreezxil/World-of-Dragons#359]
Mod Name: divergant underground

# Reason for Nomination
Reason: to put it simply this mod does nothing good to add to the game.  From my experiance the mod does the fallowing.
1.  It makes about half the world to be composed of rocks and minerals about 2 to 3 times harder then normal wich on its on is a usefull way to slow down the games progression though I feel like this is kind of a ... poor/artificial way to do it

2 .  It makes all non ore based rocks drop their product as a stone of its type at appoxamatly 2 to 4 per mined block.  Thes are then only used at a 4 to 1 ratio to make their main black type.  This means this is again another way to slow down and extend game progression.

Past these two neither me nor my freind who quite a game with 20 hours in it to remove this mod have found any use for this mod.  Bow if this was all the mod did it eould just be frustrating but there is a theird issue.  

Any and all blaocks that are hardened by this mod have a 75 to 90 percent chance to drop nothing at all.  This here is why I am recomending the removal of this mod as it does nothing useful but does couse harm to play.  Borh me and my freind tested this and neither of us got any level of consistant drop from the mod and as it couses about half of any generated world to be its hardened stone type it makes progression super frustrating

**Comment by kreezxil** [comment]
It's there because World of Dragons is primarily and RPG go slay the
dragons mod pack. I'm making being a base scientist or mage difficult
because you really need to be exploring and gaining your gear that way.
However, I recognize that some player would rather do the science and magic
so that is there. There are some automated mining mods in the pack you can
use those to dig thru the rock faster.

**Comment by kreezxil** [comment]
I'm fairly certain that if I remove this mod it will cause huge holes in the ground too.
