### ISSUE TITLE
[please fix] vanilla swords dont take damage

### ISSUE THREAD

**Issue by Rolli99** [kreezxil/World-of-Dragons#36]
**Describe the bug**
I crafted a vanilla wooden sword and an iron sword an i realized that they dont take damage when hitting entities. I also looked at the description of the item and saw that it doesnt even show the durability of the item. Only if you start mining blocks with the sword you get to see the damage it takes.

**To Reproduce**
Craft a vanilla sword and try hitting entities and mining blocks.

**Versions:**
 - Minecraft: 1.12.2
 - Forge:14.23.5.2806
 - Mod Pack :World of dragons 14.10.142

**Comment by kreezxil** [comment]
resolved by removing scaling health
