### ISSUE TITLE
[please fix] Get in the bucket mod not working

### ISSUE THREAD

**Issue by riskable** [kreezxil/World-of-Dragons#360]
**Describe the bug**
Collecting a chicken in a bucket then releasing it results in no chicken.  You get a regular bucket though!

**To Reproduce**
1. Make a bucket
2. Right-click on a chicken to capture it in the bucket
3. Right click somewhere in the world to release said chicken
4. The chicken-in-a-bucket turns back into a bucket and the chicken is gone forever.

**Versions:**

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2847
 - Mod Pack: World of Dragons 19.11.236
 - Mod Name: Get in the bucket 
 - Mod Version: 1.0.0 (I think?)

**Logs**
Not necessary...  Just try it!

**Comment by Tarlin83** [comment]
This issue has been resolved:
https://bitbucket.org/hardcorshik/minecraft-forge-getinthebucketmod/issues/1/1122-100

Requires update on the server to latest version.
@kreezxil

**Comment by kreezxil** [comment]
It just got cold as hell here. sideways windws, hail and stuff. Satan is
coming to reclaim his world.

I'll update WOD19 today.
