### ISSUE TITLE
TechGuns not grinding in grinder

### ISSUE THREAD

**Issue by TheKents0209** [kreezxil/World-of-Dragons#363]
Revolver in grinder: https://prnt.sc/q1mv3a
SMG in grinder: https://prnt.sc/q1mvdm
Recipe proof: https://prnt.sc/q1mvqq, https://prnt.sc/q1mvw3

**Comment by kreezxil** [comment]
Are you sure it's tech guns? don't you mean myrcrayfish guns?

**Comment by TheKents0209** [comment]
Those are techguns revolver and thompson smg

**Comment by kreezxil** [comment]
ok and which mod's grinder is it?

**Comment by TheKents0209** [comment]
Techguns

**Comment by kreezxil** [comment]
I'm having no issues grinding any of that stuff. I have to ask is that your grinder you're trying to access because it's padlocked to owner only.

![image](https://user-images.githubusercontent.com/3880072/69761514-39d9d880-112d-11ea-9ba9-e5bef2a84daa.png)

**Comment by TheKents0209** [comment]
Yes it is

**Comment by kreezxil** [comment]
I'm willing to bet it's a bug. set the grinder to public, green open padlock and try again.

**Comment by kreezxil** [comment]
did that help @TheKents0209 ?

**Comment by TheKents0209** [comment]
Havent tried yet

ma 2. jouluk. 2019 klo 17.04 kreezxil <notifications@github.com> kirjoitti:

**Comment by kreezxil** [comment]
no response after a month, declaring this stale and fixed.

**Comment by cheesecakegangster** [comment]
i made my own pack and also have this problem so i reckon another mod is causing it

**Comment by cheesecakegangster** [comment]
actually i figured it out: you can grind down new weapons but not ones you picked up from mobs because they're damaged, but you can't see that they're damaged

**Comment by kreezxil** [comment]
Good to know. We'll add this to the wiki.

**Comment by vizthex123** [comment]
Can this be fixed? I wanna scrap all the old guns I've looted....

**Comment by kreezxil** [comment]
Hey, I didn't know you were a player of my pack. It's nice to know a BH
Partner is also a player. I've been working gluteous maximus off on
stabilizing
https://www.curseforge.com/minecraft/modpacks/kreezcraft-presents-mycraft
for multiplayer. I'll put this on the front of the production queue for WOD
and get an update out this week to allow you to grind that stuff.

**Comment by hypergaming4** [comment]
i got the same isue but did everything above and it still wont grind
