### ISSUE TITLE
Hippogryph Mounting and flight

### ISSUE THREAD

**Issue by WarriorDragonPlayz** [kreezxil/World-of-Dragons#365]
Whenever i get onto my hippogryph and try to fly by pressing Space it just flaps around trying to fly but is unsuccecful Then when i try dismount after i moved over 1 block while mounted it it teleports me back to where i first mounted it but the hippogryph stays put in the place where i got off. After trying again it caused my bird to get stuck in a block and i couldn't find her so i searched and say on screen in chat "Hippogryph Sufficated in a Wall". Wasting my rabbit feet and saddle.

**Comment by kreezxil** [comment]
This is an issue with Ice and Fire 1.8.3

**Comment by kreezxil** [comment]
There I referenced the master issue to which the mod author has yet to respond. You can click on the link and ask around there for further assistance.

**Comment by WarriorDragonPlayz** [comment]
Thank you

**Comment by kreezxil** [comment]
#366 is similar to this. While this is newer, the other was at the top, and I got someone investigating there. I'm closing this because of that. This is not forgotten it is simply being followed in a newer report.
