### ISSUE TITLE
Please Fix Unicorn Mod Riding

### ISSUE THREAD

**Issue by WarriorDragonPlayz** [kreezxil/World-of-Dragons#366]
Also furthering my flying problem but with anoghter mod the unicorn mod will not let u ride them even with a  saddle on it just spins your camera around whenever u right click them.

**Comment by Draconian4466** [comment]
this happens with all mounts in this mod including horses

**Comment by kreezxil** [comment]
@Draconian4466 has this been fixed?

**Comment by kreezxil** [comment]
there is no attached issue at the remote place.
