### ISSUE TITLE
[please fix] Tinkers Construct sword no exp

### ISSUE THREAD

**Issue by Rolli99** [kreezxil/World-of-Dragons#37]
**Describe the bug**
This bug could be related to the bug with the vanilla swords not taking damage. My Tinkers Construct Sword doesnt get any exp from killing entities. Another weird thing is that the sword has 18 exp but I dont know where I got them from. 

**Versions:**
 - Minecraft:1.12.2
 - Forge:14.23.5.2806
 - Mod Pack :World of dragons 14.10.142

**Comment by kreezxil** [comment]
resolved by removing scaling health
