### ISSUE TITLE
Can't download World of Dragons modpack

### ISSUE THREAD

**Issue by kubusz34** [kreezxil/World-of-Dragons#375]
Hi. I have a problem. I can't download and install World of Dragons modpack on the twitch app, beacuse when im trying that, im getting this error: Object reference not set to an instance of an object. Other modpacks are working normally. Help.

**Comment by kreezxil** [comment]
This is actually a problem with Twitch. They know about it. I reported it
to them. It's happening with other packs too. If it continues use one of
the alternative launchers such as GD Launcher from https://gdevs.io, AT
Launcher, Multi MC. I recommend GD Launcher.

**Comment by kubusz34** [comment]
Ok. Thanks for the answer. I hope they will fix it :)
