### ISSUE TITLE
World of Dragons needs to be updated, AzureDoom made a change to the config file to allow TechGuns to be compatible with Mine and Slash.

### ISSUE THREAD

**Issue by slashersaul** [kreezxil/World-of-Dragons#376]
# New Config

**config filename**:
**paste url:**

**Comment by slashersaul** [comment]
Bumping just for an update.

**Comment by kreezxil** [comment]
i can understand bumping after a month but after 2 days, especially after I responded with a wall of text on @AzureDoom's own discord channel about how rude that was. And you're not even a donator, you don't have the right to bump something after 2 days. And you're simply lucky that I'm responding to you on the Sabbath.

I'll update this in 24 hours, but not tonite.
