### ISSUE TITLE
[please fix] Discord chat feedback

### ISSUE THREAD

**Issue by purestone9** [kreezxil/World-of-Dragons#378]
![Capture](https://user-images.githubusercontent.com/29181158/75459787-d33ba500-593d-11ea-9cc8-5d3cd767abb0.PNG)
![Capture](https://user-images.githubusercontent.com/29181158/75459830-e6e70b80-593d-11ea-9cd6-0859283d6cea.PNG)

**Comment by purestone9** [comment]
i belive DIsbot and interchat are working together here

**Comment by kreezxil** [comment]
which one is the duplicate? looks like i got two bots talking in the same channel

**Comment by kreezxil** [comment]
this has been fixed
