### ISSUE TITLE
[please fix] GreatWood smoking pipe server disconnection

### ISSUE THREAD

**Issue by daodragon** [kreezxil/World-of-Dragons#38]
When smoking using the greatwood pipe on WOD usa server it causes a server disconnection. i tested on singleplayer mode, i smoked with no problem.

Have Tobacco Pile in your inventory
Have a greatwood pipe in your inventory
right click the pipe and watch as when it tries to smoke the tobacco you will get s server disconnection message.

**Versions:**

 - Minecraft: 1.12.2
 - Forge:
 - Mod Pack WOD 14.13.145
 - Mod Name: Thaumcraft 6
 - Mod Version: 6.1.BETA26

**Comment by kreezxil** [comment]
https://github.com/Azanor/thaumcraft-beta/issues/1629

I'm disabling this on the server pack until there is a fix
