### ISSUE TITLE
[please fix] Missing Recipe

### ISSUE THREAD

**Issue by purestone9** [kreezxil/World-of-Dragons#380]
**Describe the bug**
Resonant Flux Capacitor was missing a recipe

**Screenshots**
![image](https://user-images.githubusercontent.com/29181158/76098128-23da8000-5f86-11ea-8a62-d2aadfe9faac.png)

**Versions:**
 - Minecraft: 1.12.2
 - Forge: 14.23.5.2847
 - Mod Pack 19.27.252
 - Mod Name: Thermal Expansion
 - Mod Version: 1.12.2-5.5.4.43

**Additional context**
I added a recipe on the server using MineTweaker
The recipe is what is in the screenshot

**Comment by kreezxil** [comment]
added in todays patch
