### ISSUE TITLE
[please remove] openmodularturrets

### ISSUE THREAD

**Issue by kreezxil** [kreezxil/World-of-Dragons#381]
https://github.com/OpenModularTurretsTeam/OMLib/issues/19

I have to wonder how far back the issue goes.

I'll keep the mod if the author can fix the issue.

**Comment by Keridos** [comment]
Not an issue in OMT/OMLib, you are using the wrong versions, either 3.1x for both or 3.2x for both, mixing does crash horribly.

**Comment by kreezxil** [comment]
ok thanks, then this will be fixed in todays patch of the pack.
