### ISSUE TITLE
Random freezing which leads to crashes.

### ISSUE THREAD

**Issue by dalekin31** [kreezxil/World-of-Dragons#387]
**Describe the bug**
During play, I will randomly freeze after a seemingly random amount of time playing, resulting in a crash. However the time it takes for this to happen seems to have massively decreased after the new update.

**To Reproduce**

Unsure on how you would go about actually reproducing it, but Light_celestial is have a similar if not the same issue.

**Versions:**

 - Minecraft:  1.12.2
 - Forge: 14.23.5.2847
 - Mod Pack WoD: 20.0.257

**Logs**

Find out how to get me what I need at [What is a Crash Report](https://github.com/kreezxil/World-of-Dragons/wiki/Crash-Reports)

Crash Report:  no report was generated
Debug Log:
Latest Log:
[latest.log](https://github.com/kreezxil/World-of-Dragons/files/4343703/latest.log)

**Additional context**
This time the freeze happened right after teleporting home with the /home command

**Comment by kreezxil** [comment]
hopefully you or someone will add more information to us to help us to find the cause.
