### ISSUE TITLE
[feature request] Incendiary Ammo & High Velocity & Tactical Nuke ammo.

### ISSUE THREAD

**Issue by Aviergence** [kreezxil/World-of-Dragons#389]
I might understand the Tactical Nuke being disabled, but the HV Rockets and Incendiary ammo dont really make sense to be disabled, I think the Incendiary ammo would help alot with the gun toting mobs, same goes for HV Rockets for the bigger mobs like cyber demons. thanks!!! <3

**Comment by kreezxil** [comment]
it's one setting in the config "enableunsafe=false" if I set it to true
everything becomes enabled. And then i'll have to go thru and test each
item to see how unsafe it is and if its bad enough forcefully remove its
crafting recipe.

**Comment by kreezxil** [comment]
turns out the mod author has those disabled, the config i keep going on about enables all the OP level features for normies.
