### ISSUE TITLE
Dragon flight limit

### ISSUE THREAD

**Issue by Malcolmhooi** [kreezxil/World-of-Dragons#39]
so after the last update i noticed the dragon flight limit was lowered than expected , i am not able to go high enough to even pass over a mountain. i believe the fly height limit is too low especially for fully grown dragons.
i hope that something could be done with this and thank u for your time.

**Comment by RunawayRenegade101** [comment]
Yes, i live on a glaicer, and whenever i spawn my dragons out of my horn, they get stuck in the ground. i suggest highering the limit to atleast 50 more blocks.

**Comment by kreezxil** [comment]
Today's update contains this change. Expect it around 12 noon CST (Texas Time).
