### ISSUE TITLE
[please fix] Heli Copter Crashing

### ISSUE THREAD

**Issue by ThaneFenrir** [kreezxil/World-of-Dragons#391]
**Describe the bug**
<Helicopter Causing crash while rendering in! -->

**To Reproduce**

**Screenshots**
<https://imgur.com/a/JY57cqQ       <------ Location> AS SOON AS YOU LOAD IT IT IT COULD CRASH<---------

**Versions:**

 - Minecraft: 1.12.2
 - Forge:14.23.5.2847
 - Mod Pack :
 - Mod Name: World of Dragons
 - Mod Version:  20.0.257

**Logs**

Find out how to get me what I need at [What is a Crash Report](https://github.com/kreezxil/World-of-Dragons/wiki/Crash-Reports)

Crash Report: https://pastebin.com/vqkwxmA1
Debug Log:
Latest Log:

**Additional context**

**Comment by kreezxil** [comment]
we established in Discord this was due to optiFine, why you didn't come back here and close it IDK???
