### ISSUE TITLE
[please add] Simple Storage Network

### ISSUE THREAD

**Issue by ThaneFenrir** [kreezxil/World-of-Dragons#392]
# Mod Nominated for Adding*
Mod Name: 
Mod Link: https://www.curseforge.com/minecraft/mc-mods/simple-storage-network

# Reason for Nomination

Reason: Easier to work with, better than refined storage, no hassle at all to use and deal with!!! Why not keep it simple???? Why complicate your storage matters when all you have to do is link it? Make it easier to do, and enjoy doing it because you didn't have to use sooooo many resources to craft such a small thing!!!! That works and it's way better <--- IMO!!!

**Comment by kreezxil** [comment]
sounds like a plan

**Comment by kreezxil** [comment]
added
