### ISSUE TITLE
[please add] The Disenchanter Mod

### ISSUE THREAD

**Issue by ThaneFenrir** [kreezxil/World-of-Dragons#393]
# Mod Nominated for Adding*
Mod Name: 
Mod Link: https://www.curseforge.com/minecraft/mc-mods/the-disenchanter-mod

# Reason for Nomination

Reason: Allows you to pull enchants off an item and put them on another. Highly configurable to your liking if you don't like how some things are. It'll allow you to put the enchants you want onto and item if you have another item with them that you don't like!

Please Note: It can be configured to allow only 1 enchants to be taken off if you find it OP, RLCraft has it that way if you like it like that.

**Comment by kreezxil** [comment]
this one is actually a good suggestion and unliked cyclic which adds 100's of new models to render doesn't add much as far as bloating goes, I would say at most a skin cell.

also added.
