### ISSUE TITLE
[please add] Cyclic

### ISSUE THREAD

**Issue by ThaneFenrir** [kreezxil/World-of-Dragons#394]
# Mod Nominated for Adding*
Mod Name: 
Mod Link: https://www.curseforge.com/minecraft/mc-mods/cyclic

# Reason for Nomination

Reason: Wireless Power transfer, More power resources, FUN!!! Really just for the wireless power transfer. New tools and items to mess with.

**Comment by kreezxil** [comment]
I took this out in the past to remove pack bloating, if half the players can't log on it's your fault, not mine, you should know better to suggest more mods to already bloated packs.

Also added.

**Comment by kreezxil** [comment]
adding this mod caused the 8gb client memory footprint to be achieved. it's not going to be officially added. you can add it to your private copy. I can't add it because it'll get rid of the remaining 8GB only players.
