### ISSUE TITLE
[please fix] quests not registering items and uncompletable quests

### ISSUE THREAD

**Issue by LightCelestial** [kreezxil/World-of-Dragons#396]
In 'No Iron Chests?!! WTF!!?' there is a quest called 90 Degrees which requires you to craft a cabinet to complete the quest.
![image](https://user-images.githubusercontent.com/62432345/77174625-ba836280-6a97-11ea-9689-5942129b936e.png)
As you see I've crafted the Cabinet, and the quest looks like this,
![image](https://user-images.githubusercontent.com/62432345/77174659-cb33d880-6a97-11ea-8cad-abb0c388e061.png)
The quest will not register the cabinet in your inventory or whenever you craft it. Therefor the quest cannot be completed.
-Next Quest-
In 'Electrobobs wizardry' there is a starter quest that requires you to get a Magic Wand.
![image](https://user-images.githubusercontent.com/62432345/77174836-1221ce00-6a98-11ea-8aa9-9b15bc59e6cc.png)
The wand has no crafting recipe and has been researched to be a Debug item that can only be spawned in. It is also not apart of Electrobobs wizardry.

**Comment by kreezxil** [comment]
in the future, these are two separate issues. make them that way. reason is as I comment that I'm fixing things you can get confused and think it is all fixed.

2nd reason which is really the first reason, it makes it easier on me and others to see what was fixed if each issues has it's own separate ticket.

for example a flat tire and missing rear view mirror while in the same car are not the same issue.

**Comment by LightCelestial** [comment]
Understandable, will keep that in mind when I post more issues I find.

**Comment by kreezxil** [comment]
I've removed the offending and broken quest nodes. so fixed in today's update.
