### ISSUE TITLE
[please add] Nomadic Tents

### ISSUE THREAD

**Issue by ThaneFenrir** [kreezxil/World-of-Dragons#398]
# Mod Nominated for Adding*
Mod Name: 
Mod Link: https://www.curseforge.com/minecraft/mc-mods/nomadic-tents

# Reason for Nomination

Reason: Only if possible, I believe this mod will encourage exploration, and make people move as they want! Allow's exploration to it's full potential!

**Comment by kreezxil** [comment]
that would be nice.

**Comment by kreezxil** [comment]
added
