### ISSUE TITLE
Weapons & Armor do not scale

### ISSUE THREAD

**Issue by Colinbark25** [kreezxil/World-of-Dragons#399]
So, i recently made some ruby gear and they did not scale to my level, nor do the following mods -(dot-hack weapons, tech-guns, tech-reborn, and any other type of armor) the only armor that does scale is rarity armor, like uncommon.

**Comment by AzureDoom** [comment]
This is being looked into, singleplayer is working so it's something on the server side of things.

**Comment by kreezxil** [comment]
fixed
