### ISSUE TITLE
[please add] Doggy Talents

### ISSUE THREAD

**Issue by LogistikCZ** [kreezxil/World-of-Dragons#400]
# Mod Nominated for Adding*
Mod Name: Doggy Talents 
Mod Link: https://www.curseforge.com/minecraft/mc-mods/doggy-talents

# Reason for Nomination

Reason: I think this mod would add something little extra for animal/dog/wolf lovers. And it could feel RPG-Like being able to level up the dog and have a nice companion for adventures.

**Comment by kreezxil** [comment]
No, the mod is broken, it is not fixed, I've commented on this elsewhere. I have an open ticket there too.
