### ISSUE TITLE
[please fix] you can pick any mob with bucket

### ISSUE THREAD

**Issue by LogistikCZ** [kreezxil/World-of-Dragons#401]
**Describe the bug**
You are able to pick up any mob with just classical bucket.
Just right click it and poof, its in bucket. It works on every mob as it seems, even Dragons.

**To Reproduce**
1) Run World Of Dragons (newest version)
2) Go to MP or SP doesnt matter
3) Take bucket and right click ANY entity.
4) Done, you can pick up even stuff like dragons.

**Screenshots**
https://cdn.discordapp.com/attachments/517427990913744896/692352708136665198/unknown.png

**Versions:**

 - Minecraft: 1.12.2
 - Forge: forge-1.12.2-14.23.5.2847-universal
 - Mod Pack: World of Dragons-20.1.258
 - Mod Name: getinthebucketmod
 - Mod Version: 1.0.1

**Logs**

Find out how to get me what I need at [What is a Crash Report](https://github.com/kreezxil/World-of-Dragons/wiki/Crash-Reports)

Crash Report: none
Debug Log: none
Latest Log: none

**Additional context**

**Comment by kreezxil** [comment]
i fixed this already.

Update to build 20.1.259
