### ISSUE TITLE
[please remove] Vein Miner

### ISSUE THREAD

**Issue by LogistikCZ** [kreezxil/World-of-Dragons#402]
# Mod Nominated for Removal
Mod Name: Vein Miner

# Reason for Nomination

Reason: Client does indeed have Vein Miner mod installed, but its not in server package.
Server and client both have OreExcavation i think the Vein Miner doesnt belong there?

**Comment by kreezxil** [comment]
You're right. Good Catch!

**Comment by kreezxil** [comment]
fixed
