### ISSUE TITLE
[please add] Just enough calculation

### ISSUE THREAD

**Issue by ParsaMT** [kreezxil/World-of-Dragons#403]
# Mod Nominated for Adding*

Mod Link: https://www.curseforge.com/minecraft/mc-mods/just-enough-calculation

# Reason for Nomination

Reason: i think its a very helpful mod as it tell you exactly how many items you need in order to craft something and being able to do that for some of the more complex items in the modpack is kinda good.

**Comment by kreezxil** [comment]
it's not, no one ever used it when i put it in the past.

**Comment by kreezxil** [comment]
I'll prove it to you. I'll ad the stats mod which shows how often a mod gets used by a player.
All add this too.
No one will use it.
Even if you make a video explaining how to use it.
Even if you make signs at spawn to explain how to use it, because Videos ... only Grok does videos.
