### ISSUE TITLE
[please add] /dank/null

### ISSUE THREAD

**Issue by ThaneFenrir** [kreezxil/World-of-Dragons#404]
# Mod Nominated for Adding*
Mod Name: 
Mod Link: https://www.curseforge.com/minecraft/mc-mods/dank-null

# Reason for Nomination

Reason:  You  ever wish you didn't have all that damn stone in your inventory after mining? Instead of having to throw it on the ground or trash it you can just make a /dank/null! Just put the item you don't want into it and every time you pick it up it'll get rid of excess!

**Comment by kreezxil** [comment]
fair enough
