### ISSUE TITLE
[please add] Bewitchment

### ISSUE THREAD

**Issue by ThaneFenrir** [kreezxil/World-of-Dragons#406]
# Mod Nominated for Adding*
Mod Name: 
Mod Link: https://www.curseforge.com/minecraft/mc-mods/bewitchment

# Reason for Nomination

Reason: Fantasy, RPG, Fun... You can pick what you want to be! A werewolf? A vampire? Demonic worship? You pick and choose your style. Slaying vampire's and werewolf's to your liking? Or you could worship demon's and summon them! Magic to poppets, mischief to shenanigans. ( Just an all around fun and enjoyable mod people could enjoy ) ( Also is a successor to Witchery ) ( If you've ever played it )  ( Only If possible Just thought I'd put it here to see whatcha think )

**Comment by kreezxil** [comment]
added
