### ISSUE TITLE
[please add] Inventory Pets

### ISSUE THREAD

**Issue by LogistikCZ** [kreezxil/World-of-Dragons#411]
# Mod Nominated for Adding*
Mod Name: Inventory Pets 
Mod Link: https://www.curseforge.com/minecraft/mc-mods/inventory-pets

# Reason for Nomination

Reason: This mods adds pet to your inventory, each pet does have its own abilities. As far as i know the mod is fairly configurable so you can disable certain pets for balance.
Adds nice touch to the game of having your pet for what you want.

**Comment by ThaneFenrir** [comment]
I will say this now, this has a 0% chance of being added! It's to op, sure you can configure and take out the things you dont like but overall this mod can be extremely over powered! Kree if you read this the only way this mod should be added to the pack is by disabling the "purplecow,

**Comment by kreezxil** [comment]
no, i will not add this. the pack is begging to bloat hard. already it's limited to 8gb+ rigs.
