### ISSUE TITLE
[Please Fix] EBWizardry x Thaumcraft conflict

### ISSUE THREAD

**Issue by Aviergence** [kreezxil/World-of-Dragons#415]
there is a part of the thaumcraft questline in the Thaumonomicon, it requires you to be shot by a fireball from a blaze/ghast/or fire charge, however due to a config in EBWizardry, the fireballs arent vanilla and it causes a conflict, there is an easy fix however.

change "replaceVanillaFireballs" to false in ebwizardry config

**Comment by kreezxil** [comment]
nice

**Comment by kreezxil** [comment]
fixed
