### ISSUE TITLE
[please fix] Triple Meat Treat not craftable

### ISSUE THREAD

**Issue by rwatson1** [kreezxil/World-of-Dragons#421]
**Describe the bug**
The triple meat treat from Thaumcraft recipe does not work.  I did some research and found that this issue is not just WOD but is a Thaumcraft issue.  Others posted the problem and some solutions on the Thaumcraft gitHub, here:
https://github.com/Azanor/thaumcraft-beta/issues/697

![ThaumBrokenRecipe](https://user-images.githubusercontent.com/63328364/78737577-7ad0cd80-7915-11ea-97be-2ed63c3d016f.PNG)

**Versions:**

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2847
 - Mod Pack 21.5.262
 - Mod Name: Thaumcraft
 - Mod Version: 6.1BETA26

**Comment by kreezxil** [comment]
and thaumcraft is dead too, read about it here:
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1292130-thaumcraft-6-1-beta26-no-longer-being-developed

**Comment by Onikage056** [comment]
That's a shame... Thaumcraft is probably the first magic mod I actively got involved in when I started playing modded MC. (The second was Botania.) Won't stop me using the mod, though.

**Comment by rwatson1** [comment]
That's very unfortunate. Is there anything that can be done to remedy the issue? There's only one recipe it's used for, so it's not a big deal.

**Comment by kreezxil** [comment]
after looking at this and studying it, I am not at sure how you managed to get the recipe to show in JEI. I would venture to say it was disabled for a reason. It is understood in the modding community that non-recipe-enabled items are meant for beta testing, not something that is in general an oopsy and should be made available to the player.

However, I have added a set of recipes that exposes the triple meat treat. We'll see how things go from there.

**Comment by rwatson1** [comment]
I thought it might be disabled and was going to ask if anyone knew why it might be, but did my own research and saw that it was a problem in other instances of Thaumcraft. It is also available as a quest reward, which furthered my belief that it was a bug, not a blocked recipe.  I will try them tonight, thank you!
