### ISSUE TITLE
/dank/null Inventory Randomized and Jumbled and Crash

### ISSUE THREAD

**Issue by defranke00** [kreezxil/World-of-Dragons#423]
**Describe the bug**
It all started after I executed April 9th's update from 21.5.262 to 21.6.263. I initially tried updating through Twitch. This caused Minecraft loader to shut down almost immediately after opening. I installed the GD Launcher next, finally getting fed up with the twitch launcher. This worked and when I logged onto the primary server, everything seemed to be correct. When I looked in my /dank/null Mark VI, I noticed some of the items I had, just minutes before the server update, put into the /dank/null were missing. Many other items were out of place, duplicated, and disappeared among other things, as can be seen in the first screenshot. You wouldn't need more than one slot per item since each slot of the Mark VI can hold 2.1 billion items, and different items are always added right after the last item in the /dank/null, also seen in the first screenshot.
I next thought that perhaps this was caused by switching from Twitch to GD Launcher, that maybe the contents order and organization was housed on the client, much like the journeymap files are stored. I could not find anything to say it was that way. After looking closely at the twitch files, I realized that all of the updated mods were not removed from my WOD instance in twitch whenever I updated. After removing all of the extra (outdated) files, the twitch version did manage to start. My reasoning for going back to twitch was that perhaps there was a corruption in the GD files, but after launching everything through the twitch launcher, I had the same result as what occurred with the GD launcher.
My next attempt to rectify the problem was to remove everything from my /dank/null and start afresh. Whenever I would attempt to remove an item from my /dank/null it would remove the item that was supposed to be in the slot I selected, not necessarily, and usually not, the item displayed for that slot. So I started the process of removing the tens of thousands of items I had in my /dank/null. After about 3 inventories of items, my client crashed (crash report), and gave two possibilites. 

**To Reproduce**
It seems to be a singular issue. My friend who I am playing with also has a /dank/null Mark VI, and he does not have the problem like I have. We theorised it may have be a corrupted item or player data file within the server.
I have been unable to reproduce this occurance in a single player world, which furthers my belief that it may be a simple corrupt file.

**Screenshots**

![2020-04-09_20 26 44](https://user-images.githubusercontent.com/63429962/78954046-7c7acc80-7aa0-11ea-83a5-a4de8fee7664.png)

**Versions:**

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2847
 - Mod Pack :  21.6.263
 - Mod Name: DankNull and p455w0rdslib
 - Mod Version: DankNull-1.12.2-1.7.91; p455w0rdslib-1.12.2-2.3.161

**Logs**

Find out how to get me what I need at [What is a Crash Report](https://github.com/kreezxil/World-of-Dragons/wiki/Crash-Reports)

Crash Report: [crash-2020-04-09_20.50.07-client.txt](https://github.com/kreezxil/World-of-Dragons/files/4459461/crash-2020-04-09_20.50.07-client.txt)
Debug Log: [debug.log](https://github.com/kreezxil/World-of-Dragons/files/4459466/debug.log)
Latest Log: [latest.log](https://github.com/kreezxil/World-of-Dragons/files/4459469/latest.log)

**Additional context**
In game username: 1WolfsGlory

**Comment by kreezxil** [comment]
thanks for a report that is EXTRA, this how a report should be when no logs
are attached. yes what you describe is corrupted file usually caused but a
file not being fully saved out when a server reboots. /dank/null did update
recently back in build 262. Oh you did get a client crash report. nice. In
the future tho put all reports in https://gist.github.com and then paste
the resulting link. It works like pastebin but is free.

**Comment by kreezxil** [comment]
You can see from these lines that issue lies firmly with dank null but that is client side and it could be upset because the server file didn't update right.

```
java.lang.IllegalArgumentException: Comparison method violates its general contract!
    at java.util.TimSort.mergeLo(TimSort.java:773)
    at java.util.TimSort.mergeAt(TimSort.java:510)
    at java.util.TimSort.mergeForceCollapse(TimSort.java:453)
    at java.util.TimSort.sort(TimSort.java:250)
    at java.util.Arrays.sort(Arrays.java:1438)
    at java.util.List.sort(List.java:478)
    at p455w0rd.danknull.inventory.DankNullHandler.sort(DankNullHandler.java:559)
    at p455w0rd.danknull.inventory.DankNullHandler.onContentsChanged(DankNullHandler.java:596)
    at p455w0rd.danknull.inventory.cap.DankNullCapabilityProvider$1.onContentsChanged(DankNullCapabilityProvider.java:28)
    at p455w0rd.danknull.inventory.DankNullHandler.extractItem(DankNullHandler.java:234)
```

**Comment by kreezxil** [comment]
I am right too, the issue has been reported already at https://github.com/p455w0rd/DankNull/issues/270

**Comment by defranke00** [comment]
Update: I managed to empty all of the contents of the bugged /dank/null. Same issue ocurred when the /dank/null was held by another player. 
Will making a new /dank/null fix the buggy actions of my current /dank/null?

**Comment by Onikage056** [comment]
If you're making a new /dank/null, it should be alright. Unless it's a particularly nasty bug, they don't normally spread beyond the affected item/area/what-have-you.

**Comment by defranke00** [comment]
> If you're making a new /dank/null, it should be alright. Unless it's a particularly nasty bug, they don't normally spread beyond the affected item/area/what-have-you.

Mr Kreezxil up there rolled back the DankNull mod 1 version, so the issue should be fixed by that, I am still using the 'corrupt' item and its working fine now back on the older version. I don't think I had tried the second /Dank/Null before the update, though, I believe it would have worked as it is supposed to. It was just that particular item that was corrupt

**Comment by defranke00** [comment]
Lets see, the most up to date version of DankNull is still having the same issue as the last one. I have not tried moving stuff around in it, so I have not go any crash logs, but this is the same thing that occurred last time.
Versions:
Minecraft: 1.12.2
Forge: 14.23.5.2847
Mod Pack : WOD 21.9.266
Mod Name: DankNull 
Mod Version: DankNull-1.12.2-1.7.94

![DankNull](https://user-images.githubusercontent.com/63429962/79384388-66e82580-7f2c-11ea-9e30-f5a48814c92b.PNG)

**Comment by kreezxil** [comment]
ok, i'll roll it back down again

**Comment by defranke00** [comment]
Update to .270 WOD seems to have fixed the problem with the danknulls not counting properly. One big hiccup though, Any contents of the old danknull's are deleted. Seeing as they weren't working properly, I don't know how much other people lost, but I know a couple did lose a decent bit.

**Comment by kreezxil** [comment]
it's a sad moment in the history of virtual mankind, but it had to be done. The author responsible for mainting dank/null stated it would happen in one of the prior builds.
