### ISSUE TITLE
Changelog says MineColonies minimum distance is 800 blocks but is actually 8k

### ISSUE THREAD

**Issue by Diamond200512** [kreezxil/World-of-Dragons#429]
Minecolonies will not allow the player to place a colony within 8k blocks of spawn while in the changelog says they cant be placed within 800 blocks of spawn.

**Comment by Diamond200512** [comment]
its been fixed on the server

**Comment by rwatson1** [comment]
Just heard from some players that they are still getting a warning when they try to place the town hall that it must be 8k from spawn. They were able to place the supply ship/camp but not the town hall.

**Comment by Diamond200512** [comment]
I changed my config client side and it let me go close to spawn server side

**Comment by rwatson1** [comment]
Oh cool, could you get on wod-bot and help them when you get a chance? Player CielianVorlan, thanks diamond.

**Comment by kreezxil** [comment]
@rwatson1 found a rogue config our own server, updated it. thanks for reporting.

**Comment by rwatson1** [comment]
Fantastic, thanks
