### ISSUE TITLE
[feature request] make colored terracotta recipes easier 

### ISSUE THREAD

**Issue by ParsaMT** [kreezxil/World-of-Dragons#43]
**Is your feature request related to a problem? Please describe.**
in the Mrcrayfish's furniture mod different colored terracotta blocks are used alot and in order to make different colors of terracotta one need a stoked cauldron which is hard to make and takes a lot of time. 

**Describe the solution you'd like**
please change it back to the normal vanilla recipe

**Comment by kreezxil** [comment]
ok, consider it done. Not sure why it isn't because I told bwm to not do hardstuff.
