### ISSUE TITLE
[Mouse Acceleration] Mouse is randomly accelerating

### ISSUE THREAD

**Issue by CalciumDefficient** [kreezxil/World-of-Dragons#431]
When I am in-game and I look around, My mouse will randomly accelerate at random times. I've looked online and tried all methods to stop this from happening, but it seems to reoccur only on this pack. It is just a frustrating little thing that has bothered me once before, but I was able to clear it up. It doesn't matter which direction I'm moving my mouse, the issue persists. But against online scores, reducing my mouse's polling rate actually increases the frequency in which it occurs, and all recommended system settings have been set as well. I'm unsure how to reproduce this, as it seems to only happen on this pack.

**Versions:**
 - Minecraft:1.12.2
 - Forge:14.23.5.2847
 - Mod Pack version:21.11.268

**Comment by LightCelestial** [comment]
Alright, so I've had this problem before with different applications, (Mostly 3rd party applications). If you can check your running apps, and close anything that could be affecting your mouse and keyboard, even if it's a slight possibility, and try loading it up again it might fix it.

**Comment by kreezxil** [comment]
@CalciumDefficient 
We're going to need some more data.

OS Type:
OS Version:
Mouse Model:

**Comment by CalciumDefficient** [comment]
OS type: Windows 10 Pro
OS Version: 1909 
OS Build: 18363.778
Mouse Model: Logitech G502 Proteus Spectrum Wired

**Comment by Tenmaver** [comment]
https://www.minecraftforum.net/forums/support/java-edition-support/2865002-random-mouse-acceleration found this on the internet, may help you a little.

**Comment by kreezxil** [comment]
@CalciumDefficient this might also be relevant to you https://www.reddit.com/r/G502MasterRace/comments/6wlq5a/g502_mouse_acceleration/

in regards to not experiencing the issue when playing other packs. Other packs don't have the overhead this pack has is the primary reason.

This is not a pack issue, so i'm closing it, feel free to keep discussing in here tho
