### ISSUE TITLE
Splash Frames not to Size!

### ISSUE THREAD

**Issue by defranke00** [kreezxil/World-of-Dragons#432]
**Describe the bug**
After today's update, WOD decided it no longer wished to launch past the load screen. From the crash report (attached below) I have deduced the problem mod is SplashAnimation-0.2.1.jar. I disabled the mod with GDLauncher, and I no longer am receiving this issue 

**To Reproduce**
Might be a me side issue only *shrug*
1) Update pack through GD Launcher from previous version
2) Launch pack with GD Launcher
3) Watch where 'World of Dragons' used to be right after launching is now the 'Kreezcraft's World of Dragons' logo appears and does not disappear
4) Wait for crash report to come up with an unknown mod as the cause

**Versions:**

 - Minecraft: 1.12.2
 - Forge: forge-14.23.5.2847
 - Mod Pack : 21.12.269
 - Mod Name: Deduced to SplashAnimation
 - Mod Version: 0.2.1

**Logs**

https://gist.github.com/defranke00/b75979043cdf6215bd6897daf523d3f9
**Additional context**

After disabling SplashAnimation with GDLauncher, the game loaded right up. Multiplayer works fine with it disabled.

**Comment by kreezxil** [comment]
This is all me. At the last minute I resized the splash animations to a size that was incompatible with the mod. I wanted to drastically decrease the payload size while keeping the new animation.

**Comment by kreezxil** [comment]
fixed in build 270
