### ISSUE TITLE
[please add] Doom Items Mod

### ISSUE THREAD

**Issue by AzureDoom** [kreezxil/World-of-Dragons#434]
Mod Link: https://www.curseforge.com/minecraft/mc-mods/doom-items-mod

Reason: It's what I call my mini expansion for the Nether. Currently has 7 new sets of Armor, a new tier of gear and 2 new main weapons that are of course Mine and Slash integrated.  Currently does not require any new chunks as all items are craftable out of existing Nether materials. Like the Nether gear will be an upgrade for Diamond gear, all the Argent Energy tools are a step up from Diamond. 

Figured the next big Minecraft is the Nether so let's raise some Nether here now. Wiki for the mod is true for the most part across versions, with mostly just some armor materials being different due to them be different in the Minecraft versions. If you'd like any thing else explained about the mod, tag me on Discord.

**Comment by kreezxil** [comment]
added
