### ISSUE TITLE
[please fix] kicked to multiplayer screen

### ISSUE THREAD

**Issue by Diamond200512** [kreezxil/World-of-Dragons#437]
**Describe the bug**

**To Reproduce**
1. Go to multiplayer tab
2. Click on official server
3. click join
4. you get disconnected or java.IOException screen

**Screenshots**
![Screen Shot 2020-05-03 at 6 33 01 PM](https://user-images.githubusercontent.com/54332468/80928800-95f3f900-8d6c-11ea-8313-766c4401091d.png)
![Screen Shot 2020-05-03 at 6 33 01 PM](https://user-images.githubusercontent.com/54332468/80928873-3c3ffe80-8d6d-11ea-997b-ca7e253ade54.png)

**Versions:**

 - Minecraft:1.12.2
World of Dragons
v270 client hotfix

**Logs**
[latest.log.zip](https://github.com/kreezxil/World-of-Dragons/files/4571945/latest.log.zip)
Crash Report: 
Debug Log:
Latest Log:

**Additional context**
might be a problem only occurring on my mac. I have not had this issue before which is the reason I'm posting it.

also, doesnt always happen sometimes it loads when you dont have the screen selected or if you restart your computer right before trying to login.

**Comment by kreezxil** [comment]
how come you didn't use https://gist.github.com to paste your long as latest.log. and u know those screenshots of that error trigger everyone, you know this and you posted it not once but twice. You know who knows this and doesn't do it, because they know it's wrong but they also know how to use a pasting service?

Admin

Admin know how to do this.

Now I have download your fart stained underwear and pick thru the feces to find the error when it could've been a simple web link that rest of labrats could've used forensic gloves on.

**Comment by Diamond200512** [comment]
im pretty sure I pasted it in

**Comment by kreezxil** [comment]
you don't understand, you drag n dropped it in
that's now called pasting it in
do I need to make a video for this? wait, maybe I have made a video for this.

**Comment by kreezxil** [comment]
# this is drag n drop
![image](https://user-images.githubusercontent.com/3880072/80930018-11a67380-8d76-11ea-81f8-9985f72385a7.png)

# this is what is meant by pasting
open it, select all, the copy it (aka copy all)

go here and paste here
![image](https://user-images.githubusercontent.com/3880072/80930052-431f3f00-8d76-11ea-8afc-e907fb49cba7.png)

now hit submit (create public gist)
![image](https://user-images.githubusercontent.com/3880072/80930078-8d082500-8d76-11ea-9745-3a30c52f2196.png)

finally copy the new url and paste that in to the bug reports
![image](https://user-images.githubusercontent.com/3880072/80930105-ba54d300-8d76-11ea-9ab6-5bda269b3505.png)

**Comment by kreezxil** [comment]
after digging thru there seems to be a block on the server causing the problem
sadly the log doesn't say from which mod it is.

**Comment by Diamond200512** [comment]
im trying to paste the log into the link, but its going super slow now

**Comment by kreezxil** [comment]
because it's is actually pasting, the create part will be equally as long

**Comment by kreezxil** [comment]
because the log is huge

**Comment by Diamond200512** [comment]
it had an error

**Comment by Diamond200512** [comment]
I have to paste again

**Comment by AzureDoom** [comment]
> because the log is huge

![image](https://user-images.githubusercontent.com/7415711/80930140-7ca87800-8d7f-11ea-91d8-16e81dff273b.png)
 Not helpful to the issue but I refuse to not do this.

**Comment by Diamond200512** [comment]
lol

**Comment by Diamond200512** [comment]
it isnt pasting in it keepes giving an error
