### ISSUE TITLE
[Bug Report] [Mod Issue] Mine and Slash Map Device

### ISSUE THREAD

**Issue by defranke00** [kreezxil/World-of-Dragons#438]
https://github.com/RobertSkalko/Mine-and-Slash/issues/224

**Comment by kreezxil** [comment]
also need some words, aka advanced constructs of characters that form
thoughts. I need to know what the report is about.

**Comment by defranke00** [comment]
Multiple Map Devices Overwrites with most Current Map Created. All map devices show the exact same maps. Possible solution: prevent crafting of map device, have 1 community device at spawn, and player(s) will have to complete all 4 map trials in one sitting or forfeit what maps they have left.
