### ISSUE TITLE
Cybernetic Katana right click server crash

### ISSUE THREAD

**Issue by JonnyM1ke** [kreezxil/World-of-Dragons#439]
**Describe the bug**
Use of Cybernetic Katana Right Click crashed the server.

**To Reproduce**
1. Use Cybernetic Katana
2. Shift Right Click

**Versions:**
 - Minecraft: 1.15.2
 - Forge: 31.1.18
 - Mod Pack: Foreshadowing
 - Mod Name: PlantTech 2
 - Mod Version: 0.02.07

**Comment by kreezxil** [comment]
why did you close it?

**Comment by rwatson1** [comment]
When he said in the bot that the server crashed, pylon linked to the WOD github instead of the foreshadowing github, so he closed here and reposted there.
