### ISSUE TITLE
[please add] Soul Bottle Mod 

### ISSUE THREAD

**Issue by ParsaMT** [kreezxil/World-of-Dragons#44]
**use of this mod**
 piggy backpack is nice and all but i feel like we need more ways to transport animals and mobs. piggy backpack can only carry one mob at a time but with this mod we will be able to transport a good amount of mobs and we can store them in our inventory. 

**Additional context**
if you want the link: https://minecraft.curseforge.com/projects/soulbottle

**Comment by kreezxil** [comment]
never ever use links from 9minecraft they steal from the authors. Please find it on CurseForge.com

**Comment by ParsaMT** [comment]
> never ever use links from 9minecraft they steal from the authors. Please find it on CurseForge.com

done

**Comment by kreezxil** [comment]
https://minecraft.curseforge.com/projects/soulbottle <--- this is it, I'll add it to today's release.
