### ISSUE TITLE
enableActuallyEditions? wtf?!!

### ISSUE THREAD

**Issue by kreezxil** [kreezxil/World-of-Dragons#441]
this is in the enderio.cfg, this didn't rear it's head until I updated to forge build 14.23.5.2854.

Also, that means on build 272, I'll be removing ENDERIO also TECHREBORN. That latter was throwing issues too.

Major version 22 is next. world wipe recommend but not necessary as I'm only removing tech mods that should be adding much to worldgen.

**Comment by kreezxil** [comment]
just enable it and restart your server.

**Comment by defranke00** [comment]
Will the main WOD server be wiped? And is there an eta on that?

**Comment by kreezxil** [comment]
the main servers will not be wiped. i fixed the issue immediately yesterday
after the patch.

**Comment by defranke00** [comment]
I meant with major version 22. Many bases have enderio/techreborn machines and energy items.

**Comment by kreezxil** [comment]
not planning on removing enderio
