### ISSUE TITLE
Crash report error loading a mod.

### ISSUE THREAD

**Issue by NiffyFox** [kreezxil/World-of-Dragons#442]
**Describe the bug**
forge loads on the mods but once it reaches the mod below the game crashes, how ever after I removed the mods and ran the game  the mod pack loaded, and I added the mods back and its still worked.

**Versions:**
 - Minecraft:
 - Forge: 14.23.5.2854
 - Mod Pack 21.14.271
 - Mod Name: CraftTweaker2
 - Mod Version: 1.12-4.1.20.576

Crash Report:  https://paste.ubuntu.com/p/QVGWw9WDRT/

**Comment by kreezxil** [comment]
thank you for the report as identified on line 40 it was a ram allocation issue. that you fixed by allocating more ram.

From Discord chat explaining this:
```
Kreezxil: in twitch, if you click on the pancakes in the upper left corner and then settings, and then minecraft, you can adjust the globally allocated ram for packs
[6:24 PM] Kreezxil: set it to 8gb since you have 16 total
[6:24 PM] Kreezxil: and this issue will go away
[6:24 PM] Kreezxil: twitch and most launchers by default only allocate 2gb of ram
[6:24 PM] Kreezxil: GDL however allocates 4gb
```
