### ISSUE TITLE
[please add] Endergy

### ISSUE THREAD

**Issue by moonbeast32** [kreezxil/World-of-Dragons#444]
# Mod Nominated for Adding*
Mod Name: Ender IO Endergy
Mod Link: https://www.curseforge.com/minecraft/mc-mods/ender-io-endergy

# Reason for Nomination
Reason: Ender IO is a great tech mod. I love it's unique approach to mechanising and automizing the game. Unfortunately, IO's progression comes to a halt once you reach The End. This is especially jarring because the dark steel upgrade system, objectively IO's best feature, has only 2 tiers (Dark steel -> end plate).

Endergy, an addon created by the same ender io devs, addresses this issue by adding an additional tier of tools and armor. In addition to this, it also adds new alloys and capacitors for beefing up your machines just a bit further. Having a 3rd tier of equipment will help compensate for the fact that IO's original tools and armor are not modified by mine 'n slash.

This addon does not require any new terrain generation.

**Comment by Diamond200512** [comment]
Unless m&s compatability is added it wouldn’t compensate for the weapons not registering for it, because I’m pretty sure it just goes off of your base melee damage unless given a m&s value

**Comment by kreezxil** [comment]
m&s compat is already in the pack, you only have to look at the mod list to
see that.

**Comment by kreezxil** [comment]
added
