### ISSUE TITLE
Magician's Worktable Missing Event Components [Mod Author disabled this]

### ISSUE THREAD

**Issue by ScarredPast** [kreezxil/World-of-Dragons#449]
**Describe the bug**
When attempting to craft a spell in the Magician's Workbench, the Event Components, which allow dictation of whether the spell will exclusively effect Entities or Blocks, do not appear and are nonfunctional. They should be within the bottom left grid, underneath the grid containing the blue Shape components. Attached image relevant. Attempts to use them as if it's a simple missing texture were not fruitful. 

**To Reproduce**
1. Obtain Magician's Worktable
2. Open Magician's Worktable

**Screenshots**
![image](https://user-images.githubusercontent.com/69659665/90207277-d7f0fa00-ddb3-11ea-8f82-bb9d0fc5f65f.png)

**Versions:**
 - Minecraft: 1.12.2
 - forge-14.23.5.2854
 - World Of Dragons v21.17.274
 - Wizardry v0.10.8

Crash and debug logs N/A, reproduced by multiple players.

**Comment by kreezxil** [comment]
actually debug logs are not na, they always exist each run, just like
latest.logs. we will need latest.log. the debug log isn't necessary.

**Comment by kreezxil** [comment]
@ScarredPast have your multiple other players also follow this issue and add anything that they feel is relevant, also check the attached issue above at TeamWizardry as they will likely respond there first and not actually post here.

**Comment by kreezxil** [comment]
@ScarredPast you have received a response by the mod author. He said those events were removed because they were causing confusion.

That means if you want them bad enough, I will need to roll Wizardry down to a version where they existed, however that will bring with it other problems such as buggy versions of Wizardry.
