### ISSUE TITLE
[please add] Slashblade

### ISSUE THREAD

**Issue by ParsaMT** [kreezxil/World-of-Dragons#47]
# Mod Nominated for Adding*
Mod Name: SlashBlade
Mod Link: https://minecraft.curseforge.com/projects/slashblade

# Reason for Nomination

Reason: its very polished mod that add cool katanas that are not overpowered. (you can see the modpacks policy of the mod in the link above)

**Comment by kreezxil** [comment]
I bet you can still fly with one of the swords!

also added.
