### ISSUE TITLE
[please add] Simply jetpacks 2 

### ISSUE THREAD

**Issue by ParsaMT** [kreezxil/World-of-Dragons#48]
# Mod Nominated for Adding*
Mod Name:Simply jetpacks 2 
Mod Link: https://minecraft.curseforge.com/projects/simply-jetpacks-2

# Reason for Nomination

Reason: flying using some tech instead of mobs

**Comment by kreezxil** [comment]
so much for dragons, welcome to the **World of Jetpacks**!

mod added.
