### ISSUE TITLE
Fairy lights not placeable

### ISSUE THREAD

**Issue by Kanna2626** [kreezxil/World-of-Dragons#51]
The mod "fairy lights" allow you to place down lights. They are craft able and they do not disappear but they cannot be placed on any blocks. In either claims or unclaimed chunks they are unplaceable

**Comment by kreezxil** [comment]
I need you to post the solution.

**Comment by Kanna2626** [comment]
You need to put the lights you wish with the string of lights recipe in any pattern you want to be able to place down the lights
