### ISSUE TITLE
New Quest to Let Player Know about Conversion

### ISSUE THREAD

**Issue by HalestormXV** [kreezxil/World-of-Dragons#52]
Seem the connectors (not the relays) from Immersive Engineering handle conversion of IF to RF as a 1:1 ratio. So if you hook a connector up to a Tech Reborn machine for example and then run an IE wire, it should power the Tech Reborn machine. Might want to write some type of quest in so that players know this is a possibility.

**Comment by kreezxil** [comment]
done

**Comment by kreezxil** [comment]
ok, officially added to today's version. also thanks for adding the info to the wiki.
