### ISSUE TITLE
[please fix] No Pole issues with immersive engineering

### ISSUE THREAD

**Issue by HiggZyy** [kreezxil/World-of-Dragons#53]
**Describe the bug**
Essentially, I fell while placing a block and it gave me a different block back.. So I started experimenting with blocks from immersive engineering.. Steel posts when jump-placed gave 2 back.. silver blocks gave copper blocks back, etc. There are lots of issues with it currently 

**To Reproduce**
1. Grab pretty much any immersive engineering block (i.e. wooden post)
2. Jump and place the block at the same time (while not in creative mode obviously)
3. Pick up the blocks
4. Now you will see some wonky stuff happening!

**Screenshots**

**Versions:**

 - Minecraft: 1.12.2
 - Forge:
 - Mod Pack: World of Dragons-- Version 14.15.147 (haven't updated just yet but saw nothing about this issue)
 - Mod Name: No Pole and Immersive Engineering
 - Mod Version: Immersive Engineering-0.12-88  nonerdpoles-1.12.2-2.0.4

**Additional context**
Not sure if any fixes have been made; just wanted to point it out!

**Comment by kreezxil** [comment]
Ok, thanks for the report. I'll see what I can do about updating the mod "No Poles", yes it's my mod too, and if I can't resolve the issue in question, I'll remove it from the pack for this week's update.

**Comment by kreezxil** [comment]
Ok, I fixed this in the mod. This will be in the next update of the pack.

**Comment by HiggZyy** [comment]
Good deal. I checked thermal foundation and noticed it had the same types of issues too lol. Place an energy pipe down while jumping and you'll get a lead stone fluxduct back for example
