### ISSUE TITLE
[please add] Morpheus

### ISSUE THREAD

**Issue by AceWolf456** [kreezxil/World-of-Dragons#57]
Sleeping on a server can be hard, so would you consider adding Morpheus to the pack? 

The thing also said I should add a link to the mod so here it is. 
https://minecraft.curseforge.com/projects/morpheus/files/2432272

**Comment by kreezxil** [comment]
Adding morpheus will mean that the majority of players will be unable to
hunt and receive drops from the mobs that spawn at night. There are
multiple mods in place that will protect you during the night, they simply
have to be used.

If you can get 20 of the players to join this thread and ask for it, I'll
add it.

**Comment by kreezxil** [comment]
added
