### ISSUE TITLE
No Object for Minecolonies BarracksTower Placeholder

### ISSUE THREAD

**Issue by tanewell** [kreezxil/World-of-Dragons#58]
There is no object for the Minecolonies BarracksTower Placeholder, which is causing the Barracks to be impossible to build.

Currently running World of Dragons version 14.18.150

![barrackstower placeholder](https://user-images.githubusercontent.com/6810937/52523267-a0a10a80-2c5d-11e9-88c2-9600c8b5a2fa.JPG)

**Comment by kreezxil** [comment]
I talked with the developer and he said you don't need this to build the barracks. You simply place the barracks hut block and the builder does the rest including bringing towers. You don't place the towers yourself.
