### ISSUE TITLE
[mod request] Underground Biomes

### ISSUE THREAD

**Issue by Dryelo** [kreezxil/World-of-Dragons#6]
**Is your feature request related to a problem? Please describe.**
No problem here, a request for an additional mod.

**Describe the solution you'd like**
I'd like to see more variations of stone.

**Describe alternatives you've considered**
Would you consider adding the mod Underground Biomes to your modpack?
Or the newer fork "UBC - Reworked and Fixed"

**Additional context**
I love your modpack but I'm a bit tired of vanilla stone.
UBC adds many colorful variants with bricks, stairs and slabs.

One thing to test would be the ore generation. According to the author(s), UBC is compatible with many mods but I couldn't say if every mod with ore-gen in World of Dragons is supported.
As soon as you tell me that you would consider adding the mod I would gladly start some serious testing. :)

Hoping for feedback and keep up the great work!
Dryelo

**Comment by kreezxil** [comment]
currently I will not be adding new mods to the pack.
In January tho after the festivities are over and all school starts back up, I will be removing some of the bulkier mods from the pack and doing world wipes.
Then at that time I'll add this mod to the pack.

Considering that both Chisel and Chisels and Bits are in the pack I don't see where you are having a true problem, both give you vast capabilities in design.
![](https://i.imgur.com/lpVNP98.png)

**Comment by kreezxil** [comment]
added
