### ISSUE TITLE
[please fix] can't install pack

### ISSUE THREAD

**Issue by Dmitchell94** [kreezxil/World-of-Dragons#60]
**Describe the bug**
I run the Pterodactyl server manager and can not seem to get the server to install properly. As it does not exactly support the script install setup that you have I tried to manually just install the mods and the configs and was getting errors with world generation. if i let Pterodactyl setup the docker environment and then try to manually install via the scripts I can not because using command line it can not find java due to the docker environment setup. This makes installing this pack in this type of setup impossible. This has been the hardest server to ever setup! is there not an easier way to install the server?

**To Reproduce**
1. Go to Pterodactyl Panel
2. Create Server
3. Upload Server Install files
4. attempt to run install.sh
5. Get java not found error due to how pterodactyl runs servers
6. try to manually install java to location and repeat step 4 get step 5 again
7. cant install via scripts in this type of setup
8. try manual install of mods and configs and minecraft
9. world generation crashes on chunk generation making pack unplayable

**Screenshots**

**Versions:**

 - Minecraft: 1.12.2
 - Forge: what the scripts download
 - Mod Pack : what the scripts download
 - Mod Name: what the scripts download
 - Mod Version: what the scripts download

**Additional context**

**Comment by kreezxil** [comment]
the current forge you need to install is in the CURRENT_INSTALLER file.

Open that and copy the link, download that.

Then installl that server using java, ie
```
java -jar forgerINSTALLER.jar --installServer
```

The resulting non-installer file will be used to run the server.

upload the libraries, config, scripts, and mods folder to your server.

upload the forge.jar (whatever it was called after using the installer) to
your server

now you can start the server with java -jar
whaterver-the-forge-non-installer.jar nogui -Dfml.queryResult=confirm
-Xms4G -Xmx4G

# please describe in detail how you arrived at a problem
On linux you would use install.sh and then you would use ./start_server.sh
for session that dies upon terminal exit, or ./.start_Linux_Master.sh for
one that remains active thru all terminal sessions. If you move the files
from the folder you ran the ./install.sh in, you'll need to run it again.

On Windows with powershell, use .\install.ps1 and then .\start_server.ps1

**Comment by kreezxil** [comment]
btw, this is the same instructions as found at
https://github.com/kreezxil/World-of-Dragons/wiki/Managed-Server-Install

**Comment by Dmitchell94** [comment]
Yes but the problem is because of using docker environments only when the docker environment is called is java installed so before launching the docker environment that launchers the server java is not a valid command. Some reason this type of setup does not like either set of instructions. To install i created a centos7 vm on my desktop ran all the commands there and uploaded the resulting files. now it works fine. just seems to be an environment incompatibility as the environment does not recognize java till the server is started with docker

**Comment by kreezxil** [comment]
which is exactly what the managed server install insructions are. you have
to do it all on your side, you don't need linux you can do it with windows
too, then upload it to your docker container.
