### ISSUE TITLE
Minecolonies version on the Twitch launcher does not match the version on the server.

### ISSUE THREAD

**Issue by cubanmikey** [kreezxil/World-of-Dragons#61]
The version of the mod minecolonies in the pack is "minecolonies-1.12.2-0.10.168-ALPHA-universal.jar"
The version of the mod minecolonies in the server is "minecolonies-1.12.2-0.10.170-ALPHA-universal.jar"

Multiple attempts to reupdate after getting the error message stated that the client has the wrong version.

Checking the pack's installed mods, I found the mod minecolonies and clicked on it, then hit versions. This showed me that the pack had the "minecolonies-1.12.2-0.10.168-ALPHA-universal.jar" version of the mod installed, while the "minecolonies-1.12.2-0.10.170-ALPHA-universal.jar" was available through the Twitch launcher. I couldn't select it, however.

**Comment by cubanmikey** [comment]
After reinstalling build 151, the issue....
.....
......
still prevails.

**Comment by kreezxil** [comment]
fixed
