### ISSUE TITLE
[please add] Appleskin

### ISSUE THREAD

**Issue by EchoBlade24** [kreezxil/World-of-Dragons#62]
# Mod Nominated for Adding*
Mod Name: Appleskin
Mod Link: https://minecraft.curseforge.com/projects/appleskin

# Reason for Nomination

Reason: With mods like Animania, Vanilla Food Pantry, and Better with Mods adding in a large variety of food, it would be helpful if we were able to see how much hunger and saturation each one restored. Appleskin provides a nifty tooltip to show this.

**Comment by kreezxil** [comment]
excellent suggestion, I'll be adding this to the Monday update. Today's update will be featuring only one ip change.

**Comment by kreezxil** [comment]
done
