### ISSUE TITLE
[please add] Vic's modern warfare mod XD

### ISSUE THREAD

**Issue by ParsaMT** [kreezxil/World-of-Dragons#64]
# Mod Nominated for Adding*
Mod Name: Vic's modern warfare mod
Mod Link: https://minecraft.curseforge.com/projects/vics-modern-warfare-mod

# Reason for Nomination

Reason: i know its not suited for the modpack in anyway but we already have dinosaurs might as well add some good weapons the good thing is they are not over powered (i know this is a stupid suggestion but its worth a shot XD )

**Comment by kreezxil** [comment]
Added, it the tests are a success, it will stay. will be adding vehicles and roads too. We might as well go Jurassic Park on this.
