### ISSUE TITLE
[please add] mod name

### ISSUE THREAD

**Issue by daodragon** [kreezxil/World-of-Dragons#67]
# Mod Nominated for Adding*
Mod Name: packing tape
Mod Link: https://minecraft.curseforge.com/projects/packing-tape

# Reason for Nomination

Reason: adds a tape that can be used to move blocks with inventories without breaking them also can be used to move techreborn items( machines ) without the need of a wrench, is pretty cheap to make and can be used in a base inventory management. it also has a ver for 1.13 already so its not a mod that needs to be removed if world of dragons get updated to ver 1.13 so it wont be a short lived mod.

**Comment by kreezxil** [comment]
not going to add it, we have Chest Transporter which can be used to also move machines.

**Comment by daodragon** [comment]
that is not in the modpack either kree. unless its under a different name than Chest Transporter because i checked the installed mods.

**Comment by kreezxil** [comment]
ok, hmm, see if the dolly is in there, I think refined storage adds a dolly

**Comment by daodragon** [comment]
i did not find any in the files

**Comment by daodragon** [comment]
asked ladykanna26 to search up dolly for me in the jei ladykanna26 couldn't find it.
