### ISSUE TITLE
Blazing Fishing Rod (1 FPS Issue)

### ISSUE THREAD

**Issue by OmegaInferno49** [kreezxil/World-of-Dragons#7]
**Describe the bug**
Upon using the Blazing Fishing Rod from Advanced Fishing, it'd take your client to a grinding halt to 1 FPS.

**To Reproduce**
1. Obtain Blazing Fishing Rod from Nether loot chest
2. Use it in most likely, any body of water
3. Pull line in when the bobber goes down
And at that point, it will produce a large amount of fish entities, much more then you actually fished up, to make some sort of ungodly picture that lags the client out.

**Screenshots**
![2018-12-17_14 44 33](https://user-images.githubusercontent.com/11032837/50111734-76a60b80-020b-11e9-9fd3-58ef667a667e.png)
![2018-12-17_14 46 52__2](https://user-images.githubusercontent.com/11032837/50112044-427f1a80-020c-11e9-9917-5abbc52d02e5.png)
^ To the right, in the cave, you can see the entities just spewing out from the body of water from the other side.

**Versions:**
 - Minecraft: 1.12.2
 - Forge: 14.23.5.2796
 - Mod: Advanced Fishery

**Additional context**
Re-logging in the ONLY way to fix this issue, since it is the client, and not the server. I can only assume the client is being overloaded with so many items in this bizarre bug, pushing it's FPS to a complete halt of 1.

**Comment by kreezxil** [comment]
Solved by removing the mod from the pack. Can't wait on someone to fix it. So sad.
