### ISSUE TITLE
[please add] OpenBlocks

### ISSUE THREAD

**Issue by Drakyl** [kreezxil/World-of-Dragons#72]
# Mod Nominated for Adding*
Mod Name: OpenBlocks
Mod Link: available via twitch sorry could not find a site link

# Reason for Nomination
Reason: It has a few useful blocks that are convenient or decorative (i.e. vacuum hopper, xp grate, fans, clime able trap door etc.). Nothing about this mod is particularly OP or game breaking (that I know of).

**Comment by kreezxil** [comment]
the majority of my own mods will lose traction with this mod added. i'd rather not add it. Also which other mod would you like to see go. The pack is already really large, so to add this something has to go.

**Comment by Drakyl** [comment]
Me personally I could do without slash blade or Techguns. Especially Techguns as I understand the need for some tech mods for automation and processing, this mod, in my personal opinion doesn't feel like it fits the theme of the pack to me. Techguns also makes the mobs a lot harder for new people.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by kreezxil** [comment]
The two mods you mentioned were recent additions as requested by players as
of late. Get more players in here discussion what to remove and why, and
why this mod should be added.

**Comment by daodragon** [comment]
slashblade should be removed because its a mod by Japanese author which means getting any info is next to impossible and the jei and the translated wiki is too confusing and missing major info

**Comment by daodragon** [comment]
also the drop rate is too random

**Comment by Draconian4466** [comment]
What do you mean droprate? The slashblade mod dosent make mobs drop anything

**Comment by Draconian4466** [comment]
Also i think making mobs harder is good because there wasnt much of anything that could kill you and ive seen players say that dragons werent that hard

**Comment by Drakyl** [comment]
Mobs being harder doesn't bother me, but I've seen people struggle that's all. As for dragons they are only easy if you can range them.

**Comment by daodragon** [comment]
hey i don't say these thing about slash blade its what i gathered from the wiki and people on the server and  other sources.

**Comment by Drakyl** [comment]
I don't personally care for Slash blade, but some people like it so don't matter to me either way if it stays or goes, but if it can make room for other mods I say let it go ??

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Draconian4466** [comment]
Well i personally like the slashblade mod because it adds some more diversity to swords instead of a sword that just hits stuff it adds combos and cool attacks.

**Comment by kreezxil** [comment]
ok then

**Comment by kreezxil** [comment]
this will not be added because of 2 reasons that factor together.

1. it crashes the server
1. it doesn't produce a crash report, therefore I can't report the bug

**Comment by Drakyl** [comment]
That's fair

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
