### ISSUE TITLE
[please add] Moar Tinkers

### ISSUE THREAD

**Issue by Drakyl** [kreezxil/World-of-Dragons#73]
# Mod Nominated for Adding*
Mod Name: Moar Tinkers
Mod Link: Available on twitch

# Reason for Nomination

Reason: The mod adds tinker compatibility with other mods such as Botania, Tech Reborn, etc giving more options for tools/weapons/cosmetic armor.

**Comment by kreezxil** [comment]
you can find the mod links, by clicking on the mod in the Twitch app, and then choosing website on the next page.

I can add this, I had it before but took it out when I put the pack on a diet last year. I won't have to remove anything to add this.

**Comment by kreezxil** [comment]
bleep bloop

**Comment by kreezxil** [comment]
officially added
