### ISSUE TITLE
[please add] Armory Expansion

### ISSUE THREAD

**Issue by Drakyl** [kreezxil/World-of-Dragons#74]
# Mod Nominated for Adding*
Mod Name: Armory Expansion
Mod Link:  Available on Twitch

# Reason for Nomination

Reason:  Adds versatility and integration with other mods for Construct Armory.  Adds to integration between mods and also useful for cosmetic purposes.

**Comment by kreezxil** [comment]
I'll have to inspect this one to see what level new data it adds in size to the pack. It might be another one of those where I have to let something else go.

**Comment by kreezxil** [comment]
i hope we don't regret this

**Comment by kreezxil** [comment]
officially added
