### ISSUE TITLE
[please add] Tinker's Compendium

### ISSUE THREAD

**Issue by Drakyl** [kreezxil/World-of-Dragons#75]
# Mod Nominated for Adding*
Mod Name: Tinker's Compendium
Mod Link: Available via Twitch

# Reason for Nomination

Reason:  Cause it adds shields to tinkers and would fit well with most of the mods on the pack since most are magic/medieval based and they look cooler than currently available shields.

**Comment by kreezxil** [comment]
hmmm, something might have to go to fit this in to the pack.

**Comment by kreezxil** [comment]
added, let's see what happens.

**Comment by kreezxil** [comment]
added officially
