### ISSUE TITLE
[please fix] economy mod crashing

### ISSUE THREAD

**Issue by ParsaMT** [kreezxil/World-of-Dragons#76]
**Describe the bug**
 i was trying to put shops in spawn so i put down a vending machine from the economy mod and it turns out if you try to buy something from it if you dont have enough money in your credit card you'll get crashed.

**To Reproduce**
1. set up a vending machine
2. get your self a credit card
3. click buy

**Versions:**

 - Minecraft:1.12.2
 - Forge:14.23.5.2815
 - Mod Pack :14.27.159
 - Mod Name:economy inc
 - Mod Version: 1.5

**Comment by kreezxil** [comment]
I need the client crash report when this happens. Also closing this, because the old vending mod is back and I've removed this one.
