### ISSUE TITLE
[please fix] Crashes possibly connected to slashblades

### ISSUE THREAD

**Issue by Valarunga** [kreezxil/World-of-Dragons#79]
**Describe the bug**

**To Reproduce**
1. Go to Somewhere with mobs
2. Kill something with the second tier of slashblades
4. The game crashes

**Screenshots**

[crash-2019-03-04_18.01.55-server.txt](https://pastebin.com/uWD0YQct)

**Versions:**

 - Minecraft: 1.12.2
 - Forge:
 - Mod Pack : World of dragons version 14.28.160
 - Mod Name: SlashBlades
 - Mod Version: mc.1.12-r19.rar

**Additional context**

**Comment by kreezxil** [comment]
@Valarunga does the client crash too or just the server? because if the client is also crashing, I need that crash report as well. Thanks.

**Comment by Valarunga** [comment]
It was just the server

**Comment by kreezxil** [comment]
referenced elsewhere now.
