### ISSUE TITLE
Endergy

### ISSUE THREAD

**Issue by Draconian4466** [kreezxil/World-of-Dragons#8]
I belive this is the mod that makes the op stellar armor it does take neather stars to create but considering you can trap the wither in a diamond glass box neather stars arent that hard to get also if you fully upgrade the stellar armor it has 95% damage reduction on all pieces and in total about 40 armor

**Comment by kreezxil** [comment]
Explain this diamond box thing.

**Comment by Draconian4466** [comment]
you can make a box out of diamond glass and just hit the wither to death it dosent break out and you dont take damage

**Comment by OmegaInferno49** [comment]
Isn't the diamond glass the same glass from those diamond sand blocks? I was wondering what the use of those were.. And very disappointed they weren't diamonds!

**Comment by kreezxil** [comment]
Did you at least look and see what you could make with diamond sand?

**Comment by Draconian4466** [comment]
Yeah i did

**Comment by Draconian4466** [comment]
Im just saying you can make an indestructible box out of them

**Comment by OmegaInferno49** [comment]
Diamond sand is pretty popular in the below 20 I believe, so it'd be decently easy to gather, then all ya' gotta' do is probably drag the wither to bedrock, and spam the diamond glass, to my assumption.

**Comment by kreezxil** [comment]
How thick are you making the walls?

My tests showed that the wither can't physically penetrate the diamond glass.
The should skulls can't penetrate the diamond glass.
But the center skull can penetrate it and usually makes a hole big enough  for the entire wither to get through.

That would seem to tell me that way too much diamond sand is spawning below y 20.

**Comment by Draconian4466** [comment]
The walls are 1 block thick.

**Comment by kreezxil** [comment]
this mod is removed in Major version 14
