### ISSUE TITLE
[please fix] The teleport to player command (/tpa) not working

### ISSUE THREAD

**Issue by Drakyl** [kreezxil/World-of-Dragons#81]
**Describe the bug**
I believe you're already aware of this one, but just in case, the /tpa command is not working on World of Dragons US server

**To Reproduce**
1. Attempt to /tpa to player without administrator privileges

**Versions:**

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2815
 - Mod Pack: World of Dragons 14.28.160

**Comment by kreezxil** [comment]
fixed
