### ISSUE TITLE
[please fix] hemp fiber recipe not existing

### ISSUE THREAD

**Issue by EchoBlade24** [kreezxil/World-of-Dragons#82]
**Describe the bug**
Better with Mods was providing hemp fibers for use in Immersive engineering, and the Immersive Engineering hemp fibers had their recipe removed. In JEI, there isn't any way to create the fibers anymore.

**To Reproduce**
1. Search Hemp Fiber in JEI
2. Click on it to see the recipes to make it

**Screenshots**
http://prntscr.com/mu7mrh

**Versions:**

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2815
 - Mod Pack : WoD Version 14.31.163
 - Mod Name: Immersive Engineering
 - Mod Version: 0.12 - 89

**Additional context**

**Comment by kreezxil** [comment]
I added a recipe in build 164 that converts 1 tinkers compendium hemp fiber to 4 immersive engineering industrial hemp seeds.
