### ISSUE TITLE
[please fix] Crash possibly related to astral sorcery

### ISSUE THREAD

**Issue by Valarunga** [kreezxil/World-of-Dragons#84]
**Describe the bug**

**To Reproduce**
1. Go to a mob farm, gather a lot of mobs
2. Kill them all
3. 

**Screenshots**

**Versions:**

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2815
 - Mod Pack : 14.31.163
 - Mod Name: Astral sorcery
[crash-2019-03-07_18.31.27-server.txt](https://github.com/kreezxil/World-of-Dragons/files/2942525/crash-2019-03-07_18.31.27-server.txt)

 - Mod Version:

**Additional context**

[crash-2019-03-07_18.31.27-server.txt](https://github.com/kreezxil/World-of-Dragons/files/2942535/crash-2019-03-07_18.31.27-server.txt)

**Comment by kreezxil** [comment]
are you able to repeat this?

**Comment by kreezxil** [comment]
https://github.com/TheRandomLabs/RandomPatches/issues/29

**Comment by Valarunga** [comment]
Yes it happens everytime i try to xp farm and too Many entities build up or something

**Comment by kreezxil** [comment]
this is the same #79 and it's all related to randompatches.

**Comment by kreezxil** [comment]
I"ve just been notified of another fix to randompatches, we won't see the fix applied until Monday tho.

**Comment by kreezxil** [comment]
the new randompatches has been installed, still going to leave this open until i'm sure that there are no more crashes. If you are here to report this crash on the pack, please just say you are still having it and attach your crash report also use pastebin.com to do that

**Comment by kreezxil** [comment]
Seems to be fixed.

Create a new issue if this happens again.
