### ISSUE TITLE
[please fix]Quest book is broken

### ISSUE THREAD

**Issue by zhongjiedong** [kreezxil/World-of-Dragons#85]
Betterwithmods has been removed in latest release and most of the getting started quest page is reliant on it.

**Comment by kreezxil** [comment]
if you are playing on a server that is not one of mine, then you need to
have the staff of that server copy the config/ftbquests line over from the
server pack to their server's config folder. I have adjusted for this
already.

**Comment by D3adlad** [comment]
Unless there is some buried way to re-tool the FTB questbook, i'm seeing the same thing.  Not into the lingo particularly, but just downloaded this from Twitch and the questbook is definitely needing the betterwithmods mod from a fresh DL as of today.

**Comment by D3adlad** [comment]
Also, not on a multiplayer server (just single player, simple)...

**Comment by kreezxil** [comment]
ok

**Comment by zhongjiedong** [comment]
> Also, not on a multiplayer server (just single player, simple)...

It's on both, but I did read the changelog now and it was intentionally removed so I will just ignore that quest page

**Comment by kreezxil** [comment]
hopefully fixed in todays build 164
