### ISSUE TITLE
[please fix] taking up unholy amounts of RAM

### ISSUE THREAD

**Issue by burgrr** [kreezxil/World-of-Dragons#87]
**Describe the bug**
I have 8 gigs of ram allocated but the modpack requires even more of that to run. It takes up the full amount of 8 gigs just to run at barely 1 fps, and I imagine if I allocated my full 16 somehow it still would take up all of it. 

**To Reproduce**
1. Install modpack.
2. Start new world.
3. Wait for world to load.
4. See lag.

**Versions:**

 - Minecraft: 1.12.2
 - Forge: Whatever version is installed by the Twitch launcher. 
 - Mod Pack : 14.32.164
 - Mod Name: N/A
 - Mod Version: N/A

**Additional context**
This is not an issue with my setup since I tested it on my laptop and it had the exact same issues. This is also the only modpack I've ever had this issue with. Every other pack I've tried runs perfectly.

**Comment by kreezxil** [comment]
show me a screen shot of your ram allocation for Twitch app for minecraft.

**Comment by burgrr** [comment]
[
![Screenshot_6](https://user-images.githubusercontent.com/34227469/54077543-8750a580-427f-11e9-8800-9819a18b398b.png)
](url)

**Comment by kreezxil** [comment]
Is your Java updated. Without a log it's hard to find why you can't load
the pack.

After powering it up and getting the 1 fps, press and hold f3 and 'c'
simultaneously for 10 seconds then release. This will force the pack to
generate a crash report. Attach that crash report in its entirety and
remember to use pastebin.com or similar.

**Comment by burgrr** [comment]
Figured out what's causing the memory usage - it's FoamFix. Anyone with this issue in the future, go into FoamFix (there'll be two entries in the mod options) and turn texture anims off. Works like a charm.
