### ISSUE TITLE
Lower defence (Moar tinkers)

### ISSUE THREAD

**Issue by Draconian4466** [kreezxil/World-of-Dragons#88]
Moar tinkers allows you to make extremely op armor some with 80 defence so all other armor is useless so it would be great if the amount of defence it gives ia lowered or the mod is removed

**Comment by Drakyl** [comment]
I'm ok with lowering the defense on the armors, but would rather not see it removed as I quite like the variety it brings.  My understanding is this can be changed in the config.  It's not so much the armor as the armor toughness that makes the difference though from my understanding. In either case both can be tweaked, but some materials like Gaia ingots should be worth something given the effort needed to obtain them, but things like Titanium and Pandorium which are relatively easy to get should be more in line with Manyullyn or steel or similar mats.

**Comment by Draconian4466** [comment]
I know but there are just some armors that have to much armor for no reason i wouldnt like to see the mod get removed either and i hope the defence gets tweaked but if nothing else i would rather have it removed than it staying

**Comment by Draconian4466** [comment]
Also it seems the higher the toughness the less damage from high damaging attacks

**Comment by Draconian4466** [comment]
And another issue with one of the addons (its either this one or compendium) is that it adds a bunch of uncraftable armor parts weapons ect.

**Comment by kreezxil** [comment]
please don't put multiple issues together, also when words feel lacking
provide screen shots, also moar tinkers doesn't allow defence tweaks what
it does do is give more metals to tinkers, so it's not what you think it
is.

**Comment by Draconian4466** [comment]
![2019-03-14_09 50 20](https://user-images.githubusercontent.com/45436964/54371352-da8b7500-463e-11e9-9643-fc3bfcb874e4.png)

**Comment by Draconian4466** [comment]
added by moar tinkers

**Comment by Draconian4466** [comment]
![2019-03-14_09 56 09](https://user-images.githubusercontent.com/45436964/54371701-7917d600-463f-11e9-9e1d-41db9b43579b.png)
these are all added by moar tinkers and half of them are uncraftable

**Comment by Draconian4466** [comment]
![2019-03-14_10 03 04](https://user-images.githubusercontent.com/45436964/54372186-71a4fc80-4640-11e9-8f27-cb0bfe01dfd6.png)
![2019-03-14_10 03 01](https://user-images.githubusercontent.com/45436964/54372191-749fed00-4640-11e9-80c0-b1ae26e1a06b.png)
all the shards are added by moar tinkers and are uncraftable

**Comment by kreezxil** [comment]
it says "material added by moar tinkers", something else is controlling the
defense values

Notice that the attached config has no values for the defense or hardness
or anything, it simply adds or does not add the material.

**Comment by Draconian4466** [comment]
Tinkers.compendium maybe?

**Comment by Draconian4466** [comment]
Also in the config if it says adds or does not add can you make it so it dosent add things like psi metal and draconium because it might confuse some players

**Comment by kreezxil** [comment]
Y is that an issue? some players are confused by cars and some are confused
by tinkers and some are confused by thermal expansion

You know my plate is full, why not edit the configs, you do have them in
your clients and send me the updated configs and then I'll sync those to
the servers and subsequently the next pack update.

**Comment by Drakyl** [comment]
If no one gets to it first I'll see what I can figure out on the configs when I'm off on Tuesday

**Comment by Drakyl** [comment]
OK. I think I found how the disable the unavailable mats and any other mats we might want to disable that's easy enough, but to change the stats may require another mod.  From what I found tweakers construct is supposed to allow this via a config file. testing to see if I can get it to work will let you know if I can.

**Comment by Drakyl** [comment]
ok so Tweakers Construct worked. I was able to make Titanium match Manyullyn stats as a test.  Now I just need to set up all of the mats to be more reasonable stat wise and edit the unusable mats from the Tinker's Compendium config and that should fix this issue, but will take me some time to do.  I'll share the config file once done and tested

**Comment by Drakyl** [comment]
Also note if we add any mods that will use the mats we'll be disabling (i.e. Psi for example) this will have to be reversed and the mats will likely need to be adjusted too.

**Comment by kreezxil** [comment]
@Drakyl did we succeed in lowering defense?
