### ISSUE TITLE
[please fix] iron barrel not craftable

### ISSUE THREAD

**Issue by zhongjiedong** [kreezxil/World-of-Dragons#89]
**Describe the bug**
Iron barrel from techguns uncraftable as it defaults to paint gun barrel from Fureniku's 

**To Reproduce**
Attempt to craft iron barrel

**Comment by Draconian4466** [comment]
Ok so if you look at a normal crafting table under the paintgun barrel there is a small triangle click that it switches to the iron barrel

**Comment by zhongjiedong** [comment]
> Ok so if you look at a normal crafting table under the paintgun barrel there is a small triangle click that it switches to the iron barrel

Thanks! Did not know about this, much appreciated.

**Comment by kreezxil** [comment]
Thanks for your report, we'll use this information to add a new recipe to
remove the conflict.
