### ISSUE TITLE
[please add] DimensionalDoors (but maybe not yet)

### ISSUE THREAD

**Issue by kingslayer296** [kreezxil/World-of-Dragons#91]
Mod Name: DimensionalDoors
Mod Link: https://minecraft.curseforge.com/projects/dimensionaldoors

adds: extra-dimensional dungeons filled with traps

possible issues: some of those traps are lava based, so retrieving graves may become an issue. upon death it sends you to limbo that you must traverse and can make you die several times before returning to the overworld, and in a near-random place. also there are personal pocket-dimensions that may cause issues if a lag machine is built. some of these are planing to be fixed (like limbo making you lose items) but it hasn't been updated yet.

**Comment by kreezxil** [comment]
I'm not gong to add this, we just removed a mod that made it's own dimensions. Apparently mods that create their own dimensions don't do so well in this pack.

Thanks for the input tho.

**Comment by kingslayer296** [comment]
the main feature of the mod is that it has a big dungeon full of puzzles made of redstone and mazes. if there was any other mod that i knew of like that, id want that added.

**Comment by kreezxil** [comment]
yeah i won't be adding this, because of that. I've already nixed a few mods
because their dimensions didn't play well with others.

don't stop with the ideas tho.
