### ISSUE TITLE
[feature request] make dragons more range resistant

### ISSUE THREAD

**Issue by kingslayer296** [kreezxil/World-of-Dragons#92]
dragons can be pretty easy to beat if you cheese them.

mine and drakyl's solution: make dragons resistant to ranged attacks, however to make sure that others have a chance against lower tiers is to have that resistance scale with how big it is.

**Comment by kreezxil** [comment]
I can make them range resistant but it won't scale, it'll be a global
apply. The only thing that scales is their health.

**Comment by kreezxil** [comment]
Dragons already search 96 blocks for a target. I suspect this is not the same thing. Further suggest you post about it on the Ice and Fire developer github as a feature request.
