### ISSUE TITLE
[Please add] the 'forestry' mod

### ISSUE THREAD

**Issue by SlyStorm2608** [kreezxil/World-of-Dragons#93]
Mod name: forestry
Mod link: https://minecraft.curseforge.com/projects/forestry

I would like to have this mod added as I feel it would add another lengthy mod for player to do and it would make the world feel more alive

**Comment by kreezxil** [comment]
How would it make the world feel more alive.

**Comment by SlyStorm2608** [comment]
I think it would by adding a variety in the trees we see around the world and adding a few blocks (like beehives) that would make it feel like animals actually lived in the world other than pigs and cows.

**Comment by kreezxil** [comment]
oh you want animals, this is added but it's your fault everyone is gong to be eaten by lions now.
