### ISSUE TITLE
Updating to 166 breaks everything

### ISSUE THREAD

**Issue by zhongjiedong** [kreezxil/World-of-Dragons#95]
Just did a server update to 166, all currently generated dynamic trees are broken, see screenshot:

https://imgur.com/a/GuRw6pe

Many items deleted such as smeltery blocks, steve's cart carts, chisel blocks and also player inventories.

Many missing textures from tech reborn.

Many items have been changed, for example acorns into Dark Oak Horizontal timber frames

Also cannot get any of this back since it seems the server was not doing auto backups

**Comment by kreezxil** [comment]
did you update from 165 to 166 or from something far earlier?

further the server only does backups if you turned them on in
ftbutilities.cfg or used another backup method.

My two official servers aren't broken at all. Did you add something to pack
and forget to add it back after the update?

what about other player bases?

**Comment by zhongjiedong** [comment]
Was from 165 to 166, I guess I must have screwed something up in the update process but I've done it 3 times before since 163 with no issues =/

Guess I'll configure the backups, thanks :)
