### ISSUE TITLE
[Please add] Nature's Compass

### ISSUE THREAD

**Issue by SlyStorm2608** [kreezxil/World-of-Dragons#99]
Mod link: https://minecraft.curseforge.com/projects/natures-compass

I would like Nature's compass to be add because, as I've now experienced, finding a specific biome in a mod pack that adds more can be very difficult without RTP and adding nature's compass will allow people to more easily locate and travel to specific biomes. If you think it's too powerful to be able to find any biome anywhere on the map, the range of the compass can be changed in the config files

**Comment by kreezxil** [comment]
this is a good mod to add, I was gonna add it if the dust would settle long
enough that I could remember to add it. thanks for making a request for it,
this will allow it to get added much sooner, like next Monday if we don't
have any more major issues.

**Comment by kreezxil** [comment]
As I have figured out how to fix the Forestry issue without writing code, I'll be release build 169 of WOD today which will include this mod.
